import {
  Home,
  Route,
  Database,
  Palette,
  Search,
  Box,
  Layers,
  AlertTriangle,
  AlertCircle,
  Hash,
  Ruler,
  Paperclip,
  Music,
  User,
  Hexagon,
  Tag,
  ScanLine,
  Grid3x3,
  Calendar,
  ChevronRight,
  MessageSquare,
  SquareStack,
  Square,
  Globe,
  Grip,
  Monitor,
  Camera,
  CardSim,
  Check,
  ChevronDown,
  ChevronsRight,
  Circle,
  Terminal,
  Keyboard,
  Type,
  List,
  Play,
  PenTool,
  Bookmark,
  ScrollText,
  ArrowUpDown,
  MessageCircle,
  CircleDot,
  CircleAlert,
  SlidersHorizontal,
  CalendarDays,
  Star,
  ArrowLeftRight,
  Loader,
  ArrowDownToLine,
  QrCode,
  SearchCode,
  Cog,
  Workflow,
  Sparkles,
  Cloud,
  BarChart3,
  FileText,
  Lock,
  Settings,
  Layout,
  PanelLeft,
  PanelTop,
  LayoutDashboard,
  DollarSign,
  Quote,
  HelpCircle,
  Bot,
  Command,
  FileCode,
  MessageSquareCode,
  Briefcase,
  ShoppingBag,
  MessageCircleMore,
  Users,
  GraduationCap,
  BriefcaseBusiness,
  UtensilsCrossed,
  Building2,
  Timer,
  Table,
  Folder,
  Image,
  Hand,
  Bell,
  Minus,
  ToggleLeft,
  ToggleRight,
  Contact,
} from "lucide-react";

export const navigationSections: NavSection[] = [
  {
    title: "Get Started",
    icon: <Star className="h-4 w-4" />,
    description: "Core concepts and fundamentals",
    links: [
      { label: "Home", href: "/", icon: <Home className="h-4 w-4" /> },
      { label: "Routing", href: "/routing", icon: <Route className="h-4 w-4" />, desc: "File-based routing, dynamic routes, layouts, navigation" },
      { label: "Data Fetching", href: "/data-fetching", icon: <Database className="h-4 w-4" />, desc: "Server-side data loading, caching, streaming" },
      { label: "Styling", href: "/styling", icon: <Palette className="h-4 w-4" />, desc: "Tailwind CSS, themes, responsive design" },
    ],
  },
  {
    title: "Registry",
    icon: <Search className="h-4 w-4" />,
    description: "Component registry platform",
    links: [
      { label: "Components", href: "/components", icon: <Box className="h-4 w-4" />, desc: "Browse the component registry" },
    ],
  },
  {
    title: "Components",
    icon: <Layers className="h-4 w-4" />,
    description: "Reusable UI primitives",
    links: [
      { label: "Accordion Menu", href: "/accordion-menu", icon: <List className="h-4 w-4" />, desc: "Multi-level accordion navigation menu" },
      { label: "Accordion", href: "/accordion", icon: <ChevronsRight className="h-4 w-4" />, desc: "Single, multiple, icon accordions" },
      { label: "Activity Feed", href: "/activity-feed", icon: <ScrollText className="h-4 w-4" />, desc: "Real-time activity and notification feed" },
      { label: "Alert Dialog", href: "/alert-dialog", icon: <AlertTriangle className="h-4 w-4" />, desc: "Modal alert dialogs with confirm/cancel" },
      { label: "Alert", href: "/alert", icon: <AlertCircle className="h-4 w-4" />, desc: "Alert messages, banners, notifications" },
      { label: "Animated Counter", href: "/animated-counter", icon: <Hash className="h-4 w-4" />, desc: "Animated number counter with easing" },
      { label: "Aspect Ratio", href: "/aspect-ratio", icon: <Ruler className="h-4 w-4" />, desc: "Maintain consistent aspect ratios" },
      { label: "Attachment", href: "/attachment", icon: <Paperclip className="h-4 w-4" />, desc: "File attachments with preview and actions" },
      { label: "Audio Player", href: "/audio-player", icon: <Music className="h-4 w-4" />, desc: "Audio player with waveform visualization" },
      { label: "Avatar", href: "/avatar", icon: <User className="h-4 w-4" />, desc: "User avatars, groups, status rings" },
      { label: "Background Patterns", href: "/background-patterns", icon: <Hexagon className="h-4 w-4" />, desc: "SVG background pattern generators" },
      { label: "Badge", href: "/badge", icon: <Tag className="h-4 w-4" />, desc: "Colored badges, dots, status indicators" },
      { label: "Barcode Scanner", href: "/barcode-scanner", icon: <ScanLine className="h-4 w-4" />, desc: "Barcode and QR code scanner" },
      { label: "Bento Grid", href: "/bento-grid", icon: <Grid3x3 className="h-4 w-4" />, desc: "Masonry-style bento layout grid" },
      { label: "Booking Calendar", href: "/booking-calendar", icon: <Calendar className="h-4 w-4" />, desc: "Appointment and booking calendar" },
      { label: "Breadcrumb", href: "/breadcrumb", icon: <ChevronRight className="h-4 w-4" />, desc: "Navigation breadcrumbs" },
      { label: "Bubble", href: "/bubble", icon: <MessageSquare className="h-4 w-4" />, desc: "Chat bubbles and message variants" },
      { label: "Button Group", href: "/button-group", icon: <SquareStack className="h-4 w-4" />, desc: "Grouped buttons with shared state" },
      { label: "Button Spotlight", href: "/button-spotlight", icon: <Sparkles className="h-4 w-4" />, desc: "Spotlight hover effect buttons" },
      { label: "Buttons", href: "/buttons", icon: <Square className="h-4 w-4" />, desc: "Variants, sizes, icons, loading states" },
      { label: "Camera Capture", href: "/camera-capture", icon: <Camera className="h-4 w-4" />, desc: "Webcam photo and video capture" },
      { label: "Cards", href: "/cards", icon: <CardSim className="h-4 w-4" />, desc: "Cards, tiles, media cards, interactive" },
      { label: "Checkbox", href: "/checkbox", icon: <Check className="h-4 w-4" />, desc: "Checkboxes with labels and states" },
      { label: "Chip", href: "/chip", icon: <Tag className="h-4 w-4" />, desc: "Compact chip and tag elements" },
      { label: "Collapsible", href: "/collapsible", icon: <ChevronDown className="h-4 w-4" />, desc: "Expandable and collapsible content" },
      { label: "Color Picker", href: "/color-picker", icon: <Circle className="h-4 w-4" />, desc: "HSL/RGB color picker with swatches" },
      { label: "Combobox", href: "/combobox", icon: <ChevronDown className="h-4 w-4" />, desc: "Searchable dropdown selects" },
      { label: "Command", href: "/command", icon: <Command className="h-4 w-4" />, desc: "Command palette with search" },
      { label: "Countdown", href: "/countdown", icon: <Timer className="h-4 w-4" />, desc: "Countdown timer with days/hours/minutes/seconds" },
      { label: "Currency Input", href: "/currency-input", icon: <DollarSign className="h-4 w-4" />, desc: "Formatted currency input with locale support" },
      { label: "Data Table", href: "/data-table", icon: <Table className="h-4 w-4" />, desc: "Data tables with sorting and filtering" },
      { label: "Date Picker", href: "/date-picker", icon: <CalendarDays className="h-4 w-4" />, desc: "Calendar date selection" },
      { label: "Dependency Graph", href: "/dependency-graph", icon: <Workflow className="h-4 w-4" />, desc: "Interactive SVG dependency graph with layered layout" },
      { label: "Direction", href: "/direction", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "RTL/LTR direction provider" },
      { label: "Dock", href: "/dock", icon: <Monitor className="h-4 w-4" />, desc: "macOS-style magnifying dock launcher" },
      { label: "Drag Drop Zone", href: "/drag-drop-zone", icon: <ArrowDownToLine className="h-4 w-4" />, desc: "Drag-and-drop file upload zone" },
      { label: "Drawer", href: "/drawer", icon: <PanelLeft className="h-4 w-4" />, desc: "Slide-in drawer panels" },
      { label: "Dropdown Menu", href: "/dropdown-menu", icon: <ChevronDown className="h-4 w-4" />, desc: "Dropdown menus with items" },
      { label: "Field", href: "/field", icon: <Ruler className="h-4 w-4" />, desc: "Form field wrapper with label" },
      { label: "File Tree", href: "/file-tree", icon: <Folder className="h-4 w-4" />, desc: "Expandable file/folder tree view" },
      { label: "File Upload", href: "/file-upload", icon: <Paperclip className="h-4 w-4" />, desc: "File upload with drag-and-drop preview" },
      { label: "Floating Toolbar", href: "/floating-toolbar", icon: <Grip className="h-4 w-4" />, desc: "Floating context-aware toolbar" },
      { label: "Forms", href: "/forms", icon: <FileText className="h-4 w-4" />, desc: "Form layouts, validation, multi-step" },
      { label: "Gallery", href: "/gallery", icon: <Image className="h-4 w-4" />, desc: "Image gallery with lightbox" },
      { label: "Gesture Area", href: "/gesture-area", icon: <Hand className="h-4 w-4" />, desc: "Touch gesture detection area" },
      { label: "Grid", href: "/grid", icon: <Grid3x3 className="h-4 w-4" />, desc: "Responsive CSS grid layouts" },
      { label: "Heat Map", href: "/heat-map", icon: <BarChart3 className="h-4 w-4" />, desc: "Data heat map visualization" },
      { label: "Hover Card", href: "/hover-card", icon: <CardSim className="h-4 w-4" />, desc: "Hover-triggered preview cards" },
      { label: "Icon Picker", href: "/icon-picker", icon: <Sparkles className="h-4 w-4" />, desc: "Searchable icon picker grid" },
      { label: "Image Comparison", href: "/image-comparison", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "Before/after image comparison slider" },
      { label: "Image", href: "/image", icon: <Image className="h-4 w-4" />, desc: "Responsive image with lazy loading" },
      { label: "Infinite Scroll", href: "/infinite-scroll", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Infinite scrolling list loader" },
      { label: "Input Group", href: "/input-group", icon: <Keyboard className="h-4 w-4" />, desc: "Grouped inputs with addons" },
      { label: "Input OTP", href: "/input-otp", icon: <Lock className="h-4 w-4" />, desc: "One-time password input" },
      { label: "Inputs", href: "/inputs", icon: <Type className="h-4 w-4" />, desc: "Text inputs, selects, checkboxes, switches" },
      { label: "Item", href: "/item", icon: <Square className="h-4 w-4" />, desc: "List item component" },
      { label: "JSON Tree Viewer", href: "/json-tree-viewer", icon: <FileCode className="h-4 w-4" />, desc: "Expandable JSON tree viewer" },
      { label: "Kbd", href: "/kbd", icon: <Keyboard className="h-4 w-4" />, desc: "Keyboard shortcut indicators" },
      { label: "Keyboard Shortcuts", href: "/keyboard-shortcuts", icon: <Keyboard className="h-4 w-4" />, desc: "Keyboard shortcut reference modal" },
      { label: "Label", href: "/label", icon: <Type className="h-4 w-4" />, desc: "Form labels" },
      { label: "List", href: "/list", icon: <List className="h-4 w-4" />, desc: "Virtualized list component" },
      { label: "Lottie Player", href: "/lottie-player", icon: <Play className="h-4 w-4" />, desc: "Lottie animation player" },
      { label: "Markdown Editor", href: "/markdown-editor", icon: <PenTool className="h-4 w-4" />, desc: "Rich markdown editor with preview" },
      { label: "Marker", href: "/marker", icon: <Bookmark className="h-4 w-4" />, desc: "Highlight marker component" },
      { label: "Masonry", href: "/masonry", icon: <Grid3x3 className="h-4 w-4" />, desc: "Masonry grid layout" },
      { label: "Menubar", href: "/menubar", icon: <PanelTop className="h-4 w-4" />, desc: "Horizontal menu bars" },
      { label: "Message Scroller", href: "/message-scroller", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Auto-scrolling message list" },
      { label: "Message", href: "/message", icon: <MessageCircle className="h-4 w-4" />, desc: "Message display component" },
      { label: "Multi Select", href: "/multi-select", icon: <Check className="h-4 w-4" />, desc: "Multi-select dropdown with tags" },
      { label: "Native Select", href: "/native-select", icon: <ChevronDown className="h-4 w-4" />, desc: "Native HTML select elements" },
      { label: "Navigation Menu", href: "/navigation-menu", icon: <Globe className="h-4 w-4" />, desc: "Navigation menu component" },
      { label: "Notification", href: "/notification", icon: <Bell className="h-4 w-4" />, desc: "Notification bell with badge count" },
      { label: "Number Input", href: "/number-input", icon: <Hash className="h-4 w-4" />, desc: "Numeric input with stepper controls" },
      { label: "Pagination", href: "/pagination", icon: <ChevronRight className="h-4 w-4" />, desc: "Page numbers, prev/next, compact" },
      { label: "Password Strength", href: "/password-strength", icon: <Lock className="h-4 w-4" />, desc: "Password strength meter indicator" },
      { label: "Pin Input", href: "/pin-input", icon: <Lock className="h-4 w-4" />, desc: "PIN/OTP digit input" },
      { label: "Progress", href: "/progress", icon: <Loader className="h-4 w-4" />, desc: "Progress bars and indicators" },
      { label: "Progress Bar", href: "/progress-bar", icon: <Loader className="h-4 w-4" />, desc: "Animated progress bar variants" },
      { label: "QR Code", href: "/qr-code", icon: <QrCode className="h-4 w-4" />, desc: "QR code generator" },
      { label: "Radio Group", href: "/radio-group", icon: <CircleDot className="h-4 w-4" />, desc: "Radio button groups" },
      { label: "Range Calendar", href: "/range-calendar", icon: <CalendarDays className="h-4 w-4" />, desc: "Date range calendar picker" },
      { label: "Rating Stars", href: "/rating-stars", icon: <Star className="h-4 w-4" />, desc: "Star rating with half-star support" },
      { label: "Resizable", href: "/resizable", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "Resizable panels" },
      { label: "Rich Text Editor", href: "/rich-text-editor", icon: <PenTool className="h-4 w-4" />, desc: "WYSIWYG rich text editor" },
      { label: "Scroll Area", href: "/scroll-area", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Custom scroll containers" },
      { label: "Search Input", href: "/search-input", icon: <Search className="h-4 w-4" />, desc: "Search input with debounced results" },
      { label: "Select", href: "/select", icon: <ChevronDown className="h-4 w-4" />, desc: "Custom select dropdowns" },
      { label: "Separator", href: "/separator", icon: <Minus className="h-4 w-4" />, desc: "Visual dividers" },
      { label: "Sheet", href: "/sheet", icon: <PanelLeft className="h-4 w-4" />, desc: "Slide-out sheet panels" },
      { label: "Slider", href: "/slider", icon: <SlidersHorizontal className="h-4 w-4" />, desc: "Range sliders" },
      { label: "Spinner", href: "/spinner", icon: <Loader className="h-4 w-4" />, desc: "Loading spinners" },
      { label: "Spotlight Search", href: "/spotlight-search", icon: <SearchCode className="h-4 w-4" />, desc: "Cmd+K spotlight search overlay" },
      { label: "Stepper", href: "/stepper", icon: <ChevronsRight className="h-4 w-4" />, desc: "Step-by-step wizard stepper" },
      { label: "Steps", href: "/steps", icon: <ChevronsRight className="h-4 w-4" />, desc: "Progress step indicators" },
      { label: "Streaming Response", href: "/streaming-response", icon: <Sparkles className="h-4 w-4" />, desc: "AI streaming response display" },
      { label: "Switch", href: "/switch", icon: <ToggleLeft className="h-4 w-4" />, desc: "Toggle switch component" },
      { label: "Table", href: "/table", icon: <Table className="h-4 w-4" />, desc: "Data tables, sorting, filtering, sticky" },
      { label: "Tabs", href: "/tabs", icon: <PanelTop className="h-4 w-4" />, desc: "Tabbed interfaces" },
      { label: "Tags", href: "/tags", icon: <Tag className="h-4 w-4" />, desc: "Tag input with autocomplete" },
      { label: "Terminal Emulator", href: "/terminal-emulator", icon: <Terminal className="h-4 w-4" />, desc: "In-browser terminal with custom commands" },
      { label: "Textarea", href: "/textarea", icon: <Type className="h-4 w-4" />, desc: "Multi-line text inputs" },
      { label: "Timeline", href: "/timeline", icon: <ScrollText className="h-4 w-4" />, desc: "Vertical, horizontal, icon timelines" },
      { label: "Toggle Group", href: "/toggle-group", icon: <ToggleRight className="h-4 w-4" />, desc: "Grouped toggles" },
      { label: "Toggle", href: "/toggle", icon: <ToggleLeft className="h-4 w-4" />, desc: "Toggle switches" },
      { label: "Tooltip", href: "/tooltip", icon: <CircleAlert className="h-4 w-4" />, desc: "Hover tooltips" },
      { label: "Tree", href: "/tree", icon: <Folder className="h-4 w-4" />, desc: "Tree view with expand/collapse" },
      { label: "Typography", href: "/typography", icon: <Type className="h-4 w-4" />, desc: "Text styling components" },
      { label: "Variant Matrix", href: "/variant-matrix", icon: <Grid3x3 className="h-4 w-4" />, desc: "Component variant comparison matrix" },
    ],
  },
  {
    title: "Navigation",
    icon: <Globe className="h-4 w-4" />,
    description: "Site navigation patterns",
    links: [
      { label: "Navigation", href: "/navigation", icon: <Globe className="h-4 w-4" />, desc: "Sidebars, top bars, breadcrumbs" },
      { label: "Layouts", href: "/layouts", icon: <Layout className="h-4 w-4" />, desc: "Page layout patterns and app shells" },
      { label: "Navbar", href: "/navbar", icon: <PanelTop className="h-4 w-4" />, desc: "Fixed, transparent, sticky navbars" },
      { label: "Header", href: "/header", icon: <PanelTop className="h-4 w-4" />, desc: "Brand, nav, search, CTA headers" },
      { label: "Sidebar", href: "/sidebar", icon: <PanelLeft className="h-4 w-4" />, desc: "Collapsible, nested, icon sidebar" },
      { label: "Footer", href: "/footer", icon: <PanelTop className="h-4 w-4" />, desc: "Multi-column, simple, social footers" },
      { label: "Search", href: "/search", icon: <Search className="h-4 w-4" />, desc: "Search bars, command palette" },
    ],
  },
  {
    title: "Overlays",
    icon: <Circle className="h-4 w-4" />,
    description: "Modals, dialogs, and floating UI",
    links: [
      { label: "Modal", href: "/modal", icon: <Square className="h-4 w-4" />, desc: "Centered, side, full-screen modals" },
      { label: "Dialog", href: "/dialog", icon: <MessageSquare className="h-4 w-4" />, desc: "Confirm, alert, form dialogs" },
      { label: "Popover", href: "/popover", icon: <CircleAlert className="h-4 w-4" />, desc: "Click, hover popovers" },
      { label: "Toast", href: "/toast", icon: <Bell className="h-4 w-4" />, desc: "Success, error, info notifications" },
      { label: "Dropdown", href: "/dropdown", icon: <ChevronDown className="h-4 w-4" />, desc: "Menu dropdowns, select dropdowns" },
      { label: "Accordion", href: "/accordion", icon: <ChevronsRight className="h-4 w-4" />, desc: "Single, multiple, icon accordions" },
      { label: "Carousel", href: "/carousel", icon: <ChevronsRight className="h-4 w-4" />, desc: "Image, card, testimonial carousels" },
    ],
  },
  {
    title: "Menus",
    icon: <Command className="h-4 w-4" />,
    description: "Command and context menus",
    links: [
      { label: "Command Menu", href: "/command-menu", icon: <Command className="h-4 w-4" />, desc: "Cmd+K palette, grouped actions" },
      { label: "Context Menu", href: "/context-menu", icon: <ChevronDown className="h-4 w-4" />, desc: "Right-click menus, nested" },
    ],
  },
  {
    title: "Feedback",
    icon: <AlertTriangle className="h-4 w-4" />,
    description: "Loading, empty, and error states",
    links: [
      { label: "Loading", href: "/loading", icon: <Loader className="h-4 w-4" />, desc: "Spinners, bars, page loaders" },
      { label: "Skeleton", href: "/skeleton", icon: <Square className="h-4 w-4" />, desc: "Text, card, table skeletons" },
      { label: "Empty State", href: "/empty-state", icon: <Square className="h-4 w-4" />, desc: "Empty inbox, search, data states" },
      { label: "Error", href: "/error", icon: <AlertCircle className="h-4 w-4" />, desc: "Error boundaries, error messages" },
      { label: "404", href: "/404", icon: <HelpCircle className="h-4 w-4" />, desc: "Creative not-found pages" },
    ],
  },
  {
    title: "Pages",
    icon: <FileText className="h-4 w-4" />,
    description: "Full page layouts and sections",
    links: [
      { label: "Landing", href: "/landing", icon: <LayoutDashboard className="h-4 w-4" />, desc: "Marketing landing page" },
      { label: "Dashboard", href: "/dashboard", icon: <LayoutDashboard className="h-4 w-4" />, desc: "Admin dashboard layout" },
      { label: "Hero", href: "/hero", icon: <Star className="h-4 w-4" />, desc: "Hero section variations" },
      { label: "Pricing", href: "/pricing", icon: <DollarSign className="h-4 w-4" />, desc: "Pricing tables and plans" },
      { label: "Testimonials", href: "/testimonials", icon: <Quote className="h-4 w-4" />, desc: "Customer testimonials" },
      { label: "FAQ", href: "/faq", icon: <HelpCircle className="h-4 w-4" />, desc: "Frequently asked questions" },
      { label: "Authentication", href: "/authentication", icon: <Lock className="h-4 w-4" />, desc: "Login, signup, password reset" },
    ],
  },
  {
    title: "Data & Media",
    icon: <BarChart3 className="h-4 w-4" />,
    description: "Data visualization and media",
    links: [
      { label: "Charts", href: "/charts", icon: <BarChart3 className="h-4 w-4" />, desc: "Bar, line, pie, area charts" },
      { label: "Calendar", href: "/calendar", icon: <Calendar className="h-4 w-4" />, desc: "Date picker, events, mini calendar" },
    ],
  },
  {
    title: "Tools",
    icon: <Cog className="h-4 w-4" />,
    description: "Visual editors and generators",
    links: [
      { label: "AI Generator", href: "/ai-generator", icon: <Sparkles className="h-4 w-4" />, desc: "AI-powered component generation" },
      { label: "API Explorer", href: "/api-explorer", icon: <SearchCode className="h-4 w-4" />, desc: "Interactive API documentation explorer" },
      { label: "Code Playground", href: "/code-playground", icon: <Play className="h-4 w-4" />, desc: "Live code playground with preview" },
      { label: "Command Palette", href: "/command-palette", icon: <Command className="h-4 w-4" />, desc: "Command palette with search" },
      { label: "Playground", href: "/playground", icon: <Play className="h-4 w-4" />, desc: "Live code playground with preview" },
      { label: "Props Editor", href: "/props-editor", icon: <Settings className="h-4 w-4" />, desc: "Visual component props editor" },
      { label: "Prompt Builder", href: "/prompt-builder", icon: <MessageSquareCode className="h-4 w-4" />, desc: "AI prompt builder interface" },
    ],
  },
  {
    title: "Templates",
    icon: <Sparkles className="h-4 w-4" />,
    description: "Full application templates",
    links: [
      { label: "Blog", href: "/blog", icon: <FileText className="h-4 w-4" />, desc: "Blog layout with posts" },
      { label: "E-commerce", href: "/e-commerce", icon: <ShoppingBag className="h-4 w-4" />, desc: "Product listing and cart" },
      { label: "Chat", href: "/chat", icon: <MessageCircleMore className="h-4 w-4" />, desc: "Messaging interface" },
      { label: "AI", href: "/ai", icon: <Bot className="h-4 w-4" />, desc: "AI chat and generation" },
      { label: "Portfolio", href: "/portfolio", icon: <Briefcase className="h-4 w-4" />, desc: "Portfolio showcase" },
      { label: "Analytics", href: "/analytics", icon: <BarChart3 className="h-4 w-4" />, desc: "Analytics dashboard" },
      { label: "SaaS", href: "/saas", icon: <Cloud className="h-4 w-4" />, desc: "Software as a Service landing page" },
      { label: "Project Mgmt", href: "/project-management", icon: <BriefcaseBusiness className="h-4 w-4" />, desc: "Kanban, tasks, project tracking" },
      { label: "Social Media", href: "/social-media", icon: <Users className="h-4 w-4" />, desc: "Feed, stories, profiles" },
      { label: "CRM", href: "/crm", icon: <Contact className="h-4 w-4" />, desc: "Contact management, deals, pipeline" },
      { label: "LMS", href: "/lms", icon: <GraduationCap className="h-4 w-4" />, desc: "Course platform, lessons, quizzes" },
      { label: "Job Board", href: "/job-board", icon: <BriefcaseBusiness className="h-4 w-4" />, desc: "Job listings, search, applications" },
      { label: "Restaurant", href: "/restaurant", icon: <UtensilsCrossed className="h-4 w-4" />, desc: "Menu, ordering, reservations" },
      { label: "Real Estate", href: "/real-estate", icon: <Building2 className="h-4 w-4" />, desc: "Property listings, mortgage calc" },
    ],
  },
];

/** Total number of links across the whole tree. */
export const navigationLinkCount = navigationSections.reduce(
  (total, section) => total + section.links.length,
  0
);
