import type { NavSection } from "@/types/navigation";


export const navigationSections: NavSection[] = [
  {
    title: "Get Started",
    icon: "★",
    description: "Core concepts and fundamentals",
    links: [
      { label: "Home", href: "/", icon: "⌂" },
      { label: "Routing", href: "/routing", icon: "↗", desc: "File-based routing, dynamic routes, layouts, navigation" },
      { label: "Data Fetching", href: "/data-fetching", icon: "⇄", desc: "Server-side data loading, caching, streaming" },
      { label: "Styling", href: "/styling", icon: "✦", desc: "Tailwind CSS, themes, responsive design" },
    ],
  },
  {
    title: "Registry",
    icon: "⌕",
    description: "Component registry platform",
    links: [
      { label: "Components", href: "/components", icon: "▣", desc: "Browse the component registry" },
    ],
  },
  {
    title: "Components",
    icon: "▣",
    description: "Reusable UI primitives",
    links: [
      { label: "Accordion Menu", href: "/accordion-menu", icon: "║", desc: "Multi-level accordion navigation menu" },
      { label: "Accordion", href: "/accordion", icon: "║", desc: "Single, multiple, icon accordions" },
      { label: "Activity Feed", href: "/activity-feed", icon: "≡", desc: "Real-time activity and notification feed" },
      { label: "Alert Dialog", href: "/alert-dialog", icon: "⚠", desc: "Modal alert dialogs with confirm/cancel" },
      { label: "Alert", href: "/alert", icon: "⚠", desc: "Alert messages, banners, notifications" },
      { label: "Animated Counter", href: "/animated-counter", icon: "@dynamic", desc: "Animated number counter with easing" },
      { label: "Aspect Ratio", href: "/aspect-ratio", icon: "▭", desc: "Maintain consistent aspect ratios" },
      { label: "Attachment", href: "/attachment", icon: "📎", desc: "File attachments with preview and actions" },
      { label: "Audio Player", href: "/audio-player", icon: "♫", desc: "Audio player with waveform visualization" },
      { label: "Avatar", href: "/avatar", icon: "◉", desc: "User avatars, groups, status rings" },
      { label: "Background Patterns", href: "/background-patterns", icon: "⬡", desc: "SVG background pattern generators" },
      { label: "Badge", href: "/badge", icon: "⬡", desc: "Colored badges, dots, status indicators" },
      { label: "Barcode Scanner", href: "/barcode-scanner", icon: "⊞", desc: "Barcode and QR code scanner" },
      { label: "Bento Grid", href: "/bento-grid", icon: "⊞", desc: "Masonry-style bento layout grid" },
      { label: "Booking Calendar", href: "/booking-calendar", icon: "📅", desc: "Appointment and booking calendar" },
      { label: "Breadcrumb", href: "/breadcrumb", icon: "›", desc: "Navigation breadcrumbs" },
      { label: "Bubble", href: "/bubble", icon: "💬", desc: "Chat bubbles and message variants" },
      { label: "Button Group", href: "/button-group", icon: "▦", desc: "Grouped buttons with shared state" },
      { label: "Button Spotlight", href: "/button-spotlight", icon: "✦", desc: "Spotlight hover effect buttons" },
      { label: "Buttons", href: "/buttons", icon: "▦", desc: "Variants, sizes, icons, loading states" },
      { label: "Camera Capture", href: "/camera-capture", icon: "◎", desc: "Webcam photo and video capture" },
      { label: "Cards", href: "/cards", icon: "⊞", desc: "Cards, tiles, media cards, interactive" },
      { label: "Checkbox", href: "/checkbox", icon: "☑", desc: "Checkboxes with labels and states" },
      { label: "Chip", href: "/chip", icon: "⬡", desc: "Compact chip and tag elements" },
      { label: "Collapsible", href: "/collapsible", icon: "▸", desc: "Expandable and collapsible content" },
      { label: "Color Picker", href: "/color-picker", icon: "◐", desc: "HSL/RGB color picker with swatches" },
      { label: "Combobox", href: "/combobox", icon: "▾", desc: "Searchable dropdown selects" },
      { label: "Command", href: "/command", icon: "⌘", desc: "Command palette with search" },
      { label: "Countdown", href: "/countdown", icon: "⏱", desc: "Countdown timer with days/hours/minutes/seconds" },
      { label: "Currency Input", href: "/currency-input", icon: "$", desc: "Formatted currency input with locale support" },
      { label: "Data Table", href: "/data-table", icon: "⊟", desc: "Data tables with sorting and filtering" },
      { label: "Date Picker", href: "/date-picker", icon: "📅", desc: "Calendar date selection" },
      { label: "Dependency Graph", href: "/dependency-graph", icon: "⌕", desc: "Interactive SVG dependency graph with layered layout" },
      { label: "Direction", href: "/direction", icon: "↻", desc: "RTL/LTR direction provider" },
      { label: "Dock", href: "/dock", icon: "⊞", desc: "macOS-style magnifying dock launcher" },
      { label: "Drag Drop Zone", href: "/drag-drop-zone", icon: "↗", desc: "Drag-and-drop file upload zone" },
      { label: "Drawer", href: "/drawer", icon: "▨", desc: "Slide-in drawer panels" },
      { label: "Dropdown Menu", href: "/dropdown-menu", icon: "▾", desc: "Dropdown menus with items" },
      { label: "Field", href: "/field", icon: "▭", desc: "Form field wrapper with label" },
      { label: "File Tree", href: "/file-tree", icon: "≡", desc: "Expandable file/folder tree view" },
      { label: "File Upload", href: "/file-upload", icon: "📎", desc: "File upload with drag-and-drop preview" },
      { label: "Floating Toolbar", href: "/floating-toolbar", icon: "⊞", desc: "Floating context-aware toolbar" },
      { label: "Forms", href: "/forms", icon: "☰", desc: "Form layouts, validation, multi-step" },
      { label: "Gallery", href: "/gallery", icon: "▣", desc: "Image gallery with lightbox" },
      { label: "Gesture Area", href: "/gesture-area", icon: "↻", desc: "Touch gesture detection area" },
      { label: "Grid", href: "/grid", icon: "⊞", desc: "Responsive CSS grid layouts" },
      { label: "Heat Map", href: "/heat-map", icon: "▇", desc: "Data heat map visualization" },
      { label: "Hover Card", href: "/hover-card", icon: "◻", desc: "Hover-triggered preview cards" },
      { label: "Icon Picker", href: "/icon-picker", icon: "✦", desc: "Searchable icon picker grid" },
      { label: "Image Comparison", href: "/image-comparison", icon: "⇔", desc: "Before/after image comparison slider" },
      { label: "Image", href: "/image", icon: "▣", desc: "Responsive image with lazy loading" },
      { label: "Infinite Scroll", href: "/infinite-scroll", icon: "↕", desc: "Infinite scrolling list loader" },
      { label: "Input Group", href: "/input-group", icon: "⌨", desc: "Grouped inputs with addons" },
      { label: "Input OTP", href: "/input-otp", icon: "•••", desc: "One-time password input" },
      { label: "Inputs", href: "/inputs", icon: "⌨", desc: "Text inputs, selects, checkboxes, switches" },
      { label: "Item", href: "/item", icon: "▪", desc: "List item component" },
      { label: "JSON Tree Viewer", href: "/json-tree-viewer", icon: "≡", desc: "Expandable JSON tree viewer" },
      { label: "Kbd", href: "/kbd", icon: "⌨", desc: "Keyboard shortcut indicators" },
      { label: "Keyboard Shortcuts", href: "/keyboard-shortcuts", icon: "⌨", desc: "Keyboard shortcut reference modal" },
      { label: "Label", href: "/label", icon: "Aa", desc: "Form labels" },
      { label: "List", href: "/list", icon: "≡", desc: "Virtualized list component" },
      { label: "Lottie Player", href: "/lottie-player", icon: "▶", desc: "Lottie animation player" },
      { label: "Markdown Editor", href: "/markdown-editor", icon: "☰", desc: "Rich markdown editor with preview" },
      { label: "Marker", href: "/marker", icon: "◉", desc: "Highlight marker component" },
      { label: "Masonry", href: "/masonry", icon: "⊞", desc: "Masonry grid layout" },
      { label: "Menubar", href: "/menubar", icon: "☰", desc: "Horizontal menu bars" },
      { label: "Message Scroller", href: "/message-scroller", icon: "↕", desc: "Auto-scrolling message list" },
      { label: "Message", href: "/message", icon: "💬", desc: "Message display component" },
      { label: "Multi Select", href: "/multi-select", icon: "☑", desc: "Multi-select dropdown with tags" },
      { label: "Native Select", href: "/native-select", icon: "▾", desc: "Native HTML select elements" },
      { label: "Navigation Menu", href: "/navigation-menu", icon: "♢", desc: "Navigation menu component" },
      { label: "Notification", href: "/notification", icon: "◊", desc: "Notification bell with badge count" },
      { label: "Number Input", href: "/number-input", icon: "@dynamic", desc: "Numeric input with stepper controls" },
      { label: "Pagination", href: "/pagination", icon: "‹›", desc: "Page numbers, prev/next, compact" },
      { label: "Password Strength", href: "/password-strength", icon: "🔒", desc: "Password strength meter indicator" },
      { label: "Pin Input", href: "/pin-input", icon: "•••", desc: "PIN/OTP digit input" },
      { label: "Progress", href: "/progress", icon: "▰", desc: "Progress bars and indicators" },
      { label: "Progress Bar", href: "/progress-bar", icon: "▰", desc: "Animated progress bar variants" },
      { label: "QR Code", href: "/qr-code", icon: "⊞", desc: "QR code generator" },
      { label: "Radio Group", href: "/radio-group", icon: "◉", desc: "Radio button groups" },
      { label: "Range Calendar", href: "/range-calendar", icon: "📅", desc: "Date range calendar picker" },
      { label: "Rating Stars", href: "/rating-stars", icon: "★", desc: "Star rating with half-star support" },
      { label: "Resizable", href: "/resizable", icon: "⇔", desc: "Resizable panels" },
      { label: "Rich Text Editor", href: "/rich-text-editor", icon: "☰", desc: "WYSIWYG rich text editor" },
      { label: "Scroll Area", href: "/scroll-area", icon: "↕", desc: "Custom scroll containers" },
      { label: "Search Input", href: "/search-input", icon: "⌕", desc: "Search input with debounced results" },
      { label: "Select", href: "/select", icon: "▾", desc: "Custom select dropdowns" },
      { label: "Separator", href: "/separator", icon: "—", desc: "Visual dividers" },
      { label: "Sheet", href: "/sheet", icon: "▧", desc: "Slide-out sheet panels" },
      { label: "Slider", href: "/slider", icon: "●—", desc: "Range sliders" },
      { label: "Spinner", href: "/spinner", icon: "◎", desc: "Loading spinners" },
      { label: "Spotlight Search", href: "/spotlight-search", icon: "⊕", desc: "Cmd+K spotlight search overlay" },
      { label: "Stepper", href: "/stepper", icon: "▸", desc: "Step-by-step wizard stepper" },
      { label: "Steps", href: "/steps", icon: "▸▸", desc: "Progress step indicators" },
      { label: "Streaming Response", href: "/streaming-response", icon: "↗", desc: "AI streaming response display" },
      { label: "Switch", href: "/switch", icon: "◐", desc: "Toggle switch component" },
      { label: "Table", href: "/table", icon: "⊟", desc: "Data tables, sorting, filtering, sticky" },
      { label: "Tabs", href: "/tabs", icon: "▭", desc: "Tabbed interfaces" },
      { label: "Tags", href: "/tags", icon: "⬡", desc: "Tag input with autocomplete" },
      { label: "Terminal Emulator", href: "/terminal-emulator", icon: "▸", desc: "In-browser terminal with custom commands" },
      { label: "Textarea", href: "/textarea", icon: "▭", desc: "Multi-line text inputs" },
      { label: "Timeline", href: "/timeline", icon: "≡", desc: "Vertical, horizontal, icon timelines" },
      { label: "Toggle Group", href: "/toggle-group", icon: "◑", desc: "Grouped toggles" },
      { label: "Toggle", href: "/toggle", icon: "◐", desc: "Toggle switches" },
      { label: "Tooltip", href: "/tooltip", icon: "◈", desc: "Hover tooltips" },
      { label: "Tree", href: "/tree", icon: "≡", desc: "Tree view with expand/collapse" },
      { label: "Typography", href: "/typography", icon: "Aa", desc: "Text styling components" },
      { label: "Variant Matrix", href: "/variant-matrix", icon: "⊞", desc: "Component variant comparison matrix" },
    ],
  },
  {
    title: "Navigation",
    icon: "➤",
    description: "Site navigation patterns",
    links: [
      { label: "Navigation", href: "/navigation", icon: "♢", desc: "Sidebars, top bars, breadcrumbs" },
      { label: "Layouts", href: "/layouts", icon: "▣", desc: "Page layout patterns and app shells" },
      { label: "Navbar", href: "/navbar", icon: "⊡", desc: "Fixed, transparent, sticky navbars" },
      { label: "Header", href: "/header", icon: "⊓", desc: "Brand, nav, search, CTA headers" },
      { label: "Sidebar", href: "/sidebar", icon: "▤", desc: "Collapsible, nested, icon sidebar" },
      { label: "Footer", href: "/footer", icon: "⊥", desc: "Multi-column, simple, social footers" },
      { label: "Search", href: "/search", icon: "⌕", desc: "Search bars, command palette" },
    ],
  },
  {
    title: "Overlays",
    icon: "⊕",
    description: "Modals, dialogs, and floating UI",
    links: [
      { label: "Modal", href: "/modal", icon: "⎔", desc: "Centered, side, full-screen modals" },
      { label: "Dialog", href: "/dialog", icon: "◻", desc: "Confirm, alert, form dialogs" },
      { label: "Popover", href: "/popover", icon: "◬", desc: "Click, hover popovers" },
      { label: "Toast", href: "/toast", icon: "◊", desc: "Success, error, info notifications" },
      { label: "Dropdown", href: "/dropdown", icon: "▾", desc: "Menu dropdowns, select dropdowns" },
      { label: "Accordion", href: "/accordion", icon: "║", desc: "Single, multiple, icon accordions" },
      { label: "Carousel", href: "/carousel", icon: "▸▸", desc: "Image, card, testimonial carousels" },
    ],
  },
  {
    title: "Menus",
    icon: "☰",
    description: "Command and context menus",
    links: [
      { label: "Command Menu", href: "/command-menu", icon: "⌘", desc: "Cmd+K palette, grouped actions" },
      { label: "Context Menu", href: "/context-menu", icon: "↘", desc: "Right-click menus, nested" },
    ],
  },
  {
    title: "Feedback",
    icon: "⚠",
    description: "Loading, empty, and error states",
    links: [
      { label: "Loading", href: "/loading", icon: "◎", desc: "Spinners, bars, page loaders" },
      { label: "Skeleton", href: "/skeleton", icon: "▯", desc: "Text, card, table skeletons" },
      { label: "Empty State", href: "/empty-state", icon: "□", desc: "Empty inbox, search, data states" },
      { label: "Error", href: "/error", icon: "✖", desc: "Error boundaries, error messages" },
      { label: "404", href: "/404", icon: "?", desc: "Creative not-found pages" },
    ],
  },
  {
    title: "Pages",
    icon: "📄",
    description: "Full page layouts and sections",
    links: [
      { label: "Landing", href: "/landing", icon: "▣", desc: "Marketing landing page" },
      { label: "Dashboard", href: "/dashboard", icon: "▦", desc: "Admin dashboard layout" },
      { label: "Hero", href: "/hero", icon: "⊡", desc: "Hero section variations" },
      { label: "Pricing", href: "/pricing", icon: "$", desc: "Pricing tables and plans" },
      { label: "Testimonials", href: "/testimonials", icon: "❝", desc: "Customer testimonials" },
      { label: "FAQ", href: "/faq", icon: "?", desc: "Frequently asked questions" },
      { label: "Authentication", href: "/authentication", icon: "🔒", desc: "Login, signup, password reset" },
    ],
  },
  {
    title: "Data & Media",
    icon: "📊",
    description: "Data visualization and media",
    links: [
      { label: "Charts", href: "/charts", icon: "▇", desc: "Bar, line, pie, area charts" },
      { label: "Calendar", href: "/calendar", icon: "📅", desc: "Date picker, events, mini calendar" },
    ],
  },
  {
    title: "Tools",
    icon: "⚙",
    description: "Visual editors and generators",
    links: [
      { label: "AI Generator", href: "/ai-generator", icon: "✦", desc: "AI-powered component generation" },
      { label: "API Explorer", href: "/api-explorer", icon: "⇄", desc: "Interactive API documentation explorer" },
      { label: "Code Playground", href: "/code-playground", icon: "▶", desc: "Live code playground with preview" },
      { label: "Command Palette", href: "/command-palette", icon: "⌘", desc: "Command palette with search" },
      { label: "Playground", href: "/playground", icon: "▶", desc: "Live code playground with preview" },
      { label: "Props Editor", href: "/props-editor", icon: "⊞", desc: "Visual component props editor" },
      { label: "Prompt Builder", href: "/prompt-builder", icon: "✦", desc: "AI prompt builder interface" },
    ],
  },
  {
    title: "Templates",
    icon: "✦",
    description: "Full application templates",
    links: [
      { label: "Blog", href: "/blog", icon: "📝", desc: "Blog layout with posts" },
      { label: "E-commerce", href: "/e-commerce", icon: "🛒", desc: "Product listing and cart" },
      { label: "Chat", href: "/chat", icon: "💬", desc: "Messaging interface" },
      { label: "AI", href: "/ai", icon: "✦", desc: "AI chat and generation" },
      { label: "Portfolio", href: "/portfolio", icon: "◆", desc: "Portfolio showcase" },
      { label: "Analytics", href: "/analytics", icon: "📈", desc: "Analytics dashboard" },
      { label: "SaaS", href: "/saas", icon: "☁", desc: "Software as a Service landing page" },
      { label: "Project Mgmt", href: "/project-management", icon: "▦", desc: "Kanban, tasks, project tracking" },
      { label: "Social Media", href: "/social-media", icon: "◎", desc: "Feed, stories, profiles" },
      { label: "CRM", href: "/crm", icon: "◉", desc: "Contact management, deals, pipeline" },
      { label: "LMS", href: "/lms", icon: "▣", desc: "Course platform, lessons, quizzes" },
      { label: "Job Board", href: "/job-board", icon: "⌕", desc: "Job listings, search, applications" },
      { label: "Restaurant", href: "/restaurant", icon: "⊡", desc: "Menu, ordering, reservations" },
      { label: "Real Estate", href: "/real-estate", icon: "▤", desc: "Property listings, mortgage calc" },
    ],
  },
];

/** Total number of links across the whole tree. */
export const navigationLinkCount = navigationSections.reduce(
  (total, section) => total + section.links.length,
  0
);
