import { NavSection } from "@/types/navigation";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignLeft,
  Anchor,
  Aperture,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpDown,
  Award,
  Battery,
  Bell,
  Bluetooth,
  Bold,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  BarChart3,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  CardSim,
  Cast,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsRight,
  Circle,
  CircleAlert,
  CircleDot,
  Clock,
  Cloud,
  Code,
  Cog,
  Columns,
  Command,
  Compass,
  Component,
  Contact,
  Copy,
  CreditCard,
  Crop,
  Crosshair,
  Crown,
  CupSoda,
  Disc,
  Dna,
  DollarSign,
  Download,
  Droplet,
  Dumbbell,
  
  Egg,
  Eye,
  Fence,
  FerrisWheel,
  FileCode,
  FileText,
  Film,
  Fingerprint,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  Footprints,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  Globe,
  GraduationCap,
  Grid3x3,
  Grip,
  Hand,
  Hammer,
  HardHat,
  Hash,
  Headphones,
  Heart,
  Heater,
  Hexagon,
  HelpCircle,
  Highlighter,
  Home,
  IceCreamBowl,
  Image,
  Inbox,
  IndianRupee,
  Infinity,
  Italic,
  Key,
  Keyboard,
  Laptop,
  Layers,
  Layout,
  LayoutDashboard,
  Leaf,
  LetterText,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link,
  Link2,
  List,
  ListTree,
  Loader,
  Locate,
  Lock,
  Magnet,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageCircleMore,
  MessageSquare,
  MessageSquareCode,
  Mic,
  Minus,
  Monitor,
  Moon,
  Mountain,
  MousePointer,
  Move,
  Move3d,
  Music,
  Navigation,
  Notebook,
  Nut,
  Package,
  Paintbrush,
  Palette,
  PanelBottom,
  PanelLeft,
  PanelTop,
  Paperclip,
  Pencil,
  PenLine,
  PenTool,
  Pentagon,
  PieChart,
  Pin,
  Pipette,
  Plane,
  Plug,
  Play,
  Podcast,
  Pointer,
  Power,
  Printer,
  QrCode,
  Quote,
  Radar,
  Radio,
  RectangleHorizontal,
  Refrigerator,
  Regex,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Router,
  Rows3,
  Rss,
  Ruler,
  Satellite,
  Scale,
  Scan,
  ScanLine,
  ScrollText,
  Scissors,
  Search,
  SearchCode,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  ShowerHead,
  Shrub,
  Sigma,
  Skull,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  SortAsc,
  SortDesc,
  Soup,
  Sparkles,
  Speaker,
  SprayCan,
  SplitSquareHorizontal,
  Square,
  SquareStack,
  Stamp,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  StretchHorizontal,
  Subtitles,
  Sun,
  Sunrise,
  Sunset,
  Swords,
  Syringe,
  Tablet,
  Table,
  Tag,
  Target,
  Telescope, 
  Terminal,
  Tent,
  Thermometer,
  Ticket,
  Timer,
  ToggleLeft,
  ToggleRight,
  Train,
  Trash,
  TreeDeciduous,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Type,
  Umbrella,
  Underline,
  Undo,
  Unplug,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  UsersRound,
  UtensilsCrossed,
  Vegan,
  VenetianMask,
  Video,
  View,
  Voicemail,
  Volume2,
  Volleyball,
  Wallet,
  Watch,
  Waves,
  Webcam,
  Wifi,
  Wheat,
  WholeWord,
  Wind,
  Wine,
  Workflow,
  WrapText,
  Wrench,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

export const navigationSections: NavSection[] = [
  {
    title: "Get Started",
    icon: <Star className="h-4 w-4" />,
    description: "Core concepts and fundamentals",
    links: [
      { label: "Home", href: "/", icon: <Home className="h-4 w-4" /> },
    ],
  },
  {
    title: "Registry",
    icon: <Search className="h-4 w-4" />,
    description: "Component registry platform",
    links: [
      { label: "Components", href: "/components", icon: <Box className="h-4 w-4" />, desc: "Browse the component registry" },
    ],
  },
  {
    title: "Components",
    icon: <Layers className="h-4 w-4" />,
    description: "Reusable UI primitives",
    links: [
      { label: "Accordion", href: "/accordion", icon: <ChevronsRight className="h-4 w-4" />, desc: "Single, multiple, icon accordions" },
      { label: "Activity Feed", href: "/activity-feed", icon: <ScrollText className="h-4 w-4" />, desc: "Real-time activity and notification feed" },
      { label: "Alert Dialog", href: "/alert-dialog", icon: <AlertTriangle className="h-4 w-4" />, desc: "Modal alert dialogs with confirm/cancel" },
      { label: "Alert", href: "/alert", icon: <AlertCircle className="h-4 w-4" />, desc: "Alert messages, banners, notifications" },
      { label: "Animated Counter", href: "/animated-counter", icon: <Hash className="h-4 w-4" />, desc: "Animated number counter with easing" },
      { label: "Aspect Ratio", href: "/aspect-ratio", icon: <Ruler className="h-4 w-4" />, desc: "Maintain consistent aspect ratios" },
      { label: "Attachment", href: "/attachment", icon: <Paperclip className="h-4 w-4" />, desc: "File attachments with preview and actions" },
      { label: "Audio Player", href: "/audio-player", icon: <Music className="h-4 w-4" />, desc: "Audio player with waveform visualization" },
      { label: "Avatar", href: "/avatar", icon: <User className="h-4 w-4" />, desc: "User avatars, groups, status rings" },
      { label: "Background Patterns", href: "/background-patterns", icon: <Hexagon className="h-4 w-4" />, desc: "SVG background pattern generators" },
      { label: "Badge", href: "/badge", icon: <Tag className="h-4 w-4" />, desc: "Colored badges, dots, status indicators" },
      { label: "Barcode Scanner", href: "/barcode-scanner", icon: <ScanLine className="h-4 w-4" />, desc: "Barcode and QR code scanner" },
      { label: "Bento Grid", href: "/bento-grid", icon: <Grid3x3 className="h-4 w-4" />, desc: "Masonry-style bento layout grid" },
      { label: "Booking Calendar", href: "/booking-calendar", icon: <Calendar className="h-4 w-4" />, desc: "Appointment and booking calendar" },
      { label: "Breadcrumb", href: "/breadcrumb", icon: <ChevronRight className="h-4 w-4" />, desc: "Navigation breadcrumbs" },
      { label: "Bubble", href: "/bubble", icon: <MessageSquare className="h-4 w-4" />, desc: "Chat bubbles and message variants" },
      { label: "Button Group", href: "/button-group", icon: <SquareStack className="h-4 w-4" />, desc: "Grouped buttons with shared state" },
      { label: "Button Spotlight", href: "/button-spotlight", icon: <Sparkles className="h-4 w-4" />, desc: "Spotlight hover effect buttons" },
      { label: "Buttons", href: "/buttons", icon: <Square className="h-4 w-4" />, desc: "Variants, sizes, icons, loading states" },
      { label: "Camera Capture", href: "/camera-capture", icon: <Camera className="h-4 w-4" />, desc: "Webcam photo and video capture" },
      { label: "Cards", href: "/cards", icon: <CardSim className="h-4 w-4" />, desc: "Cards, tiles, media cards, interactive" },
      { label: "Checkbox", href: "/checkbox", icon: <Check className="h-4 w-4" />, desc: "Checkboxes with labels and states" },
      { label: "Chip", href: "/chip", icon: <Tag className="h-4 w-4" />, desc: "Compact chip and tag elements" },

      { label: "Color Picker", href: "/color-picker", icon: <Circle className="h-4 w-4" />, desc: "HSL/RGB color picker with swatches" },
      { label: "Combobox", href: "/combobox", icon: <ChevronDown className="h-4 w-4" />, desc: "Searchable dropdown selects" },
      { label: "Command", href: "/command", icon: <Command className="h-4 w-4" />, desc: "Command palette with search" },
      { label: "Countdown", href: "/countdown", icon: <Timer className="h-4 w-4" />, desc: "Countdown timer with days/hours/minutes/seconds" },
      { label: "Currency Input", href: "/currency-input", icon: <DollarSign className="h-4 w-4" />, desc: "Formatted currency input with locale support" },
      { label: "Data Table", href: "/data-table", icon: <Table className="h-4 w-4" />, desc: "Data tables with sorting and filtering" },
      { label: "Date Picker", href: "/date-picker", icon: <CalendarDays className="h-4 w-4" />, desc: "Calendar date selection" },
      { label: "Dependency Graph", href: "/dependency-graph", icon: <Workflow className="h-4 w-4" />, desc: "Interactive SVG dependency graph with layered layout" },
      { label: "Direction", href: "/direction", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "RTL/LTR direction provider" },
      { label: "Dock", href: "/dock", icon: <Monitor className="h-4 w-4" />, desc: "macOS-style magnifying dock launcher" },
      { label: "Drag Drop Zone", href: "/drag-drop-zone", icon: <ArrowDownToLine className="h-4 w-4" />, desc: "Drag-and-drop file upload zone" },
      { label: "Drawer", href: "/drawer", icon: <PanelLeft className="h-4 w-4" />, desc: "Slide-in drawer panels" },
      { label: "Dropdown Menu", href: "/dropdown-menu", icon: <ChevronDown className="h-4 w-4" />, desc: "Dropdown menus with items" },
      { label: "Field", href: "/field", icon: <Ruler className="h-4 w-4" />, desc: "Form field wrapper with label" },
      { label: "File Tree", href: "/file-tree", icon: <Folder className="h-4 w-4" />, desc: "Expandable file/folder tree view" },
      { label: "File Upload", href: "/file-upload", icon: <Paperclip className="h-4 w-4" />, desc: "File upload with drag-and-drop preview" },
      { label: "Floating Toolbar", href: "/floating-toolbar", icon: <Grip className="h-4 w-4" />, desc: "Floating context-aware toolbar" },
      { label: "Forms", href: "/forms", icon: <FileText className="h-4 w-4" />, desc: "Form layouts, validation, multi-step" },
      { label: "Gallery", href: "/gallery", icon: <Image className="h-4 w-4" />, desc: "Image gallery with lightbox" },
      { label: "Gesture Area", href: "/gesture-area", icon: <Hand className="h-4 w-4" />, desc: "Touch gesture detection area" },
      { label: "Grid", href: "/grid", icon: <Grid3x3 className="h-4 w-4" />, desc: "Responsive CSS grid layouts" },
      { label: "Heat Map", href: "/heat-map", icon: <BarChart3 className="h-4 w-4" />, desc: "Data heat map visualization" },
      { label: "Hover Card", href: "/hover-card", icon: <CardSim className="h-4 w-4" />, desc: "Hover-triggered preview cards" },
      { label: "Icon Picker", href: "/icon-picker", icon: <Sparkles className="h-4 w-4" />, desc: "Searchable icon picker grid" },
      { label: "Image Comparison", href: "/image-comparison", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "Before/after image comparison slider" },
      { label: "Image", href: "/image", icon: <Image className="h-4 w-4" />, desc: "Responsive image with lazy loading" },
      { label: "Infinite Scroll", href: "/infinite-scroll", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Infinite scrolling list loader" },
      { label: "Input Group", href: "/input-group", icon: <Keyboard className="h-4 w-4" />, desc: "Grouped inputs with addons" },
      { label: "Input OTP", href: "/input-otp", icon: <Lock className="h-4 w-4" />, desc: "One-time password input" },
      { label: "Inputs", href: "/inputs", icon: <Type className="h-4 w-4" />, desc: "Text inputs, selects, checkboxes, switches" },
      { label: "Item", href: "/item", icon: <Square className="h-4 w-4" />, desc: "List item component" },
      { label: "JSON Tree Viewer", href: "/json-tree-viewer", icon: <FileCode className="h-4 w-4" />, desc: "Expandable JSON tree viewer" },
      { label: "Kbd", href: "/kbd", icon: <Keyboard className="h-4 w-4" />, desc: "Keyboard shortcut indicators" },
      { label: "Keyboard Shortcuts", href: "/keyboard-shortcuts", icon: <Keyboard className="h-4 w-4" />, desc: "Keyboard shortcut reference modal" },
      { label: "List", href: "/list", icon: <List className="h-4 w-4" />, desc: "Virtualized list component" },
      { label: "Lottie Player", href: "/lottie-player", icon: <Play className="h-4 w-4" />, desc: "Lottie animation player" },
      { label: "Markdown Editor", href: "/markdown-editor", icon: <PenTool className="h-4 w-4" />, desc: "Rich markdown editor with preview" },
      { label: "Marker", href: "/marker", icon: <Bookmark className="h-4 w-4" />, desc: "Highlight marker component" },
      { label: "Masonry", href: "/masonry", icon: <Grid3x3 className="h-4 w-4" />, desc: "Masonry grid layout" },
      { label: "Menubar", href: "/menubar", icon: <PanelTop className="h-4 w-4" />, desc: "Horizontal menu bars" },
      { label: "Message Scroller", href: "/message-scroller", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Auto-scrolling message list" },
      { label: "Message", href: "/message", icon: <MessageCircle className="h-4 w-4" />, desc: "Message display component" },
      { label: "Multi Select", href: "/multi-select", icon: <Check className="h-4 w-4" />, desc: "Multi-select dropdown with tags" },
      { label: "Native Select", href: "/native-select", icon: <ChevronDown className="h-4 w-4" />, desc: "Native HTML select elements" },
      { label: "Navigation Menu", href: "/navigation-menu", icon: <Globe className="h-4 w-4" />, desc: "Navigation menu component" },
      { label: "Notification", href: "/notification", icon: <Bell className="h-4 w-4" />, desc: "Notification bell with badge count" },
      { label: "Number Input", href: "/number-input", icon: <Hash className="h-4 w-4" />, desc: "Numeric input with stepper controls" },
      { label: "Pagination", href: "/pagination", icon: <ChevronRight className="h-4 w-4" />, desc: "Page numbers, prev/next, compact" },
      { label: "Password Strength", href: "/password-strength", icon: <Lock className="h-4 w-4" />, desc: "Password strength meter indicator" },
      { label: "Pin Input", href: "/pin-input", icon: <Lock className="h-4 w-4" />, desc: "PIN/OTP digit input" },
      { label: "Progress", href: "/progress", icon: <Loader className="h-4 w-4" />, desc: "Progress bars and indicators" },
      { label: "Progress Bar", href: "/progress-bar", icon: <Loader className="h-4 w-4" />, desc: "Animated progress bar variants" },
      { label: "QR Code", href: "/qr-code", icon: <QrCode className="h-4 w-4" />, desc: "QR code generator" },
      { label: "Radio Group", href: "/radio-group", icon: <CircleDot className="h-4 w-4" />, desc: "Radio button groups" },
      { label: "Range Calendar", href: "/range-calendar", icon: <CalendarDays className="h-4 w-4" />, desc: "Date range calendar picker" },
      { label: "Rating Stars", href: "/rating-stars", icon: <Star className="h-4 w-4" />, desc: "Star rating with half-star support" },
      { label: "Resizable", href: "/resizable", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "Resizable panels" },
      { label: "Rich Text Editor", href: "/rich-text-editor", icon: <PenTool className="h-4 w-4" />, desc: "WYSIWYG rich text editor" },
      { label: "Scroll Area", href: "/scroll-area", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Custom scroll containers" },
      { label: "Search Input", href: "/search-input", icon: <Search className="h-4 w-4" />, desc: "Search input with debounced results" },
      { label: "Select", href: "/select", icon: <ChevronDown className="h-4 w-4" />, desc: "Custom select dropdowns" },
      { label: "Separator", href: "/separator", icon: <Minus className="h-4 w-4" />, desc: "Visual dividers" },
      { label: "Sheet", href: "/sheet", icon: <PanelLeft className="h-4 w-4" />, desc: "Slide-out sheet panels" },
      { label: "Slider", href: "/slider", icon: <SlidersHorizontal className="h-4 w-4" />, desc: "Range sliders" },
      { label: "Spinner", href: "/spinner", icon: <Loader className="h-4 w-4" />, desc: "Loading spinners" },
      { label: "Spotlight Search", href: "/spotlight-search", icon: <SearchCode className="h-4 w-4" />, desc: "Cmd+K spotlight search overlay" },
      { label: "Stepper", href: "/stepper", icon: <ChevronsRight className="h-4 w-4" />, desc: "Step-by-step wizard stepper" },
      { label: "Steps", href: "/steps", icon: <ChevronsRight className="h-4 w-4" />, desc: "Progress step indicators" },
      { label: "Streaming Response", href: "/streaming-response", icon: <Sparkles className="h-4 w-4" />, desc: "AI streaming response display" },
      { label: "Switch", href: "/switch", icon: <ToggleLeft className="h-4 w-4" />, desc: "Toggle switch component" },
      { label: "Table", href: "/table", icon: <Table className="h-4 w-4" />, desc: "Data tables, sorting, filtering, sticky" },
      { label: "Tabs", href: "/tabs", icon: <PanelTop className="h-4 w-4" />, desc: "Tabbed interfaces" },
      { label: "Tags", href: "/tags", icon: <Tag className="h-4 w-4" />, desc: "Tag input with autocomplete" },
      { label: "Terminal Emulator", href: "/terminal-emulator", icon: <Terminal className="h-4 w-4" />, desc: "In-browser terminal with custom commands" },
      { label: "Textarea", href: "/textarea", icon: <Type className="h-4 w-4" />, desc: "Multi-line text inputs" },
      { label: "Timeline", href: "/timeline", icon: <ScrollText className="h-4 w-4" />, desc: "Vertical, horizontal, icon timelines" },
      { label: "Toggle Group", href: "/toggle-group", icon: <ToggleRight className="h-4 w-4" />, desc: "Grouped toggles" },
      { label: "Toggle", href: "/toggle", icon: <ToggleLeft className="h-4 w-4" />, desc: "Toggle switches" },
      { label: "Tooltip", href: "/tooltip", icon: <CircleAlert className="h-4 w-4" />, desc: "Hover tooltips" },
      { label: "Tree", href: "/tree", icon: <Folder className="h-4 w-4" />, desc: "Tree view with expand/collapse" },
      { label: "Typography", href: "/typography", icon: <Type className="h-4 w-4" />, desc: "Text styling components" },
      { label: "Chip Input", href: "/chip-input", icon: <Tag className="h-4 w-4" />, desc: "Tag/chip input with autocomplete" },
      { label: "Signature Pad", href: "/signature-pad", icon: <PenLine className="h-4 w-4" />, desc: "Signature capture canvas" },
      { label: "Dual Range Slider", href: "/dual-range-slider", icon: <SlidersHorizontal className="h-4 w-4" />, desc: "Dual-handle range slider" },
      { label: "Password Generator", href: "/password-generator", icon: <Lock className="h-4 w-4" />, desc: "Random password generator" },
      { label: "Color Swatch", href: "/color-swatch", icon: <Palette className="h-4 w-4" />, desc: "Color swatch picker grid" },
      { label: "Toggle Card", href: "/toggle-card", icon: <ToggleLeft className="h-4 w-4" />, desc: "Card-based toggle selection" },
      { label: "Phone Input", href: "/phone-input", icon: <Smartphone className="h-4 w-4" />, desc: "International phone input" },
      { label: "Time Picker", href: "/time-picker", icon: <Timer className="h-4 w-4" />, desc: "Time selection dropdown" },
      { label: "Stat Card", href: "/stat-card", icon: <TrendingUp className="h-4 w-4" />, desc: "Statistics card with trends" },
      { label: "Kanban Board", href: "/kanban-board", icon: <Columns className="h-4 w-4" />, desc: "Drag-and-drop kanban board" },
      { label: "Comparison Table", href: "/comparison-table", icon: <Table className="h-4 w-4" />, desc: "Side-by-side comparison" },
      { label: "Metric Card", href: "/metric-card", icon: <Gauge className="h-4 w-4" />, desc: "Metric display with sparkline" },
      { label: "Status Badge", href: "/status-badge", icon: <CircleDot className="h-4 w-4" />, desc: "Status indicator with dot" },
      { label: "Data Grid", href: "/data-grid", icon: <Grid3x3 className="h-4 w-4" />, desc: "Data grid with sorting" },
      { label: "List Group", href: "/list-group", icon: <List className="h-4 w-4" />, desc: "Grouped list items" },
      { label: "Description List", href: "/description-list", icon: <AlignLeft className="h-4 w-4" />, desc: "Key-value pair list" },
      { label: "Pie Chart", href: "/pie-chart", icon: <PieChart className="h-4 w-4" />, desc: "Pie and donut chart" },
      { label: "Progress Ring", href: "/progress-ring", icon: <Loader className="h-4 w-4" />, desc: "Circular progress indicator" },
      { label: "Confetti", href: "/confetti", icon: <Sparkles className="h-4 w-4" />, desc: "Celebration confetti animation" },
      { label: "Particles", href: "/particles", icon: <Zap className="h-4 w-4" />, desc: "Particle background effect" },
      { label: "Snackbar", href: "/snackbar", icon: <Bell className="h-4 w-4" />, desc: "Snackbar notification" },
      { label: "Bounce Loader", href: "/bounce-loader", icon: <Loader className="h-4 w-4" />, desc: "Bounce animation loader" },
      { label: "Pulse Ring", href: "/pulse-ring", icon: <RefreshCw className="h-4 w-4" />, desc: "Pulsing ring animation" },
      { label: "Wave Loader", href: "/wave-loader", icon: <Wifi className="h-4 w-4" />, desc: "Wave animation loader" },
      { label: "Typing Indicator", href: "/typing-indicator", icon: <MessageSquare className="h-4 w-4" />, desc: "Typing dots animation" },
      { label: "Skeleton List", href: "/skeleton-list", icon: <Square className="h-4 w-4" />, desc: "List skeleton loader" },
      { label: "Alert Banner", href: "/alert-banner", icon: <AlertTriangle className="h-4 w-4" />, desc: "Top alert banner" },
      { label: "Quick Nav", href: "/quick-nav", icon: <SearchCode className="h-4 w-4" />, desc: "Quick navigation popup" },
      { label: "Anchor Links", href: "/anchor-links", icon: <Link className="h-4 w-4" />, desc: "Anchor navigation links" },
      { label: "Scrollspy", href: "/scrollspy", icon: <Eye className="h-4 w-4" />, desc: "Scroll position indicator" },
      { label: "Back to Top", href: "/back-to-top", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Scroll to top button" },
      { label: "Tab Bar", href: "/tab-bar", icon: <PanelTop className="h-4 w-4" />, desc: "Mobile tab bar" },
      { label: "Segmented Control", href: "/segmented-control", icon: <ToggleRight className="h-4 w-4" />, desc: "Segmented button control" },
      { label: "Stepper Input", href: "/stepper-input", icon: <Hash className="h-4 w-4" />, desc: "Number stepper with +/- buttons" },
      { label: "Rating Input", href: "/rating-input", icon: <Star className="h-4 w-4" />, desc: "Star rating input" },
      { label: "Breadcrumb Bar", href: "/breadcrumb-bar", icon: <ChevronRight className="h-4 w-4" />, desc: "Breadcrumb navigation bar" },
      { label: "Pagination Bar", href: "/pagination-bar", icon: <ChevronRight className="h-4 w-4" />, desc: "Pagination navigation bar" },
      { label: "Step Progress", href: "/step-progress", icon: <ChevronsRight className="h-4 w-4" />, desc: "Step progress indicator" },
      { label: "Split View", href: "/split-view", icon: <SplitSquareHorizontal className="h-4 w-4" />, desc: "Split pane layout" },
      { label: "Aspect Container", href: "/aspect-container", icon: <Maximize2 className="h-4 w-4" />, desc: "Aspect ratio container" },
      { label: "Stack Layout", href: "/stack-layout", icon: <Rows3 className="h-4 w-4" />, desc: "Vertical/horizontal stack" },
      { label: "Center Layout", href: "/center-layout", icon: <Square className="h-4 w-4" />, desc: "Centering container" },
      { label: "Cluster Layout", href: "/cluster-layout", icon: <Grip className="h-4 w-4" />, desc: "Cluster layout" },
      { label: "Sidebar Layout", href: "/sidebar-layout", icon: <PanelLeft className="h-4 w-4" />, desc: "Sidebar content layout" },
      { label: "Holy Grail Layout", href: "/holy-grail-layout", icon: <Layout className="h-4 w-4" />, desc: "Classic holy grail layout" },
      { label: "Responsive Container", href: "/responsive-container", icon: <Smartphone className="h-4 w-4" />, desc: "Responsive container" },
      { label: "Drag Handle", href: "/drag-handle", icon: <Move className="h-4 w-4" />, desc: "Drag handle component" },
    ],
  },
  {
    title: "Navigation",
    icon: <Globe className="h-4 w-4" />,
    description: "Site navigation patterns",
    links: [
      { label: "Navigation", href: "/navigation", icon: <Globe className="h-4 w-4" />, desc: "Sidebars, top bars, breadcrumbs" },
      { label: "Layouts", href: "/layouts", icon: <Layout className="h-4 w-4" />, desc: "Page layout patterns and app shells" },
      { label: "Navbar", href: "/navbar", icon: <PanelTop className="h-4 w-4" />, desc: "Fixed, transparent, sticky navbars" },
      { label: "Header", href: "/header", icon: <PanelTop className="h-4 w-4" />, desc: "Brand, nav, search, CTA headers" },
      { label: "Sidebar", href: "/sidebar", icon: <PanelLeft className="h-4 w-4" />, desc: "Collapsible, nested, icon sidebar" },
      { label: "Footer", href: "/footer", icon: <PanelTop className="h-4 w-4" />, desc: "Multi-column, simple, social footers" },
      { label: "Search", href: "/search", icon: <Search className="h-4 w-4" />, desc: "Search bars, command palette" },
    ],
  },
  {
    title: "Overlays",
    icon: <Circle className="h-4 w-4" />,
    description: "Modals, dialogs, and floating UI",
    links: [
      { label: "Modal", href: "/modal", icon: <Square className="h-4 w-4" />, desc: "Centered, side, full-screen modals" },
      { label: "Dialog", href: "/dialog", icon: <MessageSquare className="h-4 w-4" />, desc: "Confirm, alert, form dialogs" },
      { label: "Popover", href: "/popover", icon: <CircleAlert className="h-4 w-4" />, desc: "Click, hover popovers" },
      { label: "Toast", href: "/toast", icon: <Bell className="h-4 w-4" />, desc: "Success, error, info notifications" },
      { label: "Dropdown", href: "/dropdown", icon: <ChevronDown className="h-4 w-4" />, desc: "Menu dropdowns, select dropdowns" },
      { label: "Accordion", href: "/accordion", icon: <ChevronsRight className="h-4 w-4" />, desc: "Single, multiple, icon accordions" },
      { label: "Carousel", href: "/carousel", icon: <ChevronsRight className="h-4 w-4" />, desc: "Image, card, testimonial carousels" },
    ],
  },
  {
    title: "Menus",
    icon: <Command className="h-4 w-4" />,
    description: "Command and context menus",
    links: [
      { label: "Command Menu", href: "/command-menu", icon: <Command className="h-4 w-4" />, desc: "Cmd+K palette, grouped actions" },
      { label: "Context Menu", href: "/context-menu", icon: <ChevronDown className="h-4 w-4" />, desc: "Right-click menus, nested" },
    ],
  },
  {
    title: "Feedback",
    icon: <AlertTriangle className="h-4 w-4" />,
    description: "Loading, empty, and error states",
    links: [
      { label: "Loading", href: "/loading", icon: <Loader className="h-4 w-4" />, desc: "Spinners, bars, page loaders" },
      { label: "Skeleton", href: "/skeleton", icon: <Square className="h-4 w-4" />, desc: "Text, card, table skeletons" },
      { label: "Empty State", href: "/empty-state", icon: <Square className="h-4 w-4" />, desc: "Empty inbox, search, data states" },
      { label: "Error", href: "/error", icon: <AlertCircle className="h-4 w-4" />, desc: "Error boundaries, error messages" },
      { label: "404", href: "/404", icon: <HelpCircle className="h-4 w-4" />, desc: "Creative not-found pages" },
    ],
  },
  {
    title: "Pages",
    icon: <FileText className="h-4 w-4" />,
    description: "Full page layouts and sections",
    links: [
      { label: "Landing", href: "/landing", icon: <LayoutDashboard className="h-4 w-4" />, desc: "Marketing landing page" },
      { label: "Dashboard", href: "/dashboard", icon: <LayoutDashboard className="h-4 w-4" />, desc: "Admin dashboard layout" },
      { label: "Hero", href: "/hero", icon: <Star className="h-4 w-4" />, desc: "Hero section variations" },
      { label: "Pricing", href: "/pricing", icon: <DollarSign className="h-4 w-4" />, desc: "Pricing tables and plans" },
      { label: "Testimonials", href: "/testimonials", icon: <Quote className="h-4 w-4" />, desc: "Customer testimonials" },
      { label: "FAQ", href: "/faq", icon: <HelpCircle className="h-4 w-4" />, desc: "Frequently asked questions" },
      { label: "Authentication", href: "/authentication", icon: <Lock className="h-4 w-4" />, desc: "Login, signup, password reset" },
    ],
  },
  {
    title: "Data & Media",
    icon: <BarChart3 className="h-4 w-4" />,
    description: "Data visualization and media",
    links: [
      { label: "Charts", href: "/charts", icon: <BarChart3 className="h-4 w-4" />, desc: "Bar, line, pie, area charts" },
      { label: "Calendar", href: "/calendar", icon: <Calendar className="h-4 w-4" />, desc: "Date picker, events, mini calendar" },
    ],
  },
  {
    title: "Tools",
    icon: <Cog className="h-4 w-4" />,
    description: "Visual editors and generators",
    links: [
      { label: "AI Generator", href: "/ai-generator", icon: <Sparkles className="h-4 w-4" />, desc: "AI-powered component generation" },
      { label: "API Explorer", href: "/api-explorer", icon: <SearchCode className="h-4 w-4" />, desc: "Interactive API documentation explorer" },
      { label: "Code Playground", href: "/code-playground", icon: <Play className="h-4 w-4" />, desc: "Live code playground with preview" },
      { label: "Command Palette", href: "/command-palette", icon: <Command className="h-4 w-4" />, desc: "Command palette with search" },
      { label: "Playground", href: "/playground", icon: <Play className="h-4 w-4" />, desc: "Live code playground with preview" },
      { label: "Props Editor", href: "/props-editor", icon: <Settings className="h-4 w-4" />, desc: "Visual component props editor" },
      { label: "Prompt Builder", href: "/prompt-builder", icon: <MessageSquareCode className="h-4 w-4" />, desc: "AI prompt builder interface" },
    ],
  },
  {
    title: "Templates",
    icon: <Sparkles className="h-4 w-4" />,
    description: "Full application templates",
    links: [
      { label: "Blog", href: "/blog", icon: <FileText className="h-4 w-4" />, desc: "Blog layout with posts" },
      { label: "E-commerce", href: "/e-commerce", icon: <ShoppingBag className="h-4 w-4" />, desc: "Product listing and cart" },
      { label: "Chat", href: "/chat", icon: <MessageCircleMore className="h-4 w-4" />, desc: "Messaging interface" },
      { label: "AI", href: "/ai", icon: <Bot className="h-4 w-4" />, desc: "AI chat and generation" },
      { label: "Portfolio", href: "/portfolio", icon: <Briefcase className="h-4 w-4" />, desc: "Portfolio showcase" },
      { label: "Analytics", href: "/analytics", icon: <BarChart3 className="h-4 w-4" />, desc: "Analytics dashboard" },
      { label: "SaaS", href: "/saas", icon: <Cloud className="h-4 w-4" />, desc: "Software as a Service landing page" },
      { label: "Project Mgmt", href: "/project-management", icon: <BriefcaseBusiness className="h-4 w-4" />, desc: "Kanban, tasks, project tracking" },
      { label: "Social Media", href: "/social-media", icon: <Users className="h-4 w-4" />, desc: "Feed, stories, profiles" },
      { label: "CRM", href: "/crm", icon: <Contact className="h-4 w-4" />, desc: "Contact management, deals, pipeline" },
      { label: "LMS", href: "/lms", icon: <GraduationCap className="h-4 w-4" />, desc: "Course platform, lessons, quizzes" },
      { label: "Job Board", href: "/job-board", icon: <BriefcaseBusiness className="h-4 w-4" />, desc: "Job listings, search, applications" },
      { label: "Restaurant", href: "/restaurant", icon: <UtensilsCrossed className="h-4 w-4" />, desc: "Menu, ordering, reservations" },
      { label: "Real Estate", href: "/real-estate", icon: <Building2 className="h-4 w-4" />, desc: "Property listings, mortgage calc" },
    ],
  },
  {
    title: "New Components",
    icon: <Sparkles className="h-4 w-4" />,
    description: "200 new component demos",
    links: [
      { label: "Activity Feed Card", href: "/activity-feed-card", icon: <Activity className="h-4 w-4" />, desc: "Activity feed card component" },
      { label: "Anchor Navigation", href: "/anchor-navigation", icon: <Anchor className="h-4 w-4" />, desc: "Anchor-based page navigation" },
      { label: "Aperture Picker", href: "/aperture-picker", icon: <Aperture className="h-4 w-4" />, desc: "Camera aperture selector" },
      { label: "Award Badge", href: "/award-badge", icon: <Award className="h-4 w-4" />, desc: "Award and achievement badges" },
      { label: "Battery Indicator", href: "/battery-indicator", icon: <Battery className="h-4 w-4" />, desc: "Battery level indicator" },
      { label: "Bluetooth Scanner", href: "/bluetooth-scanner", icon: <Bluetooth className="h-4 w-4" />, desc: "Bluetooth device scanner" },
      { label: "Bold Text", href: "/bold-text", icon: <Bold className="h-4 w-4" />, desc: "Bold text formatting" },
      { label: "Book Open", href: "/book-open", icon: <BookOpen className="h-4 w-4" />, desc: "Book open reader view" },
      { label: "Bookmark Ribbon", href: "/bookmark-ribbon", icon: <Bookmark className="h-4 w-4" />, desc: "Bookmark ribbon indicator" },
      { label: "Calendar Grid", href: "/calendar-grid", icon: <Calendar className="h-4 w-4" />, desc: "Calendar grid layout" },
      { label: "Cast Player", href: "/cast-player", icon: <Cast className="h-4 w-4" />, desc: "Chromecast player controls" },
      { label: "Chrome Tabs", href: "/chrome-tabs", icon: <Globe className="h-4 w-4" />, desc: "Chrome-style browser tabs" },
      { label: "Clock Widget", href: "/clock-widget", icon: <Clock className="h-4 w-4" />, desc: "Analog and digital clock" },
      { label: "Code Block Pro", href: "/code-block-pro", icon: <Code className="h-4 w-4" />, desc: "Advanced code block with highlights" },
      { label: "Compass Rose", href: "/compass-rose", icon: <Compass className="h-4 w-4" />, desc: "Compass rose navigation" },
      { label: "Component Story", href: "/component-story", icon: <Component className="h-4 w-4" />, desc: "Component story viewer" },
      { label: "Copy Button", href: "/copy-button", icon: <Copy className="h-4 w-4" />, desc: "One-click copy to clipboard" },
      { label: "Credit Card Form", href: "/credit-card-form", icon: <CreditCard className="h-4 w-4" />, desc: "Credit card input form" },
      { label: "Crop Tool", href: "/crop-tool", icon: <Crop className="h-4 w-4" />, desc: "Image crop tool" },
      { label: "Crosshair Cursor", href: "/crosshair-cursor", icon: <Crosshair className="h-4 w-4" />, desc: "Crosshair cursor overlay" },
      { label: "Crown Badge", href: "/crown-badge", icon: <Crown className="h-4 w-4" />, desc: "Premium crown badge" },
      { label: "3D Cube", href: "/cube-3d", icon: <Box className="h-4 w-4" />, desc: "3D CSS cube animation" },
      { label: "Cup Soda", href: "/cup-soda", icon: <CupSoda className="h-4 w-4" />, desc: "Fun cup soda animation" },
      { label: "Dawn Gradient", href: "/dawn-gradient", icon: <Sunrise className="h-4 w-4" />, desc: "Dawn gradient background" },
      { label: "Disc Spinner", href: "/disc-spinner", icon: <Disc className="h-4 w-4" />, desc: "Disc loading spinner" },
      { label: "DNA Helix", href: "/dna-helix", icon: <Dna className="h-4 w-4" />, desc: "DNA helix animation" },
      { label: "Download Button", href: "/download-button", icon: <Download className="h-4 w-4" />, desc: "Download button with progress" },
      { label: "Droplet Color", href: "/droplet-color", icon: <Droplet className="h-4 w-4" />, desc: "Color droplet picker" },
      { label: "Dumbbell Chart", href: "/dumbbell-chart", icon: <Dumbbell className="h-4 w-4" />, desc: "Dumbbell comparison chart" },
      { label: "Easel Canvas", href: "/easel-canvas", icon: <Paintbrush className="h-4 w-4" />, desc: "Easel drawing canvas" },
      { label: "Egg Timer", href: "/egg-timer", icon: <Egg className="h-4 w-4" />, desc: "Egg cooking timer" },
      { label: "Fence Pattern", href: "/fence-pattern", icon: <Fence className="h-4 w-4" />, desc: "Fence pattern background" },
      { label: "Ferris Wheel", href: "/ferris-wheel", icon: <FerrisWheel className="h-4 w-4" />, desc: "Ferris wheel animation" },
      { label: "Flame Effect", href: "/flame-effect", icon: <Flame className="h-4 w-4" />, desc: "Flame fire effect" },
      { label: "Flask Chemistry", href: "/flask-chemistry", icon: <FlaskConical className="h-4 w-4" />, desc: "Chemistry flask icon" },
      { label: "Flower Pattern", href: "/flower-pattern", icon: <Flower2 className="h-4 w-4" />, desc: "Flower pattern generator" },
      { label: "Footprints Trail", href: "/footprints-trail", icon: <Footprints className="h-4 w-4" />, desc: "Footprints trail effect" },
      { label: "Gamepad Controller", href: "/gamepad-controller", icon: <Gamepad2 className="h-4 w-4" />, desc: "Gamepad controller UI" },
      { label: "Gem Crystal", href: "/gem-crystal", icon: <Gem className="h-4 w-4" />, desc: "Gem crystal display" },
      { label: "Ghost Animation", href: "/ghost-animation", icon: <Ghost className="h-4 w-4" />, desc: "Ghost float animation" },
      { label: "Gift Wrap", href: "/gift-wrap", icon: <Gift className="h-4 w-4" />, desc: "Gift wrap card" },
      { label: "Globe Spin", href: "/globe-spin", icon: <Globe className="h-4 w-4" />, desc: "Spinning globe animation" },
      { label: "Hammer Tool", href: "/hammer-tool", icon: <Hammer className="h-4 w-4" />, desc: "Hammer tool icon" },
      { label: "Hard Hat Safety", href: "/hard-hat-safety", icon: <HardHat className="h-4 w-4" />, desc: "Safety hard hat badge" },
      { label: "Headphones Bar", href: "/headphones-bar", icon: <Headphones className="h-4 w-4" />, desc: "Audio headphones bar" },
      { label: "Heart Beat", href: "/heart-beat", icon: <Heart className="h-4 w-4" />, desc: "Heartbeat pulse animation" },
      { label: "Heater Control", href: "/heater-control", icon: <Heater className="h-4 w-4" />, desc: "Temperature heater control" },
      { label: "Helmet Shield", href: "/helmet-shield", icon: <HardHat className="h-4 w-4" />, desc: "Protective helmet icon" },
      { label: "Hip Hop Move", href: "/hip-hop-move", icon: <Music className="h-4 w-4" />, desc: "Hip hop dance animation" },
      { label: "Ice Cream Bowl", href: "/ice-cream-bowl", icon: <IceCreamBowl className="h-4 w-4" />, desc: "Ice cream bowl display" },
      { label: "Inbox Tray", href: "/inbox-tray", icon: <Inbox className="h-4 w-4" />, desc: "Inbox tray component" },
      { label: "Indian Rupee", href: "/indian-rupee", icon: <IndianRupee className="h-4 w-4" />, desc: "Indian rupee formatter" },
      { label: "Infinity Loop", href: "/infinity-loop", icon: <Infinity className="h-4 w-4" />, desc: "Infinity loop animation" },
      { label: "Inner Shadow", href: "/inner-shadow", icon: <Square className="h-4 w-4" />, desc: "Inner shadow effect" },
      { label: "Italic Text", href: "/italic-text", icon: <Italic className="h-4 w-4" />, desc: "Italic text formatting" },
      { label: "Jump Animation", href: "/jump-animation", icon: <Move className="h-4 w-4" />, desc: "Jump bounce animation" },
      { label: "Key Input", href: "/key-input", icon: <Key className="h-4 w-4" />, desc: "Keyboard key indicator" },
      { label: "Keyboard Layout", href: "/keyboard-layout", icon: <Keyboard className="h-4 w-4" />, desc: "Keyboard layout visualizer" },
      { label: "Laptop Mockup", href: "/laptop-mockup", icon: <Laptop className="h-4 w-4" />, desc: "Laptop device mockup" },
      { label: "Leaf Nature", href: "/leaf-nature", icon: <Leaf className="h-4 w-4" />, desc: "Nature leaf decoration" },
      { label: "Letter Text", href: "/letter-text", icon: <LetterText className="h-4 w-4" />, desc: "Letter text styling" },
      { label: "Life Buoy", href: "/life-buoy", icon: <LifeBuoy className="h-4 w-4" />, desc: "Life buoy help icon" },
      { label: "Lightbulb Idea", href: "/lightbulb-idea", icon: <Lightbulb className="h-4 w-4" />, desc: "Lightbulb idea indicator" },
      { label: "Line Chart Pro", href: "/line-chart-pro", icon: <LineChart className="h-4 w-4" />, desc: "Advanced line chart" },
      { label: "Link Chain", href: "/link-chain", icon: <Link2 className="h-4 w-4" />, desc: "Chain link component" },
      { label: "List Tree View", href: "/list-tree-view", icon: <ListTree className="h-4 w-4" />, desc: "Tree view list" },
      { label: "Locate Pin", href: "/locate-pin", icon: <Locate className="h-4 w-4" />, desc: "Location pin marker" },
      { label: "Magnet Field", href: "/magnet-field", icon: <Magnet className="h-4 w-4" />, desc: "Magnet field effect" },
      { label: "Mail Notify", href: "/mail-notify", icon: <Mail className="h-4 w-4" />, desc: "Mail notification badge" },
      { label: "Map Marker", href: "/map-marker", icon: <Map className="h-4 w-4" />, desc: "Map marker cluster" },
      { label: "Megaphone Announce", href: "/megaphone-announce", icon: <Megaphone className="h-4 w-4" />, desc: "Megaphone announcement" },
      { label: "Mic Recording", href: "/mic-recording", icon: <Mic className="h-4 w-4" />, desc: "Microphone recording UI" },
      { label: "Monitor Stand", href: "/monitor-stand", icon: <Monitor className="h-4 w-4" />, desc: "Monitor stand mockup" },
      { label: "Moon Dark", href: "/moon-dark", icon: <Moon className="h-4 w-4" />, desc: "Moon dark mode toggle" },
      { label: "Mountain Scene", href: "/mountain-scene", icon: <Mountain className="h-4 w-4" />, desc: "Mountain landscape scene" },
      { label: "Mouse Pointer", href: "/mouse-pointer", icon: <MousePointer className="h-4 w-4" />, desc: "Custom mouse pointer" },
      { label: "Move 3D", href: "/move-3d", icon: <Move3d className="h-4 w-4" />, desc: "3D transform controls" },
      { label: "Music Note", href: "/music-note", icon: <Music className="h-4 w-4" />, desc: "Music note animation" },
      { label: "Navigation Arrow", href: "/navigation-arrow", icon: <Navigation className="h-4 w-4" />, desc: "Navigation arrow indicator" },
      { label: "Notebook Journal", href: "/notebook-journal", icon: <Notebook className="h-4 w-4" />, desc: "Notebook journal layout" },
      { label: "Nut Bolt", href: "/nut-bolt", icon: <Nut className="h-4 w-4" />, desc: "Nut and bolt icon" },
      { label: "Options Gear", href: "/options-gear", icon: <Settings className="h-4 w-4" />, desc: "Options gear settings" },
      { label: "Package Box", href: "/package-box", icon: <Package className="h-4 w-4" />, desc: "Package box unboxing" },
      { label: "Paintbrush Art", href: "/paintbrush-art", icon: <Paintbrush className="h-4 w-4" />, desc: "Paintbrush art tool" },
      { label: "Palette Mixer", href: "/palette-mixer", icon: <Palette className="h-4 w-4" />, desc: "Color palette mixer" },
      { label: "Panel Bottom", href: "/panel-bottom", icon: <PanelBottom className="h-4 w-4" />, desc: "Bottom panel drawer" },
      { label: "Paperclip Attach", href: "/paperclip-attach", icon: <Paperclip className="h-4 w-4" />, desc: "Paperclip attachment" },
      { label: "Pencil Draw", href: "/pencil-draw", icon: <Pencil className="h-4 w-4" />, desc: "Pencil draw tool" },
      { label: "Pentagon Shape", href: "/pentagon-shape", icon: <Pentagon className="h-4 w-4" />, desc: "Pentagon shape SVG" },
      { label: "Pie Chart Pro", href: "/pie-chart-pro", icon: <PieChart className="h-4 w-4" />, desc: "Advanced pie chart" },
      { label: "Pin Location", href: "/pin-location", icon: <Pin className="h-4 w-4" />, desc: "Pin location marker" },
      { label: "Pipette Color", href: "/pipette-color", icon: <Pipette className="h-4 w-4" />, desc: "Color pipette tool" },
      { label: "Plane Travel", href: "/plane-travel", icon: <Plane className="h-4 w-4" />, desc: "Plane travel icon" },
      { label: "Plug Connect", href: "/plug-connect", icon: <Plug className="h-4 w-4" />, desc: "Plug connection status" },
      { label: "Podcast Audio", href: "/podcast-audio", icon: <Podcast className="h-4 w-4" />, desc: "Podcast audio player" },
      { label: "Pointer Click", href: "/pointer-click", icon: <Pointer className="h-4 w-4" />, desc: "Click pointer cursor" },
      { label: "Power Switch", href: "/power-switch", icon: <Power className="h-4 w-4" />, desc: "Power on/off switch" },
      { label: "Printer Output", href: "/printer-output", icon: <Printer className="h-4 w-4" />, desc: "Printer output preview" },
      { label: "Radar Scan", href: "/radar-scan", icon: <Radar className="h-4 w-4" />, desc: "Radar scan animation" },
      { label: "Radio Tune", href: "/radio-tune", icon: <Radio className="h-4 w-4" />, desc: "Radio tuner interface" },
      { label: "Ray Light", href: "/ray-light", icon: <Zap className="h-4 w-4" />, desc: "Light ray effect" },
      { label: "Rectangle Shape", href: "/rectangle-shape", icon: <RectangleHorizontal className="h-4 w-4" />, desc: "Rectangle shape tool" },
      { label: "Refrigerator", href: "/refrigerator", icon: <Refrigerator className="h-4 w-4" />, desc: "Refrigerator temperature" },
      { label: "Regex Tester", href: "/regex-tester", icon: <Regex className="h-4 w-4" />, desc: "Regex pattern tester" },
      { label: "Rotate Ccw", href: "/rotate-ccw", icon: <RotateCcw className="h-4 w-4" />, desc: "Rotate counterclockwise" },
      { label: "Router Signal", href: "/router-signal", icon: <Router className="h-4 w-4" />, desc: "Router signal strength" },
      { label: "Rss Feed", href: "/rss-feed", icon: <Rss className="h-4 w-4" />, desc: "RSS feed indicator" },
      { label: "Ruler Measure", href: "/ruler-measure", icon: <Ruler className="h-4 w-4" />, desc: "Ruler measurement tool" },
      { label: "Satellite Orbit", href: "/satellite-orbit", icon: <Satellite className="h-4 w-4" />, desc: "Satellite orbit animation" },
      { label: "Scale Balance", href: "/scale-balance", icon: <Scale className="h-4 w-4" />, desc: "Scale balance icon" },
      { label: "Scan QR", href: "/scan-qr", icon: <Scan className="h-4 w-4" />, desc: "QR code scanner" },
      { label: "Scan Line", href: "/scan-line", icon: <ScanLine className="h-4 w-4" />, desc: "Scan line animation" },
      { label: "Scissors Cut", href: "/scissors-cut", icon: <Scissors className="h-4 w-4" />, desc: "Scissors cut tool" },
      { label: "Send Message", href: "/send-message", icon: <Send className="h-4 w-4" />, desc: "Send message button" },
      { label: "Server Rack", href: "/server-rack", icon: <Server className="h-4 w-4" />, desc: "Server rack status" },
      { label: "Shield Secure", href: "/shield-secure", icon: <Shield className="h-4 w-4" />, desc: "Shield security icon" },
      { label: "Shield Check", href: "/shield-check", icon: <ShieldCheck className="h-4 w-4" />, desc: "Verified shield badge" },
      { label: "Shirt Wear", href: "/shirt-wear", icon: <Shirt className="h-4 w-4" />, desc: "Shirt clothing icon" },
      { label: "Shopping Bag", href: "/shopping-bag", icon: <ShoppingBag className="h-4 w-4" />, desc: "Shopping bag counter" },
      { label: "Shopping Cart", href: "/shopping-cart", icon: <ShoppingCart className="h-4 w-4" />, desc: "Shopping cart items" },
      { label: "Shower Head", href: "/shower-head", icon: <ShowerHead className="h-4 w-4" />, desc: "Shower water flow" },
      { label: "Shrub Garden", href: "/shrub-garden", icon: <Shrub className="h-4 w-4" />, desc: "Garden shrub icon" },
      { label: "Sigma Math", href: "/sigma-math", icon: <Sigma className="h-4 w-4" />, desc: "Sigma math symbol" },
      { label: "Skull Danger", href: "/skull-danger", icon: <Skull className="h-4 w-4" />, desc: "Skull danger warning" },
      { label: "Smile Emoji", href: "/smile-emoji", icon: <Smile className="h-4 w-4" />, desc: "Smile emoji picker" },
      { label: "Snowflake Winter", href: "/snowflake-winter", icon: <Snowflake className="h-4 w-4" />, desc: "Snowflake winter effect" },
      { label: "Sofa Comfort", href: "/sofa-comfort", icon: <Sofa className="h-4 w-4" />, desc: "Sofa comfort icon" },
      { label: "Sort Ascending", href: "/sort-ascending", icon: <SortAsc className="h-4 w-4" />, desc: "Sort ascending order" },
      { label: "Sort Descending", href: "/sort-descending", icon: <SortDesc className="h-4 w-4" />, desc: "Sort descending order" },
      { label: "Soup Bowl", href: "/soup-bowl", icon: <Soup className="h-4 w-4" />, desc: "Soup bowl icon" },
      { label: "Sparkles Magic", href: "/sparkles-magic", icon: <Sparkles className="h-4 w-4" />, desc: "Magic sparkles effect" },
      { label: "Speaker Audio", href: "/speaker-audio", icon: <Speaker className="h-4 w-4" />, desc: "Speaker audio controls" },
      { label: "Spray Can", href: "/spray-can", icon: <SprayCan className="h-4 w-4" />, desc: "Spray can paint tool" },
      { label: "Square Stack", href: "/square-stack", icon: <SquareStack className="h-4 w-4" />, desc: "Square stack layers" },
      { label: "Stamp Official", href: "/stamp-official", icon: <Stamp className="h-4 w-4" />, desc: "Official stamp seal" },
      { label: "Stethoscope Med", href: "/stethoscope-med", icon: <Stethoscope className="h-4 w-4" />, desc: "Medical stethoscope" },
      { label: "Sticky Note Pro", href: "/sticky-note-pro", icon: <StickyNote className="h-4 w-4" />, desc: "Sticky note with edit" },
      { label: "Store Front", href: "/store-front", icon: <Store className="h-4 w-4" />, desc: "Store front display" },
      { label: "Stretch Horizontal", href: "/stretch-horizontal", icon: <StretchHorizontal className="h-4 w-4" />, desc: "Horizontal stretch layout" },
      { label: "Subtitles Text", href: "/subtitles-text", icon: <Subtitles className="h-4 w-4" />, desc: "Subtitles text display" },
      { label: "Sugar Cube", href: "/sugar-cube", icon: <Box className="h-4 w-4" />, desc: "Sugar cube icon" },
      { label: "Sun Bright", href: "/sun-bright", icon: <Sun className="h-4 w-4" />, desc: "Sun brightness control" },
      { label: "Sunrise Morning", href: "/sunrise-morning", icon: <Sunrise className="h-4 w-4" />, desc: "Sunrise morning alarm" },
      { label: "Sunset Evening", href: "/sunset-evening", icon: <Sunset className="h-4 w-4" />, desc: "Sunset evening mode" },
      { label: "Swords Battle", href: "/swords-battle", icon: <Swords className="h-4 w-4" />, desc: "Swords battle icon" },
      { label: "Syringe Med", href: "/syringe-med", icon: <Syringe className="h-4 w-4" />, desc: "Medical syringe icon" },
      { label: "Tablet Device", href: "/tablet-device", icon: <Tablet className="h-4 w-4" />, desc: "Tablet device mockup" },
      { label: "Target Goal", href: "/target-goal", icon: <Target className="h-4 w-4" />, desc: "Target goal indicator" },
      { label: "Telescope View", href: "/telescope-view", icon: <Telescope className="h-4 w-4" />, desc: "Telescope view finder" },
      { label: "Temple Building", href: "/temple-building", icon: <Building2 className="h-4 w-4" />, desc: "Temple building icon" },
      { label: "Tent Camp", href: "/tent-camp", icon: <Tent className="h-4 w-4" />, desc: "Tent camping icon" },
      { label: "Thermometer Temp", href: "/thermometer-temp", icon: <Thermometer className="h-4 w-4" />, desc: "Thermometer temperature" },
      { label: "Ticket Event", href: "/ticket-event", icon: <Ticket className="h-4 w-4" />, desc: "Event ticket display" },
      { label: "Timer Countdown", href: "/timer-countdown", icon: <Timer className="h-4 w-4" />, desc: "Timer countdown clock" },
      { label: "Toggle Button", href: "/toggle-button", icon: <ToggleLeft className="h-4 w-4" />, desc: "Toggle button switch" },
      { label: "Train Transport", href: "/train-transport", icon: <Train className="h-4 w-4" />, desc: "Train transport icon" },
      { label: "Trash Delete", href: "/trash-delete", icon: <Trash className="h-4 w-4" />, desc: "Trash delete confirmation" },
      { label: "Tree Nature", href: "/tree-nature", icon: <TreeDeciduous className="h-4 w-4" />, desc: "Deciduous tree icon" },
      { label: "Trophy Award", href: "/trophy-award", icon: <Trophy className="h-4 w-4" />, desc: "Trophy award winner" },
      { label: "Truck Delivery", href: "/truck-delivery", icon: <Truck className="h-4 w-4" />, desc: "Truck delivery tracking" },
      { label: "TV Screen", href: "/tv-screen", icon: <Tv className="h-4 w-4" />, desc: "TV screen display" },
      { label: "Umbrella Rain", href: "/umbrella-rain", icon: <Umbrella className="h-4 w-4" />, desc: "Umbrella rain protection" },
      { label: "Underline Text", href: "/underline-text", icon: <Underline className="h-4 w-4" />, desc: "Underline text style" },
      { label: "Undo History", href: "/undo-history", icon: <Undo className="h-4 w-4" />, desc: "Undo history stack" },
      { label: "Unplug Disconnect", href: "/unplug-disconnect", icon: <Unplug className="h-4 w-4" />, desc: "Unplug disconnect status" },
      { label: "User Check", href: "/user-check", icon: <UserCheck className="h-4 w-4" />, desc: "User verified check" },
      { label: "User Minus", href: "/user-minus", icon: <UserMinus className="h-4 w-4" />, desc: "User remove action" },
      { label: "User Plus", href: "/user-plus", icon: <UserPlus className="h-4 w-4" />, desc: "User add action" },
      { label: "User X Remove", href: "/user-x-remove", icon: <UserX className="h-4 w-4" />, desc: "User block remove" },
      { label: "Users Round", href: "/users-round", icon: <UsersRound className="h-4 w-4" />, desc: "Users round group" },
      { label: "Vacuum Clean", href: "/vacuum-clean", icon: <Wind className="h-4 w-4" />, desc: "Vacuum cleaner icon" },
      { label: "Vegan Badge", href: "/vegan-badge", icon: <Vegan className="h-4 w-4" />, desc: "Vegan certified badge" },
      { label: "Venetian Mask", href: "/venetian-mask", icon: <VenetianMask className="h-4 w-4" />, desc: "Venetian mask icon" },
      { label: "Video Player", href: "/video-player", icon: <Video className="h-4 w-4" />, desc: "Video player controls" },
      { label: "View Toggle", href: "/view-toggle", icon: <View className="h-4 w-4" />, desc: "View mode toggle" },
      { label: "Voicemail Alert", href: "/voicemail-alert", icon: <Voicemail className="h-4 w-4" />, desc: "Voicemail alert badge" },
      { label: "Volleyball Sport", href: "/volleyball-sport", icon: <Volleyball className="h-4 w-4" />, desc: "Volleyball sport icon" },
      { label: "Wallet Finance", href: "/wallet-finance", icon: <Wallet className="h-4 w-4" />, desc: "Wallet finance tracker" },
      { label: "Watch Time", href: "/watch-time", icon: <Watch className="h-4 w-4" />, desc: "Watch time display" },
      { label: "Waves Sound", href: "/waves-sound", icon: <Waves className="h-4 w-4" />, desc: "Sound waves visualizer" },
      { label: "Webcam Stream", href: "/webcam-stream", icon: <Webcam className="h-4 w-4" />, desc: "Webcam live stream" },
      { label: "Wheat Harvest", href: "/wheat-harvest", icon: <Wheat className="h-4 w-4" />, desc: "Wheat harvest icon" },
      { label: "Whole Word", href: "/whole-word", icon: <WholeWord className="h-4 w-4" />, desc: "Whole word highlighting" },
      { label: "Wind Breeze", href: "/wind-breeze", icon: <Wind className="h-4 w-4" />, desc: "Wind breeze animation" },
      { label: "Wine Glass", href: "/wine-glass", icon: <Wine className="h-4 w-4" />, desc: "Wine glass icon" },
      { label: "Wrap Text", href: "/wrap-text", icon: <WrapText className="h-4 w-4" />, desc: "Text wrap formatting" },
      { label: "Wrench Fix", href: "/wrench-fix", icon: <Wrench className="h-4 w-4" />, desc: "Wrench fix settings" },
      { label: "Yard Garden", href: "/yard-garden", icon: <Leaf className="h-4 w-4" />, desc: "Yard garden icon" },
      { label: "Zap Lightning", href: "/zap-lightning", icon: <Zap className="h-4 w-4" />, desc: "Zap lightning flash" },
      { label: "Zoom In", href: "/zoom-in", icon: <ZoomIn className="h-4 w-4" />, desc: "Zoom in magnifier" },
      { label: "Zoom Out", href: "/zoom-out", icon: <ZoomOut className="h-4 w-4" />, desc: "Zoom out minimizer" },
    ],
  },
  {
    title: "More Components",
    icon: <Zap className="h-4 w-4" />,
    description: "200 more component demos",
    links: [
      { label: "Accordion Tabs", href: "/accordion-tabs", icon: <ChevronsRight className="h-4 w-4" />, desc: "Accordion with tab panels" },
      { label: "Alert Card", href: "/alert-card", icon: <AlertCircle className="h-4 w-4" />, desc: "Alert card notification" },
      { label: "Arrow Cursor", href: "/arrow-cursor", icon: <MousePointer className="h-4 w-4" />, desc: "Custom arrow cursor" },
      { label: "Bar Chart Horizontal", href: "/bar-chart-horizontal", icon: <BarChart3 className="h-4 w-4" />, desc: "Horizontal bar chart" },
      { label: "Bell Alarm", href: "/bell-alarm", icon: <Bell className="h-4 w-4" />, desc: "Bell alarm notification" },
      { label: "Block Quote", href: "/block-quote", icon: <Quote className="h-4 w-4" />, desc: "Styled block quote" },
      { label: "Board Kanban", href: "/board-kanban", icon: <Columns className="h-4 w-4" />, desc: "Kanban board layout" },
      { label: "Box Package", href: "/box-package", icon: <Package className="h-4 w-4" />, desc: "Box package unboxing" },
      { label: "Brackets Code", href: "/brackets-code", icon: <Code className="h-4 w-4" />, desc: "Code brackets highlight" },
      { label: "Brightness Control", href: "/brightness-control", icon: <Sun className="h-4 w-4" />, desc: "Screen brightness control" },
      { label: "Browser Window", href: "/browser-window", icon: <Monitor className="h-4 w-4" />, desc: "Browser window mockup" },
      { label: "Calculator", href: "/calculator", icon: <Calculator className="h-4 w-4" />, desc: "Calculator keypad" },
      { label: "Camera Lens", href: "/camera-lens", icon: <Camera className="h-4 w-4" />, desc: "Camera lens aperture" },
      { label: "Card Flip", href: "/card-flip", icon: <Square className="h-4 w-4" />, desc: "Card flip animation" },
      { label: "Chat Bubble", href: "/chat-bubble", icon: <MessageSquare className="h-4 w-4" />, desc: "Chat bubble variants" },
      { label: "Checkbox Group", href: "/checkbox-group", icon: <Check className="h-4 w-4" />, desc: "Checkbox group selection" },
      { label: "Circle Progress", href: "/circle-progress", icon: <CircleDot className="h-4 w-4" />, desc: "Circle progress indicator" },
      { label: "Clapper Board", href: "/clapper-board", icon: <Film className="h-4 w-4" />, desc: "Film clapper board" },
      { label: "Cloud Upload", href: "/cloud-upload", icon: <Cloud className="h-4 w-4" />, desc: "Cloud upload button" },
      { label: "Code Editor", href: "/code-editor", icon: <FileCode className="h-4 w-4" />, desc: "Code editor interface" },
      { label: "Coin Flip", href: "/coin-flip", icon: <Circle className="h-4 w-4" />, desc: "Coin flip animation" },
      { label: "Color Wheel", href: "/color-wheel", icon: <Palette className="h-4 w-4" />, desc: "Color wheel picker" },
      { label: "Comic Panel", href: "/comic-panel", icon: <SquareStack className="h-4 w-4" />, desc: "Comic panel layout" },
      { label: "Contact Card", href: "/contact-card", icon: <Contact className="h-4 w-4" />, desc: "Contact business card" },
      { label: "Cookie Consent", href: "/cookie-consent", icon: <Shield className="h-4 w-4" />, desc: "Cookie consent banner" },
      { label: "Counter Badge", href: "/counter-badge", icon: <Hash className="h-4 w-4" />, desc: "Counter badge with animation" },
      { label: "Dashboard Card", href: "/dashboard-card", icon: <LayoutDashboard className="h-4 w-4" />, desc: "Dashboard metric card" },
      { label: "Date Range", href: "/date-range", icon: <CalendarDays className="h-4 w-4" />, desc: "Date range picker" },
      { label: "Dock Bar", href: "/dock-bar", icon: <PanelBottom className="h-4 w-4" />, desc: "macOS dock bar" },
      { label: "Drag Sort", href: "/drag-sort", icon: <Move className="h-4 w-4" />, desc: "Drag to sort list" },
      { label: "Drawer Panel", href: "/drawer-panel", icon: <PanelLeft className="h-4 w-4" />, desc: "Side drawer panel" },
      { label: "Email Card", href: "/email-card", icon: <Mail className="h-4 w-4" />, desc: "Email card layout" },
      { label: "Emoji Picker", href: "/emoji-picker", icon: <Smile className="h-4 w-4" />, desc: "Emoji picker grid" },
      { label: "Equalizer", href: "/equalizer", icon: <SlidersHorizontal className="h-4 w-4" />, desc: "Audio equalizer bars" },
      { label: "Expand Card", href: "/expand-card", icon: <Maximize2 className="h-4 w-4" />, desc: "Expandable card" },
      { label: "Eye Tracker", href: "/eye-tracker", icon: <Eye className="h-4 w-4" />, desc: "Eye tracking cursor" },
      { label: "Fabric Weave", href: "/fabric-weave", icon: <Grid3x3 className="h-4 w-4" />, desc: "Fabric weave pattern" },
      { label: "File Explorer", href: "/file-explorer", icon: <Folder className="h-4 w-4" />, desc: "File explorer tree" },
      { label: "Film Strip", href: "/film-strip", icon: <Film className="h-4 w-4" />, desc: "Film strip timeline" },
      { label: "Flash Card", href: "/flash-card", icon: <BookOpen className="h-4 w-4" />, desc: "Flash card flip" },
      { label: "Floating Label", href: "/floating-label", icon: <Type className="h-4 w-4" />, desc: "Floating label input" },
      { label: "Font Size", href: "/font-size", icon: <Type className="h-4 w-4" />, desc: "Font size controls" },
      { label: "Form Wizard", href: "/form-wizard", icon: <ChevronsRight className="h-4 w-4" />, desc: "Multi-step form wizard" },
      { label: "Frame Player", href: "/frame-player", icon: <Play className="h-4 w-4" />, desc: "Frame-by-frame player" },
      { label: "Gallery Grid", href: "/gallery-grid", icon: <Image className="h-4 w-4" />, desc: "Gallery grid layout" },
      { label: "Glass Card", href: "/glass-card", icon: <Square className="h-4 w-4" />, desc: "Glassmorphism card" },
      { label: "Glow Effect", href: "/glow-effect", icon: <Zap className="h-4 w-4" />, desc: "Glow neon effect" },
      { label: "Gradient Text", href: "/gradient-text", icon: <Palette className="h-4 w-4" />, desc: "Gradient text effect" },
      { label: "Grid Gallery", href: "/grid-gallery", icon: <Grid3x3 className="h-4 w-4" />, desc: "Grid gallery layout" },
      { label: "Group Avatar", href: "/group-avatar", icon: <Users className="h-4 w-4" />, desc: "Group avatar stack" },
      { label: "Half Circle", href: "/half-circle", icon: <CircleDot className="h-4 w-4" />, desc: "Half circle gauge" },
      { label: "Hamburger Menu", href: "/hamburger-menu", icon: <Menu className="h-4 w-4" />, desc: "Hamburger menu icon" },
      { label: "Hash Tag", href: "/hash-tag", icon: <Hash className="h-4 w-4" />, desc: "Hashtag input" },
      { label: "Header Sticky", href: "/header-sticky", icon: <PanelTop className="h-4 w-4" />, desc: "Sticky header bar" },
      { label: "Hexagon Grid", href: "/hexagon-grid", icon: <Hexagon className="h-4 w-4" />, desc: "Hexagon grid layout" },
      { label: "Highlight Text", href: "/highlight-text", icon: <Highlighter className="h-4 w-4" />, desc: "Text highlight marker" },
      { label: "History Stack", href: "/history-stack", icon: <Undo className="h-4 w-4" />, desc: "History undo stack" },
      { label: "Horizontal Scroll", href: "/horizontal-scroll", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "Horizontal scroll area" },
      { label: "Icon Button", href: "/icon-button", icon: <Square className="h-4 w-4" />, desc: "Icon button variants" },
      { label: "Image Slider", href: "/image-slider", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "Image slider carousel" },
      { label: "Info Tooltip", href: "/info-tooltip", icon: <CircleAlert className="h-4 w-4" />, desc: "Info tooltip popover" },
      { label: "Input Mask", href: "/input-mask", icon: <Lock className="h-4 w-4" />, desc: "Input mask formatter" },
      { label: "Journal Entry", href: "/journal-entry", icon: <Notebook className="h-4 w-4" />, desc: "Journal entry card" },
      { label: "Joy Stick", href: "/joy-stick", icon: <Gamepad2 className="h-4 w-4" />, desc: "Virtual joystick" },
      { label: "Keyframe Anim", href: "/keyframe-anim", icon: <Play className="h-4 w-4" />, desc: "Keyframe animation" },
      { label: "Landing Hero", href: "/landing-hero", icon: <Star className="h-4 w-4" />, desc: "Landing page hero" },
      { label: "Lazy Load", href: "/lazy-load", icon: <Image className="h-4 w-4" />, desc: "Lazy load images" },
      { label: "Lightbox View", href: "/lightbox-view", icon: <Maximize2 className="h-4 w-4" />, desc: "Image lightbox viewer" },
      { label: "Line Clamp", href: "/line-clamp", icon: <AlignLeft className="h-4 w-4" />, desc: "Text line clamping" },
      { label: "List Accordion", href: "/list-accordion", icon: <List className="h-4 w-4" />, desc: "Accordion list view" },
      { label: "Loading Bar", href: "/loading-bar", icon: <Loader className="h-4 w-4" />, desc: "Loading progress bar" },
      { label: "Login Card", href: "/login-card", icon: <Lock className="h-4 w-4" />, desc: "Login card form" },
      { label: "Logo Cloud", href: "/logo-cloud", icon: <Image className="h-4 w-4" />, desc: "Logo cloud display" },
      { label: "Magnet Pull", href: "/magnet-pull", icon: <Magnet className="h-4 w-4" />, desc: "Magnet pull effect" },
      { label: "Marquee Scroll", href: "/marquee-scroll", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "Marquee scroll text" },
      { label: "Matrix Rain", href: "/matrix-rain", icon: <Terminal className="h-4 w-4" />, desc: "Matrix rain animation" },
      { label: "Menu Dropdown", href: "/menu-dropdown", icon: <ChevronDown className="h-4 w-4" />, desc: "Menu dropdown panel" },
      { label: "Meter Gauge", href: "/meter-gauge", icon: <Gauge className="h-4 w-4" />, desc: "Meter gauge display" },
      { label: "Modal Center", href: "/modal-center", icon: <Square className="h-4 w-4" />, desc: "Centered modal dialog" },
      { label: "Multi Step", href: "/multi-step", icon: <ChevronsRight className="h-4 w-4" />, desc: "Multi-step form" },
      { label: "Nav Tabs", href: "/nav-tabs", icon: <PanelTop className="h-4 w-4" />, desc: "Navigation tabs" },
      { label: "Notification Bell", href: "/notification-bell", icon: <Bell className="h-4 w-4" />, desc: "Notification bell badge" },
      { label: "Number Scroll", href: "/number-scroll", icon: <Hash className="h-4 w-4" />, desc: "Number scroll animation" },
      { label: "Onboarding Card", href: "/onboarding-card", icon: <Rocket className="h-4 w-4" />, desc: "Onboarding card flow" },
      { label: "Option Card", href: "/option-card", icon: <Square className="h-4 w-4" />, desc: "Option selection card" },
      { label: "Overlay Blur", href: "/overlay-blur", icon: <Eye className="h-4 w-4" />, desc: "Blur overlay effect" },
      { label: "Pagination Dots", href: "/pagination-dots", icon: <CircleDot className="h-4 w-4" />, desc: "Dot pagination indicator" },
      { label: "Parallax Scroll", href: "/parallax-scroll", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Parallax scroll effect" },
      { label: "Password Toggle", href: "/password-toggle", icon: <Lock className="h-4 w-4" />, desc: "Password show/hide" },
      { label: "Phone Mockup", href: "/phone-mockup", icon: <Smartphone className="h-4 w-4" />, desc: "Phone device mockup" },
      { label: "Pill Tabs", href: "/pill-tabs", icon: <PanelTop className="h-4 w-4" />, desc: "Pill-shaped tabs" },
      { label: "Pricing Card", href: "/pricing-card", icon: <DollarSign className="h-4 w-4" />, desc: "Pricing card layout" },
      { label: "Progress Circle", href: "/progress-circle", icon: <CircleDot className="h-4 w-4" />, desc: "Circular progress" },
      { label: "QR Scanner", href: "/qr-scanner", icon: <Scan className="h-4 w-4" />, desc: "QR code scanner" },
      { label: "Radio Card", href: "/radio-card", icon: <CircleDot className="h-4 w-4" />, desc: "Radio card selection" },
      { label: "Rating Bar", href: "/rating-bar", icon: <Star className="h-4 w-4" />, desc: "Star rating bar" },
      { label: "Read More", href: "/read-more", icon: <ChevronRight className="h-4 w-4" />, desc: "Read more expandable" },
      { label: "Realtime Clock", href: "/realtime-clock", icon: <Clock className="h-4 w-4" />, desc: "Real-time clock display" },
      { label: "Recording Dot", href: "/recording-dot", icon: <CircleDot className="h-4 w-4" />, desc: "Recording indicator dot" },
      { label: "Rich Table", href: "/rich-table", icon: <Table className="h-4 w-4" />, desc: "Rich data table" },
      { label: "Ring Progress", href: "/ring-progress", icon: <Loader className="h-4 w-4" />, desc: "Ring progress indicator" },
      { label: "Role Badge", href: "/role-badge", icon: <Shield className="h-4 w-4" />, desc: "User role badge" },
      { label: "Scroll Progress", href: "/scroll-progress", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Scroll progress bar" },
      { label: "Search Bar", href: "/search-bar", icon: <Search className="h-4 w-4" />, desc: "Search bar input" },
      { label: "Section Divider", href: "/section-divider", icon: <Minus className="h-4 w-4" />, desc: "Section divider line" },
      { label: "Select Dropdown", href: "/select-dropdown", icon: <ChevronDown className="h-4 w-4" />, desc: "Custom select dropdown" },
      { label: "Sent Indicator", href: "/sent-indicator", icon: <Check className="h-4 w-4" />, desc: "Message sent indicator" },
      { label: "Shape Builder", href: "/shape-builder", icon: <Square className="h-4 w-4" />, desc: "SVG shape builder" },
      { label: "Share Button", href: "/share-button", icon: <Share2 className="h-4 w-4" />, desc: "Social share button" },
      { label: "Shimmer Effect", href: "/shimmer-effect", icon: <Sparkles className="h-4 w-4" />, desc: "Shimmer loading effect" },
      { label: "Sidebar Nav", href: "/sidebar-nav", icon: <PanelLeft className="h-4 w-4" />, desc: "Sidebar navigation" },
      { label: "Size Picker", href: "/size-picker", icon: <Ruler className="h-4 w-4" />, desc: "Size selection picker" },
      { label: "Skeleton Avatar", href: "/skeleton-avatar", icon: <User className="h-4 w-4" />, desc: "Avatar skeleton loader" },
      { label: "Skeleton Card", href: "/skeleton-card", icon: <Square className="h-4 w-4" />, desc: "Card skeleton loader" },
      { label: "Slider Range", href: "/slider-range", icon: <SlidersHorizontal className="h-4 w-4" />, desc: "Slider range input" },
      { label: "Snap Scroll", href: "/snap-scroll", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Snap scroll container" },
      { label: "Social Card", href: "/social-card", icon: <Users className="h-4 w-4" />, desc: "Social media card" },
      { label: "Sparkline", href: "/sparkline", icon: <TrendingUp className="h-4 w-4" />, desc: "Inline sparkline chart" },
      { label: "Split Button", href: "/split-button", icon: <ChevronDown className="h-4 w-4" />, desc: "Split button dropdown" },
      { label: "Stacked Cards", href: "/stacked-cards", icon: <SquareStack className="h-4 w-4" />, desc: "Stacked card layout" },
      { label: "Status Dot", href: "/status-dot", icon: <CircleDot className="h-4 w-4" />, desc: "Status indicator dot" },
      { label: "Sticky Note", href: "/sticky-note", icon: <StickyNote className="h-4 w-4" />, desc: "Sticky note card" },
      { label: "Stopwatch", href: "/stopwatch", icon: <Timer className="h-4 w-4" />, desc: "Stopwatch timer" },
      { label: "Tag Cloud", href: "/tag-cloud", icon: <Tag className="h-4 w-4" />, desc: "Tag cloud display" },
      { label: "Task List", href: "/task-list", icon: <Check className="h-4 w-4" />, desc: "Task checklist" },
      { label: "Team Avatar", href: "/team-avatar", icon: <Users className="h-4 w-4" />, desc: "Team avatar group" },
      { label: "Testimonial Card", href: "/testimonial-card", icon: <Quote className="h-4 w-4" />, desc: "Testimonial card" },
      { label: "Text Gradient", href: "/text-gradient", icon: <Palette className="h-4 w-4" />, desc: "Text gradient effect" },
      { label: "Text Marquee", href: "/text-marquee", icon: <ArrowLeftRight className="h-4 w-4" />, desc: "Text marquee scroll" },
      { label: "Theme Toggle", href: "/theme-toggle", icon: <Moon className="h-4 w-4" />, desc: "Theme toggle switch" },
      { label: "Timeline Card", href: "/timeline-card", icon: <ScrollText className="h-4 w-4" />, desc: "Timeline card layout" },
      { label: "Toast Alert", href: "/toast-alert", icon: <Bell className="h-4 w-4" />, desc: "Toast alert message" },
      { label: "Toggle Pill", href: "/toggle-pill", icon: <ToggleLeft className="h-4 w-4" />, desc: "Pill toggle switch" },
      { label: "Tooltip Hint", href: "/tooltip-hint", icon: <CircleAlert className="h-4 w-4" />, desc: "Tooltip hint popup" },
      { label: "Track Progress", href: "/track-progress", icon: <Loader className="h-4 w-4" />, desc: "Track progress bar" },
      { label: "Transparent Card", href: "/transparent-card", icon: <Square className="h-4 w-4" />, desc: "Transparent card" },
      { label: "Tree View", href: "/tree-view", icon: <Folder className="h-4 w-4" />, desc: "Tree view navigation" },
      { label: "Trend Arrow", href: "/trend-arrow", icon: <TrendingUp className="h-4 w-4" />, desc: "Trend arrow indicator" },
      { label: "Typewriter Text", href: "/typewriter-text", icon: <Type className="h-4 w-4" />, desc: "Typewriter text effect" },
      { label: "Upload Zone", href: "/upload-zone", icon: <ArrowDownToLine className="h-4 w-4" />, desc: "File upload zone" },
      { label: "User Card", href: "/user-card", icon: <User className="h-4 w-4" />, desc: "User profile card" },
      { label: "Value Change", href: "/value-change", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Animated value change" },
      { label: "Video Card", href: "/video-card", icon: <Video className="h-4 w-4" />, desc: "Video thumbnail card" },
      { label: "Virtual Scroll", href: "/virtual-scroll", icon: <ArrowUpDown className="h-4 w-4" />, desc: "Virtual scroll list" },
      { label: "Volume Control", href: "/volume-control", icon: <Volume2 className="h-4 w-4" />, desc: "Volume slider control" },
      { label: "Warning Banner", href: "/warning-banner", icon: <AlertTriangle className="h-4 w-4" />, desc: "Warning alert banner" },
      { label: "Watermark", href: "/watermark", icon: <Eye className="h-4 w-4" />, desc: "Image watermark overlay" },
      { label: "Wave Background", href: "/wave-background", icon: <Waves className="h-4 w-4" />, desc: "Wave background effect" },
      { label: "Weather Card", href: "/weather-card", icon: <Cloud className="h-4 w-4" />, desc: "Weather display card" },
      { label: "Webhook Log", href: "/webhook-log", icon: <Terminal className="h-4 w-4" />, desc: "Webhook event log" },
      { label: "Width Slider", href: "/width-slider", icon: <SlidersHorizontal className="h-4 w-4" />, desc: "Width adjust slider" },
      { label: "Window Frame", href: "/window-frame", icon: <Monitor className="h-4 w-4" />, desc: "Window frame mockup" },
      { label: "Workspace Grid", href: "/workspace-grid", icon: <LayoutDashboard className="h-4 w-4" />, desc: "Workspace grid layout" },
      { label: "Year Picker", href: "/year-picker", icon: <Calendar className="h-4 w-4" />, desc: "Year selection picker" },
      { label: "Zero State", href: "/zero-state", icon: <Square className="h-4 w-4" />, desc: "Empty zero state" },
      { label: "Zigzag Divider", href: "/zigzag-divider", icon: <Minus className="h-4 w-4" />, desc: "Zigzag divider line" },
      { label: "Zip Download", href: "/zip-download", icon: <Download className="h-4 w-4" />, desc: "Zip file download" },
      { label: "Zone Picker", href: "/zone-picker", icon: <Map className="h-4 w-4" />, desc: "Timezone picker" },
      { label: "Z-order Stack", href: "/zorder-stack", icon: <Layers className="h-4 w-4" />, desc: "Z-order layer stack" },
      { label: "Zoom Control", href: "/zoom-control", icon: <ZoomIn className="h-4 w-4" />, desc: "Zoom control buttons" },
      { label: "Zone Alert", href: "/zone-alert", icon: <AlertCircle className="h-4 w-4" />, desc: "Zone-based alert" },
      { label: "Zebra Table", href: "/zebra-table", icon: <Table className="h-4 w-4" />, desc: "Zebra-striped table" },
      { label: "Zen Mode", href: "/zen-mode", icon: <Maximize2 className="h-4 w-4" />, desc: "Zen focus mode" },
      { label: "Zigzag Path", href: "/zigzag-path", icon: <TrendingUp className="h-4 w-4" />, desc: "Zigzag path chart" },
      { label: "Zero Gravity", href: "/zero-gravity", icon: <Sparkles className="h-4 w-4" />, desc: "Zero gravity animation" },
      { label: "Zip Extract", href: "/zip-extract", icon: <Package className="h-4 w-4" />, desc: "Zip extract progress" },
      { label: "Zone Select", href: "/zone-select", icon: <MapPin className="h-4 w-4" />, desc: "Zone selection input" },
      { label: "Z-axis Rotate", href: "/zaxis-rotate", icon: <RotateCcw className="h-4 w-4" />, desc: "Z-axis rotation effect" },
      { label: "Zigzag Border", href: "/zigzag-border", icon: <Minus className="h-4 w-4" />, desc: "Zigzag border style" },
      { label: "Zoom Lens", href: "/zoom-lens", icon: <ZoomIn className="h-4 w-4" />, desc: "Zoom lens magnifier" },
      { label: "Zone Overlay", href: "/zone-overlay", icon: <Eye className="h-4 w-4" />, desc: "Zone overlay highlight" },
      { label: "Z-Index Demo", href: "/zindex-demo", icon: <Layers className="h-4 w-4" />, desc: "Z-index layer demo" },
      { label: "Zip Progress", href: "/zip-progress", icon: <Loader className="h-4 w-4" />, desc: "Zip compression progress" },
      { label: "Zoom Slider", href: "/zoom-slider", icon: <SlidersHorizontal className="h-4 w-4" />, desc: "Zoom level slider" },
      { label: "Zone Map", href: "/zone-map", icon: <Map className="h-4 w-4" />, desc: "Zone map display" },
      { label: "Zebra Stripe", href: "/zebra-stripe", icon: <Table className="h-4 w-4" />, desc: "Zebra stripe rows" },
      { label: "Zen Garden", href: "/zen-garden", icon: <Flower2 className="h-4 w-4" />, desc: "Zen garden animation" },
      { label: "Zigzag Line", href: "/zigzag-line", icon: <TrendingUp className="h-4 w-4" />, desc: "Zigzag line chart" },
      { label: "Zip Card", href: "/zip-card", icon: <Package className="h-4 w-4" />, desc: "Zip archive card" },
      { label: "Zone Badge", href: "/zone-badge", icon: <MapPin className="h-4 w-4" />, desc: "Zone badge indicator" },
      { label: "Z-axis Scale", href: "/zaxis-scale", icon: <Maximize2 className="h-4 w-4" />, desc: "Z-axis scale transform" },
      { label: "Zigzag Wave", href: "/zigzag-wave", icon: <Waves className="h-4 w-4" />, desc: "Zigzag wave pattern" },
      { label: "Zoom Pan", href: "/zoom-pan", icon: <Move className="h-4 w-4" />, desc: "Zoom and pan viewer" },
      { label: "Zone Card", href: "/zone-card", icon: <MapPin className="h-4 w-4" />, desc: "Zone info card" },
      { label: "Z-rotate Card", href: "/zrotate-card", icon: <RotateCcw className="h-4 w-4" />, desc: "Z-rotate card effect" },
      { label: "Zigzag Divider V2", href: "/zigzag-divider-v2", icon: <Minus className="h-4 w-4" />, desc: "Zigzag divider v2" },
      { label: "Zoom Gesture", href: "/zoom-gesture", icon: <Hand className="h-4 w-4" />, desc: "Zoom gesture control" },
      { label: "Zone Panel", href: "/zone-panel", icon: <PanelLeft className="h-4 w-4" />, desc: "Zone panel layout" },
      { label: "Z-axis Flip", href: "/zaxis-flip", icon: <RefreshCw className="h-4 w-4" />, desc: "Z-axis flip animation" },
      { label: "Zigzag Border V2", href: "/zigzag-border-v2", icon: <Minus className="h-4 w-4" />, desc: "Zigzag border v2" },
      { label: "Zoom Image", href: "/zoom-image", icon: <ZoomIn className="h-4 w-4" />, desc: "Zoomable image viewer" },
      { label: "Zone Grid", href: "/zone-grid", icon: <Grid3x3 className="h-4 w-4" />, desc: "Zone grid layout" },
      { label: "Z-rotate Button", href: "/zrotate-button", icon: <RotateCcw className="h-4 w-4" />, desc: "Z-rotate button effect" },
      { label: "Zigzag Path V2", href: "/zigzag-path-v2", icon: <TrendingUp className="h-4 w-4" />, desc: "Zigzag path v2" },
      { label: "Zoom Button", href: "/zoom-button", icon: <ZoomIn className="h-4 w-4" />, desc: "Zoom toggle button" },
      { label: "Zone Header", href: "/zone-header", icon: <PanelTop className="h-4 w-4" />, desc: "Zone header layout" },
      { label: "Z-axis Skew", href: "/zaxis-skew", icon: <Move className="h-4 w-4" />, desc: "Z-axis skew transform" },
    ],
  },
];

/** Total number of links across the whole tree. */
export const navigationLinkCount = navigationSections.reduce(
  (total, section) => total + section.links.length,
  0
);
