import type { Product } from "../types/ecommerce.types";

export const PRODUCTS_PART_1: Product[] = [
  {
    id: "1",
    slug: "wireless-noise-cancelling-headphones",
    title: "Wireless Noise Cancelling Headphones",
    description:
      "Premium over-ear headphones with active noise cancellation, 30-hour battery life, and Hi-Res Audio support. Experience crystal-clear sound with adaptive EQ that automatically adjusts to your ear shape.",
    price: 299.99,
    originalPrice: 399.99,
    rating: 4.8,
    reviewCount: 2341,
    category: "Electronics",
    tags: ["Audio", "Wireless", "Noise Cancelling"],
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80",
    ],
    stock: 15,
    featured: true,
    badge: "Best Seller",
    sold: 4521,
    viewers: 89,
    shipping: { freeShipping: true, estimatedDays: 3, ExpressAvailable: true },
    quantityDiscounts: [
      { minQuantity: 2, discountPercent: 5, label: "Buy 2, Save 5%" },
      { minQuantity: 5, discountPercent: 10, label: "Buy 5, Save 10%" },
      { minQuantity: 10, discountPercent: 15, label: "Buy 10, Save 15%" },
    ],
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Midnight Black", value: "black" },
          { label: "Arctic White", value: "white" },
          { label: "Navy Blue", value: "blue" },
        ],
      },
    ],
    specifications: [
      { label: "Driver Size", value: "40mm" },
      { label: "Frequency Response", value: "4Hz - 40kHz" },
      { label: "Battery Life", value: "30 hours" },
      { label: "Charging Time", value: "2 hours" },
      { label: "Weight", value: "250g" },
      { label: "Bluetooth", value: "5.2" },
      { label: "Noise Cancellation", value: "Adaptive ANC" },
      { label: "Codec Support", value: "LDAC, AAC, SBC" },
    ],
    reviews: [
      {
        id: "r1",
        author: "AudioPhile_Mike",
        date: "Mar 10, 2026",
        rating: 5,
        title: "Best headphones I've ever owned",
        content: "The noise cancellation is incredible. I use these on my daily commute and in the office. Battery life easily lasts a full work week. Sound quality is exceptional across all genres.",
        helpful: 127,
        verified: true,
      },
      {
        id: "r2",
        author: "TechReviewer_Sarah",
        date: "Mar 5, 2026",
        rating: 4,
        title: "Great sound, minor comfort issue",
        content: "Sound quality is phenomenal and ANC is top-tier. Only minor issue is the ear cups could be slightly more comfortable for very long listening sessions (4+ hours). Overall highly recommended.",
        helpful: 89,
        verified: true,
      },
      {
        id: "r3",
        author: "DailyCommuter_J",
        date: "Feb 28, 2026",
        rating: 5,
        title: "Worth every penny",
        content: "Upgraded from a cheaper pair and the difference is night and day. The adaptive EQ is a game-changer. Also love the multipoint connection - switching between phone and laptop is seamless.",
        helpful: 56,
        verified: true,
      },
    ],
  },
  {
    id: "2",
    slug: "premium-leather-backpack",
    title: "Premium Leather Backpack",
    description:
      "Handcrafted full-grain leather backpack with padded laptop compartment and multiple organizer pockets. Built to last a lifetime with premium YKK zippers and reinforced stitching.",
    price: 189.99,
    rating: 4.6,
    reviewCount: 876,
    category: "Accessories",
    tags: ["Leather", "Travel", "Work"],
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
    ],
    stock: 8,
    featured: true,
    sold: 1892,
    viewers: 34,
    shipping: { freeShipping: true, estimatedDays: 5 },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Cognac Brown", value: "brown" },
          { label: "Classic Black", value: "black" },
          { label: "Tan", value: "tan" },
        ],
      },
      {
        type: "size",
        name: "Size",
        options: [
          { label: "Regular (15\")", value: "regular" },
          { label: "Large (17\")", value: "large", priceModifier: 20 },
        ],
      },
    ],
    specifications: [
      { label: "Material", value: "Full-Grain Leather" },
      { label: "Laptop Fit", value: "Up to 16\"" },
      { label: "Capacity", value: "25L" },
      { label: "Dimensions", value: "18\" x 12\" x 8\"" },
      { label: "Weight", value: "1.8 kg" },
      { label: "Zippers", value: "YKK" },
    ],
    reviews: [
      {
        id: "r4",
        author: "StyleExpert_Alex",
        date: "Mar 12, 2026",
        rating: 5,
        title: "Premium quality, beautiful leather",
        content: "The leather quality is outstanding. It's developing a beautiful patina after just a few weeks. Fits my 16\" MacBook perfectly with room to spare. The organization pockets are well thought out.",
        helpful: 98,
        verified: true,
      },
      {
        id: "r5",
        author: "TravelPro_Lisa",
        date: "Mar 1, 2026",
        rating: 4,
        title: "Great for business travel",
        content: "This has become my go-to travel bag. Fits under airline seats perfectly. The leather is gorgeous and seems very durable. Would love to see a version with a luggage strap.",
        helpful: 45,
        verified: true,
      },
    ],
  },
  {
    id: "3",
    slug: "smart-fitness-tracker",
    title: "Smart Fitness Tracker",
    description:
      "Advanced fitness tracker with heart rate monitoring, GPS, sleep tracking, and 7-day battery life. Track over 100 workout modes with real-time metrics.",
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.5,
    reviewCount: 1543,
    category: "Electronics",
    tags: ["Fitness", "Wearable", "Health"],
    images: [
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
      "https://images.unsplash.com/photo-1510017803434-a899398421b3?w=600&q=80",
    ],
    stock: 22,
    featured: true,
    badge: "Sale",
    sold: 3267,
    viewers: 156,
    shipping: { freeShipping: true, estimatedDays: 2, ExpressAvailable: true },
    flashSale: {
      id: "fs1",
      productId: "3",
      salePrice: 119.99,
      endsAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
      totalAvailable: 50,
      claimedCount: 32,
    },
    quantityDiscounts: [
      { minQuantity: 3, discountPercent: 8, label: "Buy 3, Save 8%" },
      { minQuantity: 6, discountPercent: 12, label: "Buy 6, Save 12%" },
    ],
    variants: [
      {
        type: "color",
        name: "Band Color",
        options: [
          { label: "Black", value: "black" },
          { label: "Rose Gold", value: "rosegold" },
          { label: "Forest Green", value: "green" },
        ],
      },
      {
        type: "size",
        name: "Size",
        options: [
          { label: "Small", value: "small" },
          { label: "Medium", value: "medium" },
          { label: "Large", value: "large" },
        ],
      },
    ],
    specifications: [
      { label: "Display", value: "1.4\" AMOLED" },
      { label: "Battery Life", value: "7 days" },
      { label: "Water Resistance", value: "5 ATM" },
      { label: "Sensors", value: "HR, SpO2, GPS" },
      { label: "Workout Modes", value: "100+" },
      { label: "Weight", value: "35g" },
    ],
    reviews: [
      {
        id: "r6",
        author: "FitnessFanatic_Dave",
        date: "Mar 8, 2026",
        rating: 5,
        title: "Perfect workout companion",
        content: "Battery life is as advertised - I charge it once a week. GPS is accurate and syncs quickly. Sleep tracking has helped me improve my rest quality. Highly recommend for serious fitness enthusiasts.",
        helpful: 134,
        verified: true,
      },
    ],
  },
  {
    id: "4",
    slug: "organic-cotton-t-shirt",
    title: "Organic Cotton T-Shirt",
    description:
      "Sustainably made 100% organic cotton t-shirt with a relaxed fit and eco-friendly dyes. GOTS certified organic cotton with reinforced seams.",
    price: 39.99,
    rating: 4.4,
    reviewCount: 654,
    category: "Clothing",
    tags: ["Organic", "Sustainable", "Casual"],
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80",
    ],
    stock: 45,
    sold: 2156,
    viewers: 67,
    shipping: { freeShipping: false, estimatedDays: 5 },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "White", value: "white" },
          { label: "Black", value: "black" },
          { label: "Sage Green", value: "sage" },
          { label: "Dusty Rose", value: "rose" },
          { label: "Navy", value: "navy" },
        ],
      },
      {
        type: "size",
        name: "Size",
        options: [
          { label: "XS", value: "xs" },
          { label: "S", value: "s" },
          { label: "M", value: "m" },
          { label: "L", value: "l" },
          { label: "XL", value: "xl" },
          { label: "XXL", value: "xxl" },
        ],
      },
    ],
    specifications: [
      { label: "Material", value: "100% Organic Cotton" },
      { label: "Fit", value: "Relaxed" },
      { label: "Weight", value: "180 GSM" },
      { label: "Certification", value: "GOTS" },
      { label: "Care", value: "Machine wash cold" },
    ],
    reviews: [
      {
        id: "r7",
        author: "EcoShopper_Kim",
        date: "Mar 14, 2026",
        rating: 5,
        title: "Softest t-shirt I own",
        content: "The fabric quality is incredible - so soft and comfortable. Love that it's sustainably made. Washes well without shrinking. Already ordered two more colors!",
        helpful: 78,
        verified: true,
      },
    ],
  },
  {
    id: "5",
    slug: "professional-english-cookbook",
    title: "Professional English Cookbook",
    description:
      "Comprehensive 400-page cookbook featuring 200+ recipes from world-renowned chefs with step-by-step instructions and stunning photography.",
    price: 49.99,
    rating: 4.9,
    reviewCount: 321,
    category: "Books",
    tags: ["Cooking", "Professional", "Reference"],
    images: [
      "https://images.unsplash.com/photo-1589998059171-988d887df646?w=600&q=80",
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80",
    ],
    stock: 30,
    sold: 892,
    viewers: 23,
    shipping: { freeShipping: true, estimatedDays: 4 },
    specifications: [
      { label: "Pages", value: "400" },
      { label: "Recipes", value: "200+" },
      { label: "Language", value: "English" },
      { label: "Binding", value: "Hardcover" },
      { label: "Dimensions", value: "10\" x 12\"" },
    ],
    reviews: [
      {
        id: "r8",
        author: "HomeChef_Amanda",
        date: "Mar 3, 2026",
        rating: 5,
        title: "A kitchen essential",
        content: "This cookbook has transformed my cooking. The recipes are well-explained and the photography is beautiful. Worth every penny for anyone serious about cooking.",
        helpful: 67,
        verified: true,
      },
    ],
  },
  {
    id: "6",
    slug: "yoga-mat-premium",
    title: "Premium Yoga Mat",
    description:
      "Extra-thick 6mm eco-friendly TPE yoga mat with alignment lines and carrying strap. Non-slip surface on both sides for maximum grip.",
    price: 68.99,
    originalPrice: 89.99,
    rating: 4.7,
    reviewCount: 987,
    category: "Sports",
    tags: ["Yoga", "Fitness", "Eco-Friendly"],
    images: [
      "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&q=80",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    ],
    stock: 18,
    featured: true,
    badge: "Sale",
    sold: 2890,
    viewers: 112,
    shipping: { freeShipping: true, estimatedDays: 3 },
    flashSale: {
      id: "fs2",
      productId: "6",
      salePrice: 49.99,
      endsAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      totalAvailable: 30,
      claimedCount: 18,
    },
    quantityDiscounts: [
      { minQuantity: 2, discountPercent: 10, label: "Buy 2, Save 10%" },
      { minQuantity: 4, discountPercent: 15, label: "Buy 4, Save 15%" },
    ],
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Purple", value: "purple" },
          { label: "Teal", value: "teal" },
          { label: "Black", value: "black" },
          { label: "Pink", value: "pink" },
        ],
      },
    ],
    specifications: [
      { label: "Thickness", value: "6mm" },
      { label: "Material", value: "TPE (Eco-Friendly)" },
      { label: "Dimensions", value: "72\" x 26\"" },
      { label: "Weight", value: "2.5 kg" },
      { label: "Surface", value: "Non-slip both sides" },
      { label: "Includes", value: "Carrying strap" },
    ],
    reviews: [
      {
        id: "r9",
        author: "YogaInstructor_Nina",
        date: "Mar 11, 2026",
        rating: 5,
        title: "Studio quality at home",
        content: "The grip is amazing - no slipping even during hot yoga. Love the alignment lines, they're subtle but helpful. The eco-friendly material was a big plus for my decision.",
        helpful: 112,
        verified: true,
      },
    ],
  },
  {
    id: "7",
    slug: "stainless-steel-water-bottle",
    title: "Stainless Steel Water Bottle",
    description:
      "Double-wall vacuum insulated water bottle keeps drinks cold for 24 hours or hot for 12 hours. BPA-free with wide mouth for easy cleaning.",
    price: 34.99,
    rating: 4.6,
    reviewCount: 1234,
    category: "Home & Kitchen",
    tags: ["Hydration", "Sustainable", "Insulated"],
    images: [
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
      "https://images.unsplash.com/photo-1523364696700-30fac6a0f541?w=600&q=80",
    ],
    stock: 50,
    sold: 5678,
    viewers: 45,
    shipping: { freeShipping: true, estimatedDays: 3 },
    quantityDiscounts: [
      { minQuantity: 3, discountPercent: 10, label: "Buy 3, Save 10%" },
      { minQuantity: 6, discountPercent: 15, label: "Buy 6, Save 15%" },
      { minQuantity: 12, discountPercent: 20, label: "Buy 12, Save 20%" },
    ],
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Brushed Steel", value: "steel" },
          { label: "Matte Black", value: "black" },
          { label: "Ocean Blue", value: "blue" },
          { label: "Coral", value: "coral" },
        ],
      },
      {
        type: "size",
        name: "Size",
        options: [
          { label: "500ml", value: "500ml" },
          { label: "750ml", value: "750ml", priceModifier: 5 },
          { label: "1L", value: "1l", priceModifier: 10 },
        ],
      },
    ],
    specifications: [
      { label: "Material", value: "18/8 Stainless Steel" },
      { label: "Insulation", value: "Double-wall vacuum" },
      { label: "Cold Retention", value: "24 hours" },
      { label: "Hot Retention", value: "12 hours" },
      { label: "BPA Free", value: "Yes" },
    ],
    reviews: [],
  },
  {
    id: "8",
    slug: "wireless-charging-pad",
    title: "Wireless Charging Pad",
    description:
      "Sleek 15W fast wireless charging pad compatible with all Qi-enabled devices. LED indicator and foreign object detection for safety.",
    price: 29.99,
    originalPrice: 44.99,
    rating: 4.3,
    reviewCount: 567,
    category: "Electronics",
    tags: ["Charging", "Wireless", "Fast"],
    images: [
      "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&q=80",
      "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80",
    ],
    stock: 35,
    badge: "Sale",
    sold: 1892,
    viewers: 34,
    shipping: { freeShipping: false, estimatedDays: 4 },
    specifications: [
      { label: "Output", value: "15W Max" },
      { label: "Compatibility", value: "All Qi devices" },
      { label: "Input", value: "USB-C" },
      { label: "Safety", value: "FOD, Overcharge" },
    ],
    reviews: [],
  },
  {
    id: "9",
    slug: "slim-fit-jeans",
    title: "Slim Fit Stretch Jeans",
    description:
      "Modern slim fit jeans with 4-way stretch fabric for ultimate comfort. Made from sustainable denim with water-saving production.",
    price: 79.99,
    rating: 4.5,
    reviewCount: 892,
    category: "Clothing",
    tags: ["Denim", "Casual", "Stretch"],
    images: [
      "https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80",
      "https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=600&q=80",
    ],
    stock: 28,
    sold: 1567,
    viewers: 78,
    shipping: { freeShipping: true, estimatedDays: 4 },
    variants: [
      {
        type: "color",
        name: "Wash",
        options: [
          { label: "Dark Indigo", value: "dark" },
          { label: "Medium Wash", value: "medium" },
          { label: "Light Wash", value: "light" },
        ],
      },
      {
        type: "size",
        name: "Waist",
        options: [
          { label: "28", value: "28" },
          { label: "30", value: "30" },
          { label: "32", value: "32" },
          { label: "34", value: "34" },
          { label: "36", value: "36" },
        ],
      },
    ],
    specifications: [
      { label: "Material", value: "98% Cotton, 2% Elastane" },
      { label: "Fit", value: "Slim" },
      { label: "Rise", value: "Mid-Rise" },
      { label: "Stretch", value: "4-Way" },
    ],
    reviews: [],
  },
  {
    id: "10",
    slug: "ceramic-plant-pots-set",
    title: "Ceramic Plant Pots Set",
    description:
      "Set of 3 minimalist ceramic plant pots in matte white finish with bamboo saucers. Drainage holes included.",
    price: 44.99,
    rating: 4.7,
    reviewCount: 445,
    category: "Home & Kitchen",
    tags: ["Plants", "Decor", "Ceramic"],
    images: [
      "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&q=80",
      "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600&q=80",
    ],
    stock: 20,
    sold: 789,
    viewers: 28,
    shipping: { freeShipping: true, estimatedDays: 5 },
    specifications: [
      { label: "Material", value: "Ceramic + Bamboo" },
      { label: "Set Includes", value: "3 pots" },
      { label: "Sizes", value: "4\", 5\", 6\"" },
      { label: "Drainage", value: "Yes" },
    ],
    reviews: [],
  },
];
