import type { Product } from "../types/ecommerce.types";

export const PRODUCTS_PART_2: Product[] = [
  {
    id: "11",
    slug: "running-shoes-pro",
    title: "Professional Running Shoes",
    description:
      "Lightweight performance running shoes with responsive cushioning and carbon fiber plate. Engineered mesh upper for breathability.",
    price: 159.99,
    originalPrice: 189.99,
    rating: 4.8,
    reviewCount: 1678,
    category: "Sports",
    tags: ["Running", "Performance", "Lightweight"],
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80",
    ],
    stock: 12,
    badge: "New",
    sold: 2345,
    viewers: 189,
    shipping: { freeShipping: true, estimatedDays: 2, ExpressAvailable: true },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Red/Black", value: "red" },
          { label: "White/Blue", value: "white" },
          { label: "All Black", value: "black" },
        ],
      },
      {
        type: "size",
        name: "Size",
        options: [
          { label: "US 7", value: "7" },
          { label: "US 8", value: "8" },
          { label: "US 9", value: "9" },
          { label: "US 10", value: "10" },
          { label: "US 11", value: "11" },
          { label: "US 12", value: "12" },
        ],
      },
    ],
    specifications: [
      { label: "Weight", value: "215g" },
      { label: "Drop", value: "8mm" },
      { label: "Plate", value: "Carbon Fiber" },
      { label: "Upper", value: "Engineered Mesh" },
      { label: "Cushioning", value: "React Foam" },
    ],
    reviews: [
      {
        id: "r10",
        author: "MarathonRunner_Chris",
        date: "Mar 13, 2026",
        rating: 5,
        title: "Shaved 5 minutes off my PR",
        content: "The carbon plate makes a real difference. I've worn these for two marathons now and they perform exceptionally well. The energy return is noticeable from the first step.",
        helpful: 189,
        verified: true,
      },
      {
        id: "r11",
        author: "CasualJogger_Tom",
        date: "Mar 7, 2026",
        rating: 4,
        title: "Great for speed work",
        content: "These shoes are perfect for tempo runs and races. They feel fast and responsive. For easy/recovery runs I prefer something with more cushion, but for performance they're unbeatable.",
        helpful: 67,
        verified: true,
      },
    ],
  },
  {
    id: "12",
    slug: "leather-wallet-rfid",
    title: "RFID Blocking Leather Wallet",
    description:
      "Slim bifold wallet crafted from genuine leather with RFID blocking technology. 8 card slots and bill compartment.",
    price: 54.99,
    rating: 4.4,
    reviewCount: 723,
    category: "Accessories",
    tags: ["Wallet", "Leather", "RFID"],
    images: [
      "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&q=80",
      "https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=600&q=80",
    ],
    stock: 40,
    sold: 1234,
    viewers: 45,
    shipping: { freeShipping: true, estimatedDays: 4 },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Brown", value: "brown" },
          { label: "Black", value: "black" },
          { label: "Burgundy", value: "burgundy" },
        ],
      },
    ],
    specifications: [
      { label: "Material", value: "Genuine Leather" },
      { label: "Card Slots", value: "8" },
      { label: "RFID", value: "Blocking" },
      { label: "Dimensions", value: "4.5\" x 3.5\"" },
    ],
    reviews: [],
  },
  {
    id: "13",
    slug: "smart-home-speaker",
    title: "Smart Home Speaker",
    description:
      "Voice-controlled smart speaker with premium 360-degree sound and built-in smart home hub. Supports all major voice assistants.",
    price: 129.99,
    rating: 4.6,
    reviewCount: 1890,
    category: "Electronics",
    tags: ["Smart Home", "Audio", "Voice Control"],
    images: [
      "https://images.unsplash.com/photo-1543512214-318c7553f230?w=600&q=80",
      "https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=600&q=80",
    ],
    stock: 25,
    sold: 3456,
    viewers: 123,
    shipping: { freeShipping: true, estimatedDays: 3 },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Charcoal", value: "charcoal" },
          { label: "Sand", value: "sand" },
          { label: "Twilight Blue", value: "blue" },
        ],
      },
    ],
    specifications: [
      { label: "Sound", value: "360-degree" },
      { label: "Connectivity", value: "WiFi, Bluetooth" },
      { label: "Smart Hub", value: "Zigbee, Thread" },
      { label: "Mics", value: "Far-field 7-mic array" },
    ],
    reviews: [],
  },
  {
    id: "14",
    slug: "merino-wool-sweater",
    title: "Merino Wool Sweater",
    description:
      "Luxuriously soft 100% Merino wool sweater with temperature-regulating properties. Perfect for layering or wearing alone.",
    price: 119.99,
    rating: 4.7,
    reviewCount: 432,
    category: "Clothing",
    tags: ["Wool", "Premium", "Winter"],
    images: [
      "https://images.unsplash.com/photo-1434389677669-e08b4cda3a47?w=600&q=80",
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    ],
    stock: 16,
    sold: 567,
    viewers: 34,
    shipping: { freeShipping: true, estimatedDays: 5 },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Charcoal", value: "charcoal" },
          { label: "Oatmeal", value: "oatmeal" },
          { label: "Forest", value: "forest" },
        ],
      },
      {
        type: "size",
        name: "Size",
        options: [
          { label: "S", value: "s" },
          { label: "M", value: "m" },
          { label: "L", value: "l" },
          { label: "XL", value: "xl" },
        ],
      },
    ],
    specifications: [
      { label: "Material", value: "100% Merino Wool" },
      { label: "Fit", value: "Regular" },
      { label: "Care", value: "Hand wash" },
    ],
    reviews: [],
  },
  {
    id: "15",
    slug: "portable-bluetooth-speaker",
    title: "Portable Bluetooth Speaker",
    description:
      "Rugged waterproof Bluetooth speaker with 20-hour playtime and 360-degree sound. IP67 rated for dust and water resistance.",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviewCount: 1345,
    category: "Electronics",
    tags: ["Portable", "Waterproof", "Bluetooth"],
    images: [
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
      "https://images.unsplash.com/photo-1589003077984-894e133dabab?w=600&q=80",
    ],
    stock: 30,
    badge: "Sale",
    sold: 2890,
    viewers: 167,
    shipping: { freeShipping: true, estimatedDays: 3 },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Black", value: "black" },
          { label: "Red", value: "red" },
          { label: "Blue", value: "blue" },
          { label: "Green", value: "green" },
        ],
      },
    ],
    specifications: [
      { label: "Battery", value: "20 hours" },
      { label: "Water Rating", value: "IP67" },
      { label: "Sound", value: "360-degree" },
      { label: "Pairing", value: "Multi-speaker" },
    ],
    reviews: [],
  },
  {
    id: "16",
    slug: "cast-iron-dutch-oven",
    title: "Cast Iron Dutch Oven",
    description:
      "Enameled cast iron Dutch oven with self-basting lid, oven-safe to 500°F. Perfect for braising, baking bread, and slow cooking.",
    price: 89.99,
    rating: 4.8,
    reviewCount: 678,
    category: "Home & Kitchen",
    tags: ["Cooking", "Cast Iron", "Durable"],
    images: [
      "https://images.unsplash.com/photo-1585837146751-a44118595080?w=600&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
    ],
    stock: 14,
    sold: 1567,
    viewers: 56,
    shipping: { freeShipping: true, estimatedDays: 4 },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "Classic Red", value: "red" },
          { label: "Marseille Yellow", value: "yellow" },
          { label: "Artichaut", value: "green" },
        ],
      },
      {
        type: "size",
        name: "Size",
        options: [
          { label: "5.5 Qt", value: "5.5" },
          { label: "7.25 Qt", value: "7.25", priceModifier: 30 },
          { label: "9 Qt", value: "9", priceModifier: 60 },
        ],
      },
    ],
    specifications: [
      { label: "Material", value: "Enameled Cast Iron" },
      { label: "Oven Safe", value: "500°F" },
      { label: "Dishwasher", value: "Safe" },
      { label: "Lid", value: "Self-basting" },
    ],
    reviews: [],
  },
  {
    id: "17",
    slug: "canvas-sneakers-classic",
    title: "Classic Canvas Sneakers",
    description:
      "Timeless canvas sneakers with vulcanized rubber sole and cushioned insole. A wardrobe staple for any casual outfit.",
    price: 49.99,
    rating: 4.3,
    reviewCount: 2100,
    category: "Clothing",
    tags: ["Casual", "Canvas", "Classic"],
    images: [
      "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80",
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80",
    ],
    stock: 55,
    sold: 4567,
    viewers: 89,
    shipping: { freeShipping: false, estimatedDays: 5 },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "White", value: "white" },
          { label: "Black", value: "black" },
          { label: "Navy", value: "navy" },
          { label: "Red", value: "red" },
        ],
      },
      {
        type: "size",
        name: "Size",
        options: [
          { label: "US 7", value: "7" },
          { label: "US 8", value: "8" },
          { label: "US 9", value: "9" },
          { label: "US 10", value: "10" },
          { label: "US 11", value: "11" },
        ],
      },
    ],
    specifications: [
      { label: "Upper", value: "Canvas" },
      { label: "Sole", value: "Vulcanized Rubber" },
      { label: "Insole", value: "Cushioned" },
    ],
    reviews: [],
  },
  {
    id: "18",
    slug: "sunglasses-polarized",
    title: "Polarized Sunglasses",
    description:
      "Lightweight polarized sunglasses with UV400 protection and titanium frame. Includes hard case and cleaning cloth.",
    price: 149.99,
    rating: 4.6,
    reviewCount: 567,
    category: "Accessories",
    tags: ["UV Protection", "Polarized", "Lightweight"],
    images: [
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&q=80",
    ],
    stock: 22,
    sold: 890,
    viewers: 45,
    shipping: { freeShipping: true, estimatedDays: 3 },
    variants: [
      {
        type: "color",
        name: "Frame/Lens",
        options: [
          { label: "Gold/Green", value: "gold" },
          { label: "Silver/Blue", value: "silver" },
          { label: "Matte Black/Grey", value: "black" },
        ],
      },
    ],
    specifications: [
      { label: "Lens", value: "Polarized" },
      { label: "Protection", value: "UV400" },
      { label: "Frame", value: "Titanium" },
      { label: "Weight", value: "28g" },
      { label: "Includes", value: "Case, Cloth" },
    ],
    reviews: [],
  },
  {
    id: "19",
    slug: "mechanical-keyboard",
    title: "Mechanical Keyboard",
    description:
      "Hot-swappable mechanical keyboard with RGB backlighting and PBT keycaps. Gasket mount for a premium typing experience.",
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.7,
    reviewCount: 892,
    category: "Electronics",
    tags: ["Mechanical", "RGB", "Hot-Swappable"],
    images: [
      "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&q=80",
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80",
    ],
    stock: 19,
    badge: "Sale",
    sold: 1234,
    viewers: 234,
    shipping: { freeShipping: true, estimatedDays: 3 },
    variants: [
      {
        type: "color",
        name: "Color",
        options: [
          { label: "White", value: "white" },
          { label: "Black", value: "black" },
          { label: "Grey", value: "grey" },
        ],
      },
      {
        type: "style",
        name: "Switch",
        options: [
          { label: "Cherry MX Red", value: "red" },
          { label: "Cherry MX Brown", value: "brown" },
          { label: "Cherry MX Blue", value: "blue" },
        ],
      },
    ],
    specifications: [
      { label: "Layout", value: "75%" },
      { label: "Mount", value: "Gasket" },
      { label: "Keycaps", value: "PBT Double-shot" },
      { label: "Backlight", value: "Per-key RGB" },
      { label: "Hot-Swap", value: "Yes (5-pin)" },
      { label: "Connectivity", value: "USB-C, Bluetooth" },
    ],
    reviews: [],
  },
  {
    id: "20",
    slug: "travel-journal-leather",
    title: "Leather Travel Journal",
    description:
      "Premium leather-bound journal with 200 pages of acid-free paper and expandable pocket. Lay-flat binding for easy writing.",
    price: 34.99,
    rating: 4.8,
    reviewCount: 456,
    category: "Books",
    tags: ["Journal", "Travel", "Leather"],
    images: [
      "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&q=80",
      "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80",
    ],
    stock: 38,
    sold: 678,
    viewers: 23,
    shipping: { freeShipping: true, estimatedDays: 4 },
    specifications: [
      { label: "Material", value: "Full-Grain Leather" },
      { label: "Pages", value: "200" },
      { label: "Paper", value: "100gsm Acid-Free" },
      { label: "Binding", value: "Lay-flat" },
      { label: "Extras", value: "Expandable pocket" },
    ],
    reviews: [],
  },
];
