export const SIDEBAR_SOURCE = [
  '"use client";',
  '',
  'import { useState } from "react";',
  'import { cn } from "@/lib/cn";',
  '',
  'type SidebarSide = "left" | "right";',
  '',
  'interface SidebarProps {',
  '  children?: React.ReactNode;',
  '  side?: SidebarSide;',
  '  width?: number;',
  '  collapsed?: boolean;',
  '  onCollapsedChange?: (collapsed: boolean) => void;',
  '  className?: string;',
  '}',
  '',
  'interface SidebarHeaderProps {',
  '  children?: React.ReactNode;',
  '  className?: string;',
  '}',
  '',
  'interface SidebarContentProps {',
  '  children?: React.ReactNode;',
  '  className?: string;',
  '}',
  '',
  'interface SidebarFooterProps {',
  '  children?: React.ReactNode;',
  '  className?: string;',
  '}',
  '',
  'interface SidebarItemProps {',
  '  children?: React.ReactNode;',
  '  active?: boolean;',
  '  disabled?: boolean;',
  '  onClick?: () => void;',
  '  className?: string;',
  '}',
  '',
  'interface SidebarGroupProps {',
  '  label?: string;',
  '  children?: React.ReactNode;',
  '  className?: string;',
  '}',
  '',
  'interface SidebarTriggerProps {',
  '  className?: string;',
  '}',
  '',
  '// Context (simplified for source display)',
  'const SidebarCtx = React.createContext({',
  '  collapsed: false, setCollapsed: () => {}, side: "left" as SidebarSide,',
  '});',
  '',
  'export function Sidebar({',
  '  children, side = "left", width = 256,',
  '  collapsed: controlled, onCollapsedChange, className',
  '}: SidebarProps) {',
  '  const [internal, setInternal] = useState(false);',
  '  const collapsed = controlled ?? internal;',
  '  const setCollapsed = onCollapsedChange ?? setInternal;',
  '',
  '  return (',
  '    <SidebarCtx.Provider value={{ collapsed, setCollapsed, side }}>',
  '      <aside',
  '        role="navigation"',
  '        aria-label="Sidebar"',
  '        className={cn(',
  '          "flex h-full flex-col border-r border-border/60 bg-background text-foreground",',
  '          "transition-[width] duration-200 ease-in-out",',
  '          side === "right" && "border-l border-r-0",',
  '          collapsed ? "w-16" : "w-[var(--sb-w)]",',
  '          className',
  '        )}',
  '        style={{ "--sb-w": `${width}px` }}',
  '      >',
  '        {children}',
  '      </aside>',
  '    </SidebarCtx.Provider>',
  '  );',
  '}',
  '',
  'export function SidebarHeader({ children, className }: SidebarHeaderProps) {',
  '  const { collapsed } = React.useContext(SidebarCtx);',
  '  return (',
  '    <div className={cn(',
  '      "flex items-center border-b border-border/60 px-3 py-3 transition-all duration-200",',
  '      collapsed ? "justify-center px-2" : "gap-3",',
  '      className',
  '    )}>',
  '      {children}',
  '    </div>',
  '  );',
  '}',
  '',
  'export function SidebarContent({ children, className }: SidebarContentProps) {',
  '  return <div className={cn("flex-1 overflow-y-auto px-2 py-2", className)}>{children}</div>;',
  '}',
  '',
  'export function SidebarFooter({ children, className }: SidebarFooterProps) {',
  '  return <div className={cn("border-t border-border/60 px-3 py-3", className)}>{children}</div>;',
  '}',
  '',
  'export function SidebarItem({ children, active, disabled, onClick, className }: SidebarItemProps) {',
  '  return (',
  '    <button',
  '      type="button"',
  '      onClick={onClick}',
  '      disabled={disabled}',
  '      className={cn(',
  '        "flex w-full items-center gap-2 rounded-lg px-2.5 py-1.5 text-sm font-medium outline-none",',
  '        "transition-all duration-150",',
  '        "hover:bg-muted/60 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1",',
  '        "active:bg-muted/80 disabled:pointer-events-none disabled:opacity-50",',
  '        active && "bg-primary/10 text-primary hover:bg-primary/15",',
  '        !active && "text-muted-foreground",',
  '        className',
  '      )}',
  '    >',
  '      {children}',
  '    </button>',
  '  );',
  '}',
  '',
  'export function SidebarGroup({ label, children, className }: SidebarGroupProps) {',
  '  return (',
  '    <div className={cn("flex flex-col gap-0.5", className)}>',
  '      {label && <span className="px-2.5 pb-1 pt-2 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground/70">{label}</span>}',
  '      {children}',
  '    </div>',
  '  );',
  '}',
  '',
  'export function SidebarTrigger({ className }: SidebarTriggerProps) {',
  '  const { collapsed, setCollapsed } = React.useContext(SidebarCtx);',
  '  return (',
  '    <button',
  '      type="button"',
  '      onClick={() => setCollapsed(!collapsed)}',
  '      className={cn(',
  '        "flex h-8 w-8 items-center justify-center rounded-lg text-muted-foreground",',
  '        "hover:bg-muted/60 hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring",',
  '        "active:bg-muted/80",',
  '        className',
  '      )}',
  '    >',
  '      <svg className={cn("transition-transform duration-200", collapsed && "rotate-180")}',
  '        xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"',
  '        fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">',
  '        <path d="m11 17-5-5 5-5" /><path d="m18 17-5-5 5-5" />',
  '      </svg>',
  '    </button>',
  '  );',
  '}',
].join('\n');
