export const PAGINATION_BAR_SOURCE = [
  'import { useState, useMemo } from "react";',
  'import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from "lucide-react";',
  '',
  'type Variant = "default" | "pill" | "outline";',
  'type Size = "sm" | "md" | "lg";',
  '',
  'const isPill = (v: string) => v === "pill";',
  'const isOutline = (v: string) => v === "outline";',
  'const btnClass = (v: string, s: string) =>',
  '  `${isPill(v) ? "rounded-full" : "rounded-md"}` +',
  '  ` ${s === "sm" ? "h-8 min-w-[32px] text-xs" : s === "lg" ? "h-11 min-w-[44px] text-base" : "h-9 min-w-[36px] text-sm"}`;',
  'const navClass = (s: string) => s === "sm" ? "h-8 text-xs" : s === "lg" ? "h-11 text-base" : "h-9 text-sm";',
  'const activeClass = (v: string) =>',
  '  isOutline(v)',
  '    ? "border-primary text-primary bg-primary/10"',
  '    : "bg-foreground text-background dark:bg-muted dark:text-zinc-900";',
  '',
  'export interface PaginationBarProps {',
  '  current: number;',
  '  total: number;',
  '  onChange: (p: number) => void;',
  '  variant?: Variant;',
  '  size?: Size;',
  '  showFirstLast?: boolean;',
  '  showInfo?: boolean;',
  '}',
  '',
  'export function PaginationBar({',
  '  current, total, onChange, variant = "default", size = "md",',
  '  showFirstLast = true, showInfo,',
  '}: PaginationBarProps) {',
  '  const pages = useMemo(() => {',
  '    const p: (number | "...")[] = [];',
  '    const delta = 1;',
  '    const s = Math.max(2, current - delta);',
  '    const e = Math.min(total - 1, current + delta);',
  '    p.push(1);',
  '    if (s > 2) p.push("...");',
  '    for (let i = s; i <= e; i++) p.push(i);',
  '    if (e < total - 1) p.push("...");',
  '    if (total > 1) p.push(total);',
  '    return p;',
  '  }, [current, total]);',
  '',
  '  return (',
  '    <div className="flex min-w-0 max-w-full items-center gap-1 overflow-x-auto pb-1">',
  '      {showInfo && (',
  '        <span className="mr-2 whitespace-nowrap text-xs text-muted-foreground">',
  '          Page {current} of {total}',
  '        </span>',
  '      )}',
  '      {showFirstLast && (',
  '        <button onClick={() => onChange(1)} disabled={current === 1}',
  '          className={`${btnClass(variant, size)} flex items-center justify-center border border-border disabled:opacity-40`}>',
  '          <ChevronsLeft className="h-4 w-4" />',
  '        </button>',
  '      )}',
  '      <button onClick={() => onChange(Math.max(1, current - 1))} disabled={current === 1}',
  '        className={`${btnClass(variant, navClass(size))} flex items-center gap-1 border border-border px-2 disabled:opacity-40`}>',
  '        <ChevronLeft className="h-4 w-4" />',
  '        <span className="hidden sm:inline">Prev</span>',
  '      </button>',
  '      <div className="flex items-center gap-1">',
  '        {pages.map((page, i) =>',
  '          page === "..." ? (',
  '            <span key={`e${i}`}',
  '              className={`flex ${btnClass(variant, size)} items-center justify-center text-sm text-muted-foreground/70`}>',
  '              ...',
  '            </span>',
  '          ) : (',
  '            <button key={page} onClick={() => onChange(page)}',
  '              className={`${btnClass(variant, size)} flex items-center justify-center border px-2 ${page === current ? activeClass(variant) : "border-border hover:bg-muted"}`}>',
  '              {page}',
  '            </button>',
  '          )',
  '        )}',
  '      </div>',
  '      <button onClick={() => onChange(Math.min(total, current + 1))}',
  '        disabled={current === total}',
  '        className={`${navClass(size)} flex items-center gap-1 border border-border px-2 disabled:opacity-40`}>',
  '        <span className="hidden sm:inline">Next</span>',
  '        <ChevronRight className="h-4 w-4" />',
  '      </button>',
  '      {showFirstLast && (',
  '        <button onClick={() => onChange(total)} disabled={current === total}',
  '          className={`${btnClass(variant, size)} flex items-center justify-center border border-border disabled:opacity-40`}>',
  '          <ChevronsRight className="h-4 w-4" />',
  '        </button>',
  '      )}',
  '    </div>',
  '  );',
  '}',
].join('\n');
