import type { ApiEndpoint } from "@/components/ui";

export const demoEndpoints: ApiEndpoint[] = [
  {
    id: "auth-login",
    method: "POST",
    path: "/auth/login",
    title: "Sign in with credentials",
    group: "Auth",
    tags: ["login", "session", "token"],
    delay: 600,
    requestBody: { email: "ada@example.com", password: "hunter2" },
    response: {
      status: 200,
      headers: { "Content-Type": "application/json", "Set-Cookie": "session=…; HttpOnly" },
      body: {
        token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzQyIiwicm9sZSI6ImFkbWluIn0.example",
        user: { id: "user_42", name: "Ada Lovelace", email: "ada@example.com", role: "admin" },
        expiresIn: 3600,
      },
    },
  },
  {
    id: "auth-refresh",
    method: "POST",
    path: "/auth/refresh",
    title: "Refresh access token",
    group: "Auth",
    tags: ["token", "session"],
    requiresAuth: true,
    delay: 400,
    requestBody: { refreshToken: "rt_…" },
    response: {
      status: 200,
      headers: { "Content-Type": "application/json" },
      body: { token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.new-token", expiresIn: 3600 },
    },
  },
  {
    id: "auth-logout",
    method: "POST",
    path: "/auth/logout",
    title: "End the session",
    group: "Auth",
    tags: ["logout", "session"],
    requiresAuth: true,
    delay: 300,
    response: { status: 204, body: null },
  },

  {
    id: "users-list",
    method: "GET",
    path: "/users",
    title: "List all users",
    group: "Users",
    tags: ["list", "paginate"],
    query: [
      { key: "limit", value: "10", description: "Max results (default 10)" },
      { key: "offset", value: "0", description: "Pagination offset" },
      { key: "role", value: "", description: "Filter by role" },
    ],
    response: {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "X-Total-Count": "42",
        "Cache-Control": "max-age=60",
      },
      body: {
        data: [
          { id: "user_1", name: "Ada Lovelace", email: "ada@example.com", role: "admin" },
          { id: "user_2", name: "Alan Turing", email: "alan@example.com", role: "engineer" },
          { id: "user_3", name: "Grace Hopper", email: "grace@example.com", role: "engineer" },
        ],
        pagination: { limit: 10, offset: 0, total: 42 },
      },
    },
  },
  {
    id: "users-get",
    method: "GET",
    path: "/users/:id",
    title: "Get a single user",
    group: "Users",
    tags: ["read", "detail"],
    requiresAuth: true,
    params: [{ key: "id", value: "user_1" }],
    response: {
      status: 200,
      headers: { "Content-Type": "application/json" },
      body: {
        id: "user_1",
        name: "Ada Lovelace",
        email: "ada@example.com",
        role: "admin",
        createdAt: "2024-03-14T09:00:00Z",
      },
    },
  },
  {
    id: "users-create",
    method: "POST",
    path: "/users",
    title: "Create a user",
    group: "Users",
    tags: ["create"],
    requiresAuth: true,
    delay: 550,
    requestBody: { name: "New User", email: "new@example.com", role: "engineer" },
    response: {
      status: 201,
      headers: { "Content-Type": "application/json", Location: "/v1/users/user_44" },
      body: { id: "user_44", name: "New User", email: "new@example.com", role: "engineer" },
    },
  },
  {
    id: "users-update",
    method: "PATCH",
    path: "/users/:id",
    title: "Update a user",
    group: "Users",
    tags: ["update"],
    requiresAuth: true,
    params: [{ key: "id", value: "user_1" }],
    requestBody: { role: "owner", name: "Ada Lovelace" },
    response: {
      status: 200,
      headers: { "Content-Type": "application/json" },
      body: { id: "user_1", name: "Ada Lovelace", role: "owner", updatedAt: "2026-07-31T10:15:00Z" },
    },
  },
  {
    id: "users-delete",
    method: "DELETE",
    path: "/users/:id",
    title: "Delete a user",
    group: "Users",
    tags: ["delete", "destroy"],
    requiresAuth: true,
    params: [{ key: "id", value: "user_3" }],
    delay: 350,
    response: { status: 200, body: { ok: true, deleted: "user_3" } },
  },

  {
    id: "files-list",
    method: "GET",
    path: "/files",
    title: "List uploaded files",
    group: "Files",
    tags: ["list", "media"],
    requiresAuth: true,
    query: [{ key: "type", value: "", description: "Filter by MIME type" }],
    response: {
      status: 200,
      headers: { "Content-Type": "application/json", "X-Total-Count": "7" },
      body: {
        data: [
          { id: "file_1", name: "logo.svg", type: "image/svg+xml", size: 4096 },
          { id: "file_2", name: "report.pdf", type: "application/pdf", size: 248_576 },
        ],
      },
    },
  },
  {
    id: "files-get",
    method: "GET",
    path: "/files/:id",
    title: "Get file metadata",
    group: "Files",
    tags: ["read", "missing"],
    requiresAuth: true,
    params: [{ key: "id", value: "file_999" }],
    response: {
      status: 404,
      headers: { "Content-Type": "application/json" },
      body: {
        error: "not_found",
        message: "File file_999 does not exist",
        requestId: "req_abc123",
      },
    },
  },
  {
    id: "files-upload",
    method: "POST",
    path: "/files/upload",
    title: "Upload a file",
    group: "Files",
    tags: ["upload", "media"],
    requiresAuth: true,
    delay: 900,
    response: {
      status: 201,
      headers: { "Content-Type": "application/json" },
      body: { id: "file_8", name: "screenshot.png", url: "https://cdn.example.com/file_8" },
    },
  },

  {
    id: "system-health",
    method: "GET",
    path: "/health",
    title: "Service health check",
    group: "System",
    tags: ["health", "status"],
    delay: 200,
    response: {
      status: 200,
      headers: { "Content-Type": "application/json" },
      body: { status: "ok", uptime: 48231, version: "2.4.1", region: "eu-west-1" },
    },
  },
  {
    id: "system-stats",
    method: "GET",
    path: "/stats",
    title: "Usage statistics",
    group: "System",
    tags: ["stats", "metrics"],
    requiresAuth: true,
    delay: 700,
    response: {
      status: 500,
      headers: { "Content-Type": "application/json" },
      body: {
        error: "internal_error",
        message: "Could not aggregate metrics (timeout on downstream analytics)",
        requestId: "req_xyz789",
      },
    },
  },
];

export const publicEndpoints: ApiEndpoint[] = [
  {
    id: "health",
    method: "GET",
    path: "/health",
    title: "Service health check",
    group: "System",
    delay: 200,
    response: {
      status: 200,
      body: { status: "ok", uptime: 48231, version: "2.4.1" },
    },
  },
  {
    id: "docs",
    method: "GET",
    path: "/docs",
    title: "API documentation",
    group: "System",
    delay: 250,
    response: {
      status: 200,
      headers: { "Content-Type": "text/plain" },
      body: "Welcome to the API. See /v1/users for resources.",
    },
  },
  {
    id: "public-users",
    method: "GET",
    path: "/users",
    title: "List public users",
    group: "Users",
    query: [{ key: "limit", value: "5" }],
    response: {
      status: 200,
      body: {
        data: [
          { id: "user_1", name: "Ada Lovelace" },
          { id: "user_2", name: "Alan Turing" },
        ],
      },
    },
  },
  {
    id: "public-version",
    method: "GET",
    path: "/version",
    title: "API version",
    group: "System",
    delay: 150,
    response: { status: 200, body: { api: "v1", build: "2026.07.1", env: "production" } },
  },
];
