export const STACK_SOURCE = [
  '"use client";',
  '',
  'import { Children, Fragment, forwardRef } from "react";',
  'import { cn } from "@/lib/cn";',
  '',
  'type StackDirection = "vertical" | "horizontal";',
  'type StackAlign = "start" | "center" | "end" | "stretch";',
  'type StackJustify = "start" | "center" | "end" | "between" | "around" | "evenly";',
  '',
  'interface StackProps {',
  '  direction?: StackDirection; gap?: number; align?: StackAlign;',
  '  justify?: StackJustify; wrap?: boolean; separator?: React.ReactNode;',
  '  className?: string; children: React.ReactNode;',
  '}',
  '',
  'interface InlineProps {',
  '  gap?: number; align?: StackAlign; justify?: StackJustify;',
  '  wrap?: boolean; className?: string; children: React.ReactNode;',
  '}',
  '',
  'const ALIGN_MAP: Record<StackAlign, string> = {',
  '  start: "items-start", center: "items-center", end: "items-end", stretch: "items-stretch",',
  '};',
  'const JUSTIFY_MAP: Record<StackJustify, string> = {',
  '  start: "justify-start", center: "justify-center", end: "justify-end",',
  '  between: "justify-between", around: "justify-around", evenly: "justify-evenly",',
  '};',
  '',
  'const Stack = forwardRef<HTMLDivElement, StackProps>(({',
  '  direction = "vertical", gap = 4, align, justify, wrap = false, separator, className, children',
  '}, ref) => {',
  '  const isVertical = direction === "vertical";',
  '  const items = Children.toArray(children);',
  '  const separated = separator',
  '    ? items.reduce<React.ReactNode[]>((acc, child, i) => {',
  '        if (i > 0) acc.push(<Fragment key={`sep-${i}`}>{separator}</Fragment>);',
  '        acc.push(child); return acc;',
  '      }, [])',
  '    : items;',
  '',
  '  return (',
  '    <div ref={ref} role="group"',
  '      className={cn("flex", isVertical ? "flex-col" : "flex-row",',
  '        `gap-${gap}`, align && ALIGN_MAP[align], justify && JUSTIFY_MAP[justify],',
  '        wrap && "flex-wrap", className)}>',
  '      {separated}',
  '    </div>',
  '  );',
  '});',
  'Stack.displayName = "Stack";',
  '',
  'const Inline = forwardRef<HTMLDivElement, InlineProps>(({',
  '  gap = 3, align, justify, wrap = false, className, children',
  '}, ref) => (',
  '  <div ref={ref} role="group"',
  '    className={cn("flex flex-row", `gap-${gap}`,',
  '      align && ALIGN_MAP[align], justify && JUSTIFY_MAP[justify],',
  '      wrap && "flex-wrap", className)}>',
  '    {children}',
  '  </div>',
  '));',
  'Inline.displayName = "Inline";',
  '',
  'export { Stack, Inline };',
].join('\n');
