"use client";

export {
  X as CloseIcon,
  Menu,
  Menu as MenuIcon,
  Search,
  Search as SearchIcon,
  Sun,
  Sun as SunIcon,
  Moon,
  Moon as MoonIcon,
  Copy,
  Copy as CopyIcon,
  RefreshCw as RegenerateIcon,
  Pencil as EditIcon,
  Trash2 as TrashIcon,
  ThumbsUp,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown,
  ThumbsDown as ThumbsDownIcon,
  Paperclip,
  Paperclip as PaperclipIcon,
  Image,
  Image as ImageIcon,
  Mic,
  Mic as MicIcon,
} from "lucide-react";
