import type { CanvasNode } from "../../types/canvas";

interface ExtractedUtility {
  name: string;
  type: "function" | "constant" | "mixin";
  code: string;
  usageCount: number;
}

function findRepeatedPatterns(nodes: Record<string, CanvasNode>): Map<string, number> {
  const patterns = new Map<string, number>();

  for (const node of Object.values(nodes)) {
    const classes = Object.values(node.props)
      .filter((v) => typeof v === "string" && v.includes(" "))
      .map(String);

    for (const cls of classes) {
      patterns.set(cls, (patterns.get(cls) ?? 0) + 1);
    }
  }

  return patterns;
}

function extractColorConstants(nodes: Record<string, CanvasNode>): string[] {
  const colors = new Set<string>();

  for (const node of Object.values(nodes)) {
    const { background, typography } = node.visual;
    if (background.color) colors.add(background.color);
    if (typography.color) colors.add(typography.color);
    if (typeof node.props.backgroundColor === "string") colors.add(node.props.backgroundColor);
    if (typeof node.props.color === "string") colors.add(node.props.color);
  }

  return Array.from(colors).filter((c) => c.startsWith("#"));
}

function extractSpacingValues(nodes: Record<string, CanvasNode>): number[] {
  const values = new Set<number>();

  for (const node of Object.values(nodes)) {
    const { padding, margin } = node.visual;
    if (padding.top) values.add(padding.top);
    if (padding.right) values.add(padding.right);
    if (padding.bottom) values.add(padding.bottom);
    if (padding.left) values.add(padding.left);
    if (margin.top) values.add(margin.top);
    if (margin.right) values.add(margin.right);
    if (margin.bottom) values.add(margin.bottom);
    if (margin.left) values.add(margin.left);
  }

  return Array.from(values).filter((v) => v > 0);
}

export function extractUtilities(nodes: Record<string, CanvasNode>): ExtractedUtility[] {
  const utilities: ExtractedUtility[] = [];
  const colors = extractColorConstants(nodes);
  const spacing = extractSpacingValues(nodes);

  if (colors.length > 0) {
    utilities.push({
      name: "colors",
      type: "constant",
      code: `export const colors = {\n${colors.map((c) => `  "${c}": "${c}",`).join("\n")}\n} as const;`,
      usageCount: colors.length,
    });
  }

  if (spacing.length > 0) {
    utilities.push({
      name: "spacing",
      type: "constant",
      code: `export const spacing = {\n${spacing.map((v) => `  ${v}: "${v}px",`).join("\n")}\n} as const;`,
      usageCount: spacing.length,
    });
  }

  utilities.push({
    name: "cn",
    type: "function",
    code: `export function cn(...classes: (string | undefined | null | false)[]): string {
  return classes.filter(Boolean).join(" ");
}`,
    usageCount: 1,
  });

  return utilities;
}

export function formatUtilities(utilities: ExtractedUtility[]): string {
  const lines: string[] = [
    "// Auto-generated utility functions and constants",
    "// Generated by Visual Component Studio",
    "",
  ];

  for (const util of utilities) {
    lines.push(`// ${util.type}: ${util.name} (used ${util.usageCount}x)`);
    lines.push(util.code);
    lines.push("");
  }

  return lines.join("\n");
}
