import type { Company, CompanyReview, Application, Recruiter } from "../types";

export const COMPANIES: Company[] = [
  {
    name: "Google",
    logo: "https://logo.clearbit.com/google.com",
    coverImage: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=800&h=300&fit=crop",
    openRoles: 247,
    rating: 4.6,
    size: "180,000+",
    industry: "Technology",
    founded: "1998",
    headquarters: "Mountain View, CA",
  },
  {
    name: "Stripe",
    logo: "https://logo.clearbit.com/stripe.com",
    coverImage: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=300&fit=crop",
    openRoles: 89,
    rating: 4.7,
    size: "8,000+",
    industry: "FinTech",
    founded: "2010",
    headquarters: "San Francisco, CA",
  },
  {
    name: "Netflix",
    logo: "https://logo.clearbit.com/netflix.com",
    coverImage: "https://images.unsplash.com/photo-1574375927938-d5a98e8d7e28?w=800&h=300&fit=crop",
    openRoles: 64,
    rating: 4.5,
    size: "13,000+",
    industry: "Entertainment",
    founded: "1997",
    headquarters: "Los Gatos, CA",
  },
  {
    name: "Figma",
    logo: "https://logo.clearbit.com/figma.com",
    coverImage: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=300&fit=crop",
    openRoles: 32,
    rating: 4.8,
    size: "1,500+",
    industry: "Design Tools",
    founded: "2012",
    headquarters: "San Francisco, CA",
  },
  {
    name: "Notion",
    logo: "https://logo.clearbit.com/notion.so",
    coverImage: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&h=300&fit=crop",
    openRoles: 41,
    rating: 4.5,
    size: "800+",
    industry: "Productivity",
    founded: "2013",
    headquarters: "San Francisco, CA",
  },
  {
    name: "OpenAI",
    logo: "https://logo.clearbit.com/openai.com",
    coverImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=300&fit=crop",
    openRoles: 78,
    rating: 4.4,
    size: "3,000+",
    industry: "Artificial Intelligence",
    founded: "2015",
    headquarters: "San Francisco, CA",
  },
];

export const COMPANY_REVIEWS: CompanyReview[] = [
  {
    company: "Google",
    companyLogo: "https://logo.clearbit.com/google.com",
    rating: 4.6,
    text: "World-class engineering culture with resources to work on truly impactful problems. The scale of systems here is unmatched — you'll ship code used by billions. Benefits are exceptional and work-life balance is genuinely respected.",
    role: "Senior Software Engineer",
    date: "March 2026",
    pros: "Unmatched technical scale, brilliant colleagues, industry-leading benefits, strong internal mobility",
    cons: "Large organization can slow decision-making, promo process can be competitive",
  },
  {
    company: "Stripe",
    companyLogo: "https://logo.clearbit.com/stripe.com",
    rating: 4.7,
    text: "Incredible product-market fit with a culture that genuinely values engineering excellence. Every detail matters here — from API design to developer documentation. The density of talent is remarkable.",
    role: "Staff Engineer",
    date: "January 2026",
    pros: "Engineering-first culture, elegant products, high autonomy, transparent leadership",
    cons: "High bar means constant pressure to perform, fast-paced environment",
  },
  {
    company: "Figma",
    companyLogo: "https://logo.clearbit.com/figma.com",
    rating: 4.8,
    text: "The most collaborative and design-forward company I've experienced. Product decisions are thoughtful and user-centric. The team is exceptionally talented and the culture is warm and inclusive.",
    role: "Product Designer",
    date: "February 2026",
    pros: "Incredible design culture, collaborative team, impactful product, great growth opportunities",
    cons: "Acquisition uncertainty, small team means wearing many hats",
  },
];

export const APPLICATIONS: Application[] = [
  {
    id: 1,
    title: "Senior Frontend Engineer",
    company: "Google",
    companyLogo: "https://logo.clearbit.com/google.com",
    status: "Interview",
    stage: "Technical Screen — Round 2 of 4",
    date: "Aug 12, 2026",
  },
  {
    id: 2,
    title: "Staff Product Designer",
    company: "Stripe",
    companyLogo: "https://logo.clearbit.com/stripe.com",
    status: "Applied",
    stage: "Application Under Review",
    date: "Aug 18, 2026",
  },
  {
    id: 3,
    title: "Machine Learning Engineer",
    company: "OpenAI",
    companyLogo: "https://logo.clearbit.com/openai.com",
    status: "Rejected",
    stage: "Position Filled",
    date: "Jul 24, 2026",
  },
  {
    id: 4,
    title: "Senior Backend Engineer",
    company: "Stripe",
    companyLogo: "https://logo.clearbit.com/stripe.com",
    status: "Offer",
    stage: "Offer Extended — Reviewing",
    date: "Aug 5, 2026",
  },
];

export const RECRUITER: Recruiter = {
  name: "Sarah Chen",
  title: "Senior Technical Recruiter",
  company: "Google",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
  email: "sarah.chen@google.com",
  phone: "+1 (650) 555-0147",
};
