import type { SalaryInsight, CareerPathNode, JobMarketReport, CompanyDirectoryEntry } from "../types";

export const SALARY_INSIGHTS: SalaryInsight[] = [
  {
    title: "Senior Frontend Engineer",
    location: "San Francisco, CA",
    median: 185000,
    p25: 155000,
    p75: 215000,
    p90: 260000,
    growth: 8.2,
    openRoles: 342,
  },
  {
    title: "Senior Backend Engineer",
    location: "San Francisco, CA",
    median: 190000,
    p25: 160000,
    p75: 225000,
    p90: 275000,
    growth: 7.5,
    openRoles: 289,
  },
  {
    title: "Product Designer",
    location: "New York, NY",
    median: 145000,
    p25: 120000,
    p75: 175000,
    p90: 210000,
    growth: 6.1,
    openRoles: 178,
  },
  {
    title: "Machine Learning Engineer",
    location: "San Francisco, CA",
    median: 210000,
    p25: 175000,
    p75: 255000,
    p90: 320000,
    growth: 12.4,
    openRoles: 156,
  },
  {
    title: "Product Manager",
    location: "Remote",
    median: 155000,
    p25: 130000,
    p75: 185000,
    p90: 225000,
    growth: 5.8,
    openRoles: 234,
  },
  {
    title: "DevOps Engineer",
    location: "Austin, TX",
    median: 150000,
    p25: 125000,
    p75: 180000,
    p90: 215000,
    growth: 9.3,
    openRoles: 198,
  },
];

export const SALARY_RANGES = [
  { label: "Under $50k", min: 0, max: 50000 },
  { label: "$50k - $100k", min: 50000, max: 100000 },
  { label: "$100k - $150k", min: 100000, max: 150000 },
  { label: "$150k - $200k", min: 150000, max: 200000 },
  { label: "$200k - $250k", min: 200000, max: 250000 },
  { label: "$250k+", min: 250000, max: Infinity },
] as const;

export const INTERVIEW_QUESTIONS = [
  {
    id: 1,
    category: "Technical",
    question: "Explain the difference between `==` and `===` in JavaScript. When would you use each?",
    difficulty: "Easy" as const,
    tips: "Discuss type coercion, loose vs strict equality, and when implicit conversion can cause bugs.",
    timeLimit: "5 min",
  },
  {
    id: 2,
    category: "Technical",
    question: "How would you design a real-time chat application? Walk through the architecture.",
    difficulty: "Hard" as const,
    tips: "Cover WebSocket connections, message queuing, database design, scaling considerations, and offline support.",
    timeLimit: "15 min",
  },
  {
    id: 3,
    category: "Behavioral",
    question: "Tell me about a time you had to make a difficult technical decision under pressure.",
    difficulty: "Medium" as const,
    tips: "Use the STAR method. Focus on your thought process, trade-offs considered, and the outcome.",
    timeLimit: "5 min",
  },
  {
    id: 4,
    category: "Technical",
    question: "What are React Server Components and how do they differ from Client Components?",
    difficulty: "Medium" as const,
    tips: "Explain server-side rendering, streaming, the boundary between server and client, and performance benefits.",
    timeLimit: "8 min",
  },
  {
    id: 5,
    category: "System Design",
    question: "Design a URL shortener like bit.ly. How would you handle billions of URLs?",
    difficulty: "Hard" as const,
    tips: "Cover hash generation strategies, database sharding, caching layers, analytics, and rate limiting.",
    timeLimit: "20 min",
  },
  {
    id: 6,
    category: "Behavioral",
    question: "Describe a project where you had to collaborate with non-technical stakeholders.",
    difficulty: "Medium" as const,
    tips: "Highlight communication skills, translating technical concepts, and building consensus.",
    timeLimit: "5 min",
  },
  {
    id: 7,
    category: "Technical",
    question: "Explain database indexing. When would you add an index and what are the trade-offs?",
    difficulty: "Medium" as const,
    tips: "Discuss B-tree indexes, composite indexes, write performance impact, and query plan analysis.",
    timeLimit: "8 min",
  },
  {
    id: 8,
    category: "System Design",
    question: "How would you implement a notification system that supports email, SMS, and push?",
    difficulty: "Hard" as const,
    tips: "Cover event-driven architecture, queue management, delivery guarantees, user preferences, and retry logic.",
    timeLimit: "15 min",
  },
];

export const COMPANY_INSIGHTS_DATA = [
  {
    name: "Google",
    logo: "https://logo.clearbit.com/google.com",
    workLifeBalance: 4.2,
    compensation: 4.8,
    culture: 4.5,
    careerGrowth: 4.3,
    diversity: 4.1,
    recommendToFriend: 87,
    totalReviews: 15420,
    ceo: "Sundar Pichai",
    ceoApproval: 82,
    pros: [
      "World-class benefits and compensation",
      "Brilliant, collaborative colleagues",
      "Impact at massive scale",
      "Strong internal mobility",
    ],
    cons: [
      "Large organization can slow decisions",
      "Bureaucracy in some teams",
      "Work-life balance varies by team",
    ],
  },
  {
    name: "Stripe",
    logo: "https://logo.clearbit.com/stripe.com",
    workLifeBalance: 4.4,
    compensation: 4.7,
    culture: 4.8,
    careerGrowth: 4.5,
    diversity: 4.0,
    recommendToFriend: 92,
    totalReviews: 3200,
    ceo: "Patrick Collison",
    ceoApproval: 95,
    pros: [
      "Engineering-first culture",
      "Beautiful, well-crafted products",
      "High autonomy and trust",
      "Transparent leadership",
    ],
    cons: [
      "High performance bar",
      "Fast-paced environment",
      "Can be demanding during launches",
    ],
  },
  {
    name: "Figma",
    logo: "https://logo.clearbit.com/figma.com",
    workLifeBalance: 4.6,
    compensation: 4.5,
    culture: 4.9,
    careerGrowth: 4.2,
    diversity: 4.3,
    recommendToFriend: 94,
    totalReviews: 1800,
    ceo: "Dylan Field",
    ceoApproval: 97,
    pros: [
      "Incredible design culture",
      "Warm, inclusive team",
      "Meaningful, impactful product",
      "Great growth opportunities",
    ],
    cons: [
      "Small team means wearing many hats",
      "Startup intensity at scale",
      "Rapid growth brings challenges",
    ],
  },
  {
    name: "Netflix",
    logo: "https://logo.clearbit.com/netflix.com",
    workLifeBalance: 4.0,
    compensation: 4.9,
    culture: 4.3,
    careerGrowth: 4.1,
    diversity: 3.9,
    recommendToFriend: 81,
    totalReviews: 8500,
    ceo: "Ted Sarandos",
    ceoApproval: 78,
    pros: [
      "Top-of-market compensation",
      "Freedom and responsibility culture",
      "Impact on 200M+ subscribers",
      "No vacation policy",
    ],
    cons: [
      "Keeper test creates pressure",
      "High performance expectations",
      "Work-life balance challenges",
    ],
  },
];

export const TIPS_FOR_JOB_SEEKERS = [
  {
    title: "Optimize Your Resume for ATS",
    description: "Use keywords from the job description, keep formatting simple, and save as PDF.",
    category: "Resume",
  },
  {
    title: "Nail the Technical Screen",
    description: "Practice coding problems daily, think out loud, and ask clarifying questions.",
    category: "Interview",
  },
  {
    title: "Research the Company",
    description: "Read their blog, understand their product, and prepare thoughtful questions.",
    category: "Preparation",
  },
  {
    title: "Negotiate Your Offer",
    description: "Always negotiate. Research market rates and consider total compensation.",
    category: "Negotiation",
  },
  {
    title: "Build Your Network",
    description: "Connect with employees, attend events, and engage on professional platforms.",
    category: "Networking",
  },
  {
    title: "Prepare Your Portfolio",
    description: "Showcase 3-5 strong projects with clear case studies and impact metrics.",
    category: "Portfolio",
  },
];

export const CAREER_PATHS: CareerPathNode[] = [
  { id: 1, title: "Junior Developer", level: "Entry", salaryRange: "$60k - $85k", yearsExp: "0-2 years", skills: ["HTML/CSS", "JavaScript", "Git", "Basic React"], next: [2, 3] },
  { id: 2, title: "Mid-Level Developer", level: "Mid", salaryRange: "$90k - $130k", yearsExp: "2-5 years", skills: ["React", "TypeScript", "Node.js", "Testing"], next: [4, 5] },
  { id: 3, title: "Frontend Specialist", level: "Mid", salaryRange: "$95k - $140k", yearsExp: "2-5 years", skills: ["React", "Next.js", "Performance", "A11y"], next: [4, 5] },
  { id: 4, title: "Senior Developer", level: "Senior", salaryRange: "$140k - $200k", yearsExp: "5-8 years", skills: ["System Design", "Mentoring", "Architecture", "Cross-team"], next: [6, 7] },
  { id: 5, title: "Tech Lead", level: "Senior", salaryRange: "$150k - $220k", yearsExp: "5-8 years", skills: ["Leadership", "Planning", "Code Review", "Stakeholder Mgmt"], next: [6, 7] },
  { id: 6, title: "Staff Engineer", level: "Staff", salaryRange: "$180k - $280k", yearsExp: "8-12 years", skills: ["Technical Strategy", "Org-wide Impact", "Cross-org"], next: [8] },
  { id: 7, title: "Engineering Manager", level: "Manager", salaryRange: "$170k - $260k", yearsExp: "8-12 years", skills: ["People Management", "Hiring", "Team Building", "Roadmapping"], next: [8] },
  { id: 8, title: "Principal / Director", level: "Principal", salaryRange: "$250k - $400k+", yearsExp: "12+ years", skills: ["Executive Leadership", "Company Strategy", "Industry Vision"], next: [] },
];

export const JOB_MARKET_REPORTS: JobMarketReport[] = [
  { category: "Frontend Engineering", totalJobs: 12847, avgSalary: 165000, growth: 8.2, topSkills: ["React", "TypeScript", "Next.js", "Tailwind"], topCompanies: ["Google", "Meta", "Vercel", "Stripe"], demandLevel: "High" },
  { category: "Backend Engineering", totalJobs: 9823, avgSalary: 175000, growth: 7.1, topSkills: ["Go", "Python", "Kubernetes", "PostgreSQL"], topCompanies: ["Netflix", "AWS", "Databricks", "Cloudflare"], demandLevel: "High" },
  { category: "Data Science", totalJobs: 6541, avgSalary: 155000, growth: 11.3, topSkills: ["Python", "SQL", "ML", "TensorFlow"], topCompanies: ["OpenAI", "Meta", "Google", "Stripe"], demandLevel: "High" },
  { category: "Product Design", totalJobs: 4320, avgSalary: 140000, growth: 5.8, topSkills: ["Figma", "Prototyping", "User Research", "Design Systems"], topCompanies: ["Figma", "Airbnb", "Notion", "Linear"], demandLevel: "Medium" },
  { category: "DevOps / SRE", totalJobs: 5678, avgSalary: 160000, growth: 9.7, topSkills: ["AWS", "Terraform", "Docker", "CI/CD"], topCompanies: ["HashiCorp", "Datadog", "PagerDuty", "AWS"], demandLevel: "High" },
  { category: "Product Management", totalJobs: 7234, avgSalary: 150000, growth: 6.4, topSkills: ["Strategy", "Analytics", "Agile", "SQL"], topCompanies: ["Stripe", "Notion", "Figma", "Slack"], demandLevel: "Medium" },
];

export const COMPANY_DIRECTORY: CompanyDirectoryEntry[] = [
  { name: "Google", logo: "https://logo.clearbit.com/google.com", industry: "Technology", size: "180,000+", headquarters: "Mountain View, CA", openRoles: 247, rating: 4.6, founded: "1998", website: "google.com", description: "Organizing the world's information and making it universally accessible." },
  { name: "Stripe", logo: "https://logo.clearbit.com/stripe.com", industry: "FinTech", size: "8,000+", headquarters: "San Francisco, CA", openRoles: 89, rating: 4.7, founded: "2010", website: "stripe.com", description: "Financial infrastructure for the internet." },
  { name: "Figma", logo: "https://logo.clearbit.com/figma.com", industry: "Design Tools", size: "1,500+", headquarters: "San Francisco, CA", openRoles: 32, rating: 4.8, founded: "2012", website: "figma.com", description: "The leading collaborative design platform." },
  { name: "Netflix", logo: "https://logo.clearbit.com/netflix.com", industry: "Entertainment", size: "13,000+", headquarters: "Los Gatos, CA", openRoles: 64, rating: 4.5, founded: "1997", website: "netflix.com", description: "Entertainment streaming for 200M+ subscribers worldwide." },
  { name: "Notion", logo: "https://logo.clearbit.com/notion.so", industry: "Productivity", size: "800+", headquarters: "San Francisco, CA", openRoles: 41, rating: 4.5, founded: "2013", website: "notion.so", description: "The all-in-one workspace for your notes, tasks, and collaboration." },
  { name: "OpenAI", logo: "https://logo.clearbit.com/openai.com", industry: "Artificial Intelligence", size: "3,000+", headquarters: "San Francisco, CA", openRoles: 78, rating: 4.4, founded: "2015", website: "openai.com", description: "Creating safe AGI that benefits all of humanity." },
  { name: "Vercel", logo: "https://logo.clearbit.com/vercel.com", industry: "Developer Tools", size: "500+", headquarters: "San Francisco, CA", openRoles: 28, rating: 4.6, founded: "2015", website: "vercel.com", description: "Develop. Preview. Ship. The platform for frontend developers." },
  { name: "Databricks", logo: "https://logo.clearbit.com/databricks.com", industry: "Data & AI", size: "7,000+", headquarters: "San Francisco, CA", openRoles: 95, rating: 4.5, founded: "2013", website: "databricks.com", description: "The lakehouse company — unified analytics, AI, and data engineering." },
];

export const COVER_LETTER_TIPS = [
  { title: "Start with a Strong Opening", description: "Address the hiring manager by name if possible. State the position and why you're excited about it." },
  { title: "Show You've Done Your Research", description: "Reference specific company projects, values, or recent news that resonates with you." },
  { title: "Highlight Relevant Achievements", description: "Use metrics and specific examples. 'Improved performance by 40%' beats 'worked on optimization'." },
  { title: "Address the Skills Gap", description: "If you're missing some requirements, acknowledge it and show how you've learned similar skills." },
  { title: "Keep it Concise", description: "Aim for 3-4 paragraphs, max one page. Recruiters spend 30 seconds scanning cover letters." },
  { title: "End with a Call to Action", description: "Express enthusiasm for an interview and thank them for their consideration." },
];
