import type { FeaturedJob, Job, SimilarJob, RecommendedJob } from "../types";

export const FEATURED_JOBS: FeaturedJob[] = [
  { id: 1, title: "Senior Frontend Engineer", company: "Google", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "Mountain View, CA", salary: "$180k - $250k", type: "Full-Time", remote: true, urgent: true, gradient: "from-blue-600 to-blue-800" },
  { id: 2, title: "Product Designer", company: "Airbnb", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "San Francisco, CA", salary: "$150k - $200k", type: "Full-Time", remote: false, urgent: false, gradient: "from-rose-500 to-pink-600" },
  { id: 3, title: "DevOps Engineer", company: "Netflix", companyLogo: "https://images.unsplash.com/photo-1574375927938-d5a98e8d7e28?w=100&h=100&fit=crop", location: "Remote", salary: "$170k - $230k", type: "Contract", remote: true, urgent: true, gradient: "from-red-600 to-red-800" },
];

export const ALL_JOBS: Job[] = [
  { id: 4, title: "Backend Engineer", company: "Stripe", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "San Francisco, CA", salary: "$160k - $220k", salaryMin: 160, salaryMax: 220, type: "Full-Time", remote: true, urgent: false, skills: ["Go", "PostgreSQL", "Kubernetes"], posted: "2h ago", description: "Build and scale payment infrastructure serving millions of transactions daily.", benefits: ["Health insurance", "401k match", "Unlimited PTO", "Stock options"], experience: "Senior", category: "Engineering" },
  { id: 5, title: "UX Researcher", company: "Figma", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "New York, NY", salary: "$130k - $170k", salaryMin: 130, salaryMax: 170, type: "Full-Time", remote: false, urgent: false, skills: ["User Testing", "Figma", "Qualitative Research"], posted: "5h ago", description: "Lead user research initiatives to shape the future of design tools.", benefits: ["Health insurance", "Learning budget", "Flexible hours"], experience: "Mid", category: "Design" },
  { id: 6, title: "Marketing Lead", company: "Notion", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "New York, NY", salary: "$140k - $180k", salaryMin: 140, salaryMax: 180, type: "Full-Time", remote: true, urgent: false, skills: ["SEO", "Content Strategy", "Analytics"], posted: "1d ago", description: "Drive growth through innovative marketing campaigns and content strategies.", benefits: ["Health insurance", "Remote work", "Stock options"], experience: "Senior", category: "Marketing" },
  { id: 7, title: "Data Scientist", company: "OpenAI", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "San Francisco, CA", salary: "$200k - $300k", salaryMin: 200, salaryMax: 300, type: "Full-Time", remote: false, urgent: true, skills: ["Python", "ML", "TensorFlow", "PyTorch"], posted: "3d ago", description: "Research and develop cutting-edge AI models that push the boundaries of what's possible.", benefits: ["Top compensation", "Research budget", "Conference attendance"], experience: "Senior", category: "Data" },
  { id: 8, title: "iOS Developer", company: "Spotify", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "Stockholm, Sweden", salary: "$140k - $180k", salaryMin: 140, salaryMax: 180, type: "Full-Time", remote: true, urgent: false, skills: ["Swift", "UIKit", "SwiftUI"], posted: "1w ago", description: "Build the world's best music streaming experience for millions of users.", benefits: ["Health insurance", "Spotify Premium", "Flexible work"], experience: "Mid", category: "Engineering" },
  { id: 9, title: "Product Manager", company: "Slack", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "San Francisco, CA", salary: "$160k - $210k", salaryMin: 160, salaryMax: 210, type: "Full-Time", remote: true, urgent: false, skills: ["Product Strategy", "Agile", "Data Analysis"], posted: "2d ago", description: "Shape the future of team communication and collaboration.", benefits: ["Health insurance", "Stock options", "Parental leave"], experience: "Senior", category: "Product" },
  { id: 10, title: "Security Engineer", company: "CrowdStrike", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "Austin, TX", salary: "$150k - $200k", salaryMin: 150, salaryMax: 200, type: "Full-Time", remote: true, urgent: true, skills: ["Pen Testing", "SIEM", "Cloud Security"], posted: "3d ago", description: "Protect organizations from cyber threats with advanced security solutions.", benefits: ["Health insurance", "401k", "Security certifications"], experience: "Senior", category: "Engineering" },
  { id: 11, title: "Frontend Developer", company: "Vercel", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "Remote", salary: "$130k - $170k", salaryMin: 130, salaryMax: 170, type: "Full-Time", remote: true, urgent: false, skills: ["React", "TypeScript", "Next.js"], posted: "6h ago", description: "Build the platform for frontend developers and deploy the best web experiences.", benefits: ["Remote-first", "Equipment budget", "Conference attendance"], experience: "Mid", category: "Engineering" },
  { id: 12, title: "Financial Analyst", company: "Goldman Sachs", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", location: "New York, NY", salary: "$120k - $160k", salaryMin: 120, salaryMax: 160, type: "Full-Time", remote: false, urgent: false, skills: ["Financial Modeling", "Excel", "Python"], posted: "1d ago", description: "Analyze financial data and provide strategic insights for investment decisions.", benefits: ["Competitive salary", "Bonus structure", "Health insurance"], experience: "Mid", category: "Finance" },
];

export const SIMILAR_JOBS: SimilarJob[] = [
  { id: 13, title: "Staff Frontend Engineer", company: "Meta", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", salary: "$200k - $280k", type: "Full-Time" },
  { id: 14, title: "React Engineer", company: "Shopify", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", salary: "$150k - $200k", type: "Full-Time" },
  { id: 15, title: "UI Engineer", company: "Apple", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", salary: "$170k - $230k", type: "Full-Time" },
];

export const RECOMMENDED_JOBS: RecommendedJob[] = [
  { id: 16, title: "Full Stack Developer", company: "Supabase", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", salary: "$140k - $180k", match: 95, skills: ["React", "Node.js", "PostgreSQL"] },
  { id: 17, title: "Technical Writer", company: "GitLab", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", salary: "$100k - $140k", match: 88, skills: ["Documentation", "API", "Markdown"] },
  { id: 18, title: "Cloud Architect", company: "AWS", companyLogo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop", salary: "$190k - $260k", match: 82, skills: ["AWS", "Terraform", "Kubernetes"] },
];
