import type { FeaturedJob, Job, SimilarJob, RecommendedJob } from "../types";

export const FEATURED_JOBS: FeaturedJob[] = [
  {
    id: 1,
    title: "Senior Frontend Engineer",
    company: "Google",
    companyLogo: "https://logo.clearbit.com/google.com",
    location: "Mountain View, CA",
    salary: "$185,000 - $265,000",
    type: "Full-Time",
    remote: true,
    urgent: false,
    gradient: "from-blue-600 via-blue-500 to-cyan-400",
  },
  {
    id: 2,
    title: "Staff Product Designer",
    company: "Stripe",
    companyLogo: "https://logo.clearbit.com/stripe.com",
    location: "San Francisco, CA",
    salary: "$190,000 - $270,000",
    type: "Full-Time",
    remote: false,
    urgent: true,
    gradient: "from-violet-600 via-purple-500 to-fuchsia-400",
  },
  {
    id: 3,
    title: "Principal Engineer, Infrastructure",
    company: "Netflix",
    companyLogo: "https://logo.clearbit.com/netflix.com",
    location: "Los Gatos, CA",
    salary: "$310,000 - $480,000",
    type: "Full-Time",
    remote: true,
    urgent: false,
    gradient: "from-red-600 via-rose-500 to-pink-400",
  },
];

export const ALL_JOBS: Job[] = [
  {
    id: 4,
    title: "Senior Backend Engineer",
    company: "Stripe",
    companyLogo: "https://logo.clearbit.com/stripe.com",
    location: "San Francisco, CA",
    salary: "$175,000 - $250,000",
    salaryMin: 175,
    salaryMax: 250,
    type: "Full-Time",
    remote: true,
    urgent: false,
    skills: ["Go", "PostgreSQL", "Kubernetes", "gRPC"],
    posted: "2h ago",
    description:
      "Design and build scalable payment infrastructure that processes billions of dollars for millions of businesses worldwide. You will work on distributed systems at massive scale, collaborating with teams across the globe to define the future of internet commerce.",
    benefits: [
      "Health, dental & vision insurance",
      "401(k) with 4% match",
      "Unlimited PTO",
      "Equity compensation",
      "Home office stipend",
    ],
    experience: "Senior",
    category: "Engineering",
  },
  {
    id: 5,
    title: "UX Researcher",
    company: "Figma",
    companyLogo: "https://logo.clearbit.com/figma.com",
    location: "New York, NY",
    salary: "$135,000 - $180,000",
    salaryMin: 135,
    salaryMax: 180,
    type: "Full-Time",
    remote: false,
    urgent: false,
    skills: ["User Testing", "Figma", "Qualitative Research", "Survey Design"],
    posted: "5h ago",
    description:
      "Lead end-to-end research initiatives that shape the future of collaborative design tools. Partner closely with product and engineering to uncover user needs, validate hypotheses, and drive data-informed decisions across the platform.",
    benefits: [
      "Health & wellness benefits",
      "$5,000 annual learning budget",
      "Flexible work hours",
      "Equity grants",
      "Paid parental leave",
    ],
    experience: "Mid",
    category: "Design",
  },
  {
    id: 6,
    title: "Growth Marketing Manager",
    company: "Notion",
    companyLogo: "https://logo.clearbit.com/notion.so",
    location: "New York, NY",
    salary: "$145,000 - $195,000",
    salaryMin: 145,
    salaryMax: 195,
    type: "Full-Time",
    remote: true,
    urgent: false,
    skills: ["SEO", "Content Strategy", "Analytics", "Paid Acquisition"],
    posted: "1d ago",
    description:
      "Drive user acquisition and retention through innovative, data-driven marketing campaigns. Own the full marketing funnel from awareness to conversion, working cross-functionally with product, design, and engineering teams.",
    benefits: [
      "Health insurance",
      "Remote-first culture",
      "Stock options",
      "Annual retreat",
      "Professional development",
    ],
    experience: "Senior",
    category: "Marketing",
  },
  {
    id: 7,
    title: "Machine Learning Engineer",
    company: "OpenAI",
    companyLogo: "https://logo.clearbit.com/openai.com",
    location: "San Francisco, CA",
    salary: "$220,000 - $370,000",
    salaryMin: 220,
    salaryMax: 370,
    type: "Full-Time",
    remote: false,
    urgent: true,
    skills: ["Python", "PyTorch", "Transformers", "Distributed Systems"],
    posted: "3d ago",
    description:
      "Research and develop state-of-the-art AI models that push the boundaries of what artificial intelligence can achieve. Work alongside world-class researchers on problems at the frontier of capability, safety, and alignment.",
    benefits: [
      "Top-of-market compensation",
      "Significant equity package",
      "Research publication support",
      "Conference travel budget",
      "Premium healthcare",
    ],
    experience: "Senior",
    category: "Data",
  },
  {
    id: 8,
    title: "iOS Engineer",
    company: "Spotify",
    companyLogo: "https://logo.clearbit.com/spotify.com",
    location: "Stockholm, Sweden",
    salary: "$120,000 - $165,000",
    salaryMin: 120,
    salaryMax: 165,
    type: "Full-Time",
    remote: true,
    urgent: false,
    skills: ["Swift", "UIKit", "SwiftUI", "Core Audio"],
    posted: "1w ago",
    description:
      "Build the world's best music streaming experience used by over 600 million people. Work on features that directly impact how people discover, listen to, and share music and podcasts every day.",
    benefits: [
      "Health insurance",
      "Spotify Premium for family",
      "Flexible hybrid work",
      "Stock purchase plan",
      "Wellness allowance",
    ],
    experience: "Mid",
    category: "Engineering",
  },
  {
    id: 9,
    title: "Senior Product Manager",
    company: "Slack",
    companyLogo: "https://logo.clearbit.com/slack.com",
    location: "San Francisco, CA",
    salary: "$165,000 - $225,000",
    salaryMin: 165,
    salaryMax: 225,
    type: "Full-Time",
    remote: true,
    urgent: false,
    skills: ["Product Strategy", "Agile", "Data Analysis", "Cross-functional Leadership"],
    posted: "2d ago",
    description:
      "Define product vision and strategy for collaboration features used by millions of teams worldwide. Lead a cross-functional team to ship products that make work life simpler, more pleasant, and more productive.",
    benefits: [
      "Comprehensive health coverage",
      "Salesforce equity",
      "26 weeks parental leave",
      "Wellness reimbursement",
      "Learning & development",
    ],
    experience: "Senior",
    category: "Product",
  },
  {
    id: 10,
    title: "Cloud Security Engineer",
    company: "CrowdStrike",
    companyLogo: "https://logo.clearbit.com/crowdstrike.com",
    location: "Austin, TX",
    salary: "$155,000 - $210,000",
    salaryMin: 155,
    salaryMax: 210,
    type: "Full-Time",
    remote: true,
    urgent: true,
    skills: ["AWS", "SIEM", "Penetration Testing", "Terraform"],
    posted: "3d ago",
    description:
      "Protect the world's largest enterprises from advanced cyber threats. Design and implement cloud-native security solutions, conduct threat modeling, and build automated detection and response systems.",
    benefits: [
      "Health, dental & vision",
      "401(k) with match",
      "Certification reimbursement",
      "Remote work flexibility",
      "Stock purchase plan",
    ],
    experience: "Senior",
    category: "Engineering",
  },
  {
    id: 11,
    title: "Frontend Engineer",
    company: "Vercel",
    companyLogo: "https://logo.clearbit.com/vercel.com",
    location: "Remote",
    salary: "$140,000 - $185,000",
    salaryMin: 140,
    salaryMax: 185,
    type: "Full-Time",
    remote: true,
    urgent: false,
    skills: ["React", "TypeScript", "Next.js", "Turborepo"],
    posted: "6h ago",
    description:
      "Build the developer platform that powers the modern web. Work on Next.js, Turborepo, and the Vercel infrastructure that serves millions of deployments and billions of requests every month.",
    benefits: [
      "Remote-first team",
      "$5,000 equipment budget",
      "Annual team offsites",
      "Equity compensation",
      "Unlimited PTO",
    ],
    experience: "Mid",
    category: "Engineering",
  },
  {
    id: 12,
    title: "Quantitative Analyst",
    company: "Goldman Sachs",
    companyLogo: "https://logo.clearbit.com/goldmansachs.com",
    location: "New York, NY",
    salary: "$150,000 - $220,000",
    salaryMin: 150,
    salaryMax: 220,
    type: "Full-Time",
    remote: false,
    urgent: false,
    skills: ["Python", "SQL", "Statistical Modeling", "Time Series Analysis"],
    posted: "1d ago",
    description:
      "Develop quantitative models and analytical frameworks to drive investment decisions across global markets. Collaborate with portfolio managers and traders to optimize strategies and manage risk.",
    benefits: [
      "Competitive base salary",
      "Performance bonus",
      "Health & wellness",
      "401(k) plan",
      "Professional development",
    ],
    experience: "Mid",
    category: "Finance",
  },
  {
    id: 13,
    title: "Senior Data Engineer",
    company: "Databricks",
    companyLogo: "https://logo.clearbit.com/databricks.com",
    location: "San Francisco, CA",
    salary: "$180,000 - $260,000",
    salaryMin: 180,
    salaryMax: 260,
    type: "Full-Time",
    remote: true,
    urgent: false,
    skills: ["Spark", "Python", "Delta Lake", "Airflow"],
    posted: "8h ago",
    description:
      "Design and build the data infrastructure that powers the Lakehouse Platform. Work on large-scale data pipelines processing petabytes of data for thousands of enterprise customers worldwide.",
    benefits: [
      "Premium healthcare",
      "Equity grants",
      "Remote flexibility",
      "Conference budget",
      "Wellness perks",
    ],
    experience: "Senior",
    category: "Data",
  },
  {
    id: 14,
    title: "Head of Design",
    company: "Linear",
    companyLogo: "https://logo.clearbit.com/linear.app",
    location: "San Francisco, CA",
    salary: "$200,000 - $280,000",
    salaryMin: 200,
    salaryMax: 280,
    type: "Full-Time",
    remote: true,
    urgent: false,
    skills: ["Design Systems", "Product Strategy", "Team Leadership", "Figma"],
    posted: "4d ago",
    description:
      "Lead the design team at one of the fastest-growing developer tools companies. Define the design vision for Linear, building a world-class product experience that teams love to use every day.",
    benefits: [
      "Competitive compensation",
      "Meaningful equity",
      "Health benefits",
      "Flexible PTO",
      "Home office setup",
    ],
    experience: "Lead",
    category: "Design",
  },
  {
    id: 15,
    title: "Staff Software Engineer",
    company: "GitHub",
    companyLogo: "https://logo.clearbit.com/github.com",
    location: "Remote",
    salary: "$195,000 - $280,000",
    salaryMin: 195,
    salaryMax: 280,
    type: "Full-Time",
    remote: true,
    urgent: false,
    skills: ["Ruby on Rails", "React", "GraphQL", "MySQL"],
    posted: "12h ago",
    description:
      "Architect and build features for the world's largest developer platform. Lead technical initiatives that impact millions of developers and thousands of enterprises relying on GitHub daily.",
    benefits: [
      "Microsoft benefits package",
      "Unlimited PTO",
      "Home office budget",
      "Learning & development",
      "Wellness allowance",
    ],
    experience: "Senior",
    category: "Engineering",
  },
];

export const SIMILAR_JOBS: SimilarJob[] = [
  {
    id: 16,
    title: "Staff Frontend Engineer",
    company: "Meta",
    companyLogo: "https://logo.clearbit.com/meta.com",
    salary: "$210,000 - $295,000",
    type: "Full-Time",
  },
  {
    id: 17,
    title: "Senior React Engineer",
    company: "Shopify",
    companyLogo: "https://logo.clearbit.com/shopify.com",
    salary: "$155,000 - $210,000",
    type: "Full-Time",
  },
  {
    id: 18,
    title: "UI Engineer",
    company: "Apple",
    companyLogo: "https://logo.clearbit.com/apple.com",
    salary: "$175,000 - $245,000",
    type: "Full-Time",
  },
];

export const RECOMMENDED_JOBS: RecommendedJob[] = [
  {
    id: 19,
    title: "Full Stack Developer",
    company: "Supabase",
    companyLogo: "https://logo.clearbit.com/supabase.com",
    salary: "$145,000 - $190,000",
    match: 95,
    skills: ["React", "TypeScript", "PostgreSQL", "Edge Functions"],
  },
  {
    id: 20,
    title: "Technical Writer",
    company: "GitLab",
    companyLogo: "https://logo.clearbit.com/gitlab.com",
    salary: "$105,000 - $145,000",
    match: 88,
    skills: ["Documentation", "API Reference", "Markdown"],
  },
  {
    id: 21,
    title: "Solutions Architect",
    company: "AWS",
    companyLogo: "https://logo.clearbit.com/aws.amazon.com",
    salary: "$175,000 - $250,000",
    match: 82,
    skills: ["AWS", "Terraform", "Kubernetes", "Python"],
  },
];
