export const DASHBOARD_GRID_SOURCE = [
  'import { LayoutDashboard, BarChart3, Users, TrendingUp, Activity, PieChart } from "lucide-react";',
  '',
  'interface StatCardProps {',
  '  label: string;',
  '  value: string;',
  '  change?: string;',
  '  icon?: React.ReactNode;',
  '}',
  '',
  'function StatCard({ label, value, change, icon }: StatCardProps) {',
  '  const isPositive = change?.startsWith("+");',
  '  return (',
  '    <div className="rounded-lg border bg-background p-3">',
  '      <div className="flex items-center gap-2">',
  '        {icon}',
  '        <span className="text-[10px] text-muted-foreground">{label}</span>',
  '      </div>',
  '      <div className="mt-1 text-lg font-semibold">{value}</div>',
  '      {change && (',
  '        <div className={`text-[10px] ${isPositive ? "text-green-600 dark:text-green-400" : "text-red-600 dark:text-red-400"}`}>',
  '          {change}',
  '        </div>',
  '      )}',
  '    </div>',
  '  );',
  '}',
  '',
  'interface ProgressBarProps {',
  '  value: number;',
  '  color?: string;',
  '}',
  '',
  'function ProgressBar({ value, color = "bg-primary" }: ProgressBarProps) {',
  '  return (',
  '    <div className="h-1.5 rounded-full bg-muted">',
  '      <div className={`h-1.5 rounded-full ${color}`} style={{ width: `${value}%` }} />',
  '    </div>',
  '  );',
  '}',
  '',
  '// 4-Column Dashboard',
  'function DashboardBasic() {',
  '  return (',
  '    <div className="grid grid-cols-4 gap-3">',
  '      <StatCard label="Total Users" value="12,345" change="+12.5%" />',
  '      <StatCard label="Revenue" value="$48,290" change="+8.2%" />',
  '      <StatCard label="Orders" value="1,892" change="-3.1%" />',
  '      <StatCard label="Conversion" value="3.24%" change="+0.8%" />',
  '    </div>',
  '  );',
  '}',
  '',
  '// With Charts',
  'function DashboardWithCharts() {',
  '  return (',
  '    <div className="grid grid-cols-4 gap-3">',
  '      <div className="col-span-2 row-span-2 rounded-lg border bg-background p-4">',
  '        <div className="text-xs font-medium">Revenue Overview</div>',
  '        <div className="mt-4 flex h-24 items-end gap-1">',
  '          {[40,65,45,80,55,70,90,60,75,85,50,95].map((h, i) => (',
  '            <div key={i} className="flex-1 rounded-t bg-primary/20" style={{ height: `${h}%` }} />',
  '          ))}',
  '        </div>',
  '      </div>',
  '      <StatCard label="Active Users" value="2,847" icon={<Users className="h-3 w-3" />} />',
  '      <StatCard label="Growth" value="+24.5%" icon={<TrendingUp className="h-3 w-3" />} />',
  '    </div>',
  '  );',
  '}',
  '',
  '// Column Spanning',
  'function DashboardSpanning() {',
  '  return (',
  '    <div className="grid grid-cols-6 gap-3">',
  '      <div className="col-span-2 rounded-lg border bg-background p-3">',
  '        <div className="text-[10px] text-muted-foreground">Wide Card (span 2)</div>',
  '      </div>',
  '      <div className="col-span-4 rounded-lg border bg-background p-3">',
  '        <div className="text-[10px] text-muted-foreground">Extra Wide Card (span 4)</div>',
  '      </div>',
  '      <div className="col-span-3 rounded-lg border bg-background p-3">',
  '        <div className="text-[10px] text-muted-foreground">Half Width (span 3)</div>',
  '      </div>',
  '      <div className="col-span-3 rounded-lg border bg-background p-3">',
  '        <div className="text-[10px] text-muted-foreground">Half Width (span 3)</div>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
  '',
  '// KPI Dashboard',
  'function DashboardKPI() {',
  '  const kpis = [',
  '    { title: "Sales Target", value: "$125K", progress: 78, color: "bg-blue-500" },',
  '    { title: "New Users", value: "2,400", progress: 62, color: "bg-green-500" },',
  '  ];',
  '  return (',
  '    <div className="grid grid-cols-2 gap-3">',
  '      {kpis.map((k) => (',
  '        <div key={k.title} className="rounded-lg border bg-background p-4">',
  '          <div className="flex items-center justify-between">',
  '            <span className="text-xs text-muted-foreground">{k.title}</span>',
  '            <span className="text-sm font-semibold">{k.value}</span>',
  '          </div>',
  '          <div className="mt-2">',
  '            <ProgressBar value={k.progress} color={k.color} />',
  '          </div>',
  '        </div>',
  '      ))}',
  '    </div>',
  '  );',
  '}',
].join('\n');
