import type { ComponentTemplate } from "../types/studio";
import type { CanvasNode } from "../types/canvas";

export const COMPONENT_TEMPLATES: ComponentTemplate[] = [
  {
    id: "hero-section",
    name: "Hero Section",
    category: "layout",
    description: "Full-width hero with heading, subtext, and CTA button",
    preview: "hero",
    tags: ["hero", "landing", "header"],
    createdAt: Date.now(),
    props: {},
    nodes: {
      hero_container: {
        id: "hero_container",
        type: "container",
        componentName: "container",
        position: { x: 0, y: 0 },
        size: { width: 800, height: 400 },
        parentId: null,
        children: ["hero_heading", "hero_text", "hero_button"],
        props: {
          display: "flex",
          flexDirection: "col",
          gap: 24,
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "#f8fafc",
          borderRadius: 16,
          paddingTop: 64,
          paddingBottom: 64,
          paddingLeft: 32,
          paddingRight: 32,
        },
        zIndex: 0,
        locked: false,
        visible: true,
      },
      hero_heading: {
        id: "hero_heading",
        type: "component",
        componentName: "heading",
        position: { x: 200, y: 80 },
        size: { width: 400, height: 48 },
        parentId: "hero_container",
        children: [],
        props: { text: "Build Something Amazing", level: "h1", fontSize: 36, fontWeight: "800", color: "#111827" },
        zIndex: 1,
        locked: false,
        visible: true,
      },
      hero_text: {
        id: "hero_text",
        type: "component",
        componentName: "text",
        position: { x: 150, y: 140 },
        size: { width: 500, height: 24 },
        parentId: "hero_container",
        children: [],
        props: { text: "Create stunning interfaces with our component library. No code required.", fontSize: 16, fontWeight: "400", color: "#6b7280", textAlign: "center" },
        zIndex: 2,
        locked: false,
        visible: true,
      },
      hero_button: {
        id: "hero_button",
        type: "component",
        componentName: "button",
        position: { x: 320, y: 200 },
        size: { width: 160, height: 48 },
        parentId: "hero_container",
        children: [],
        props: { text: "Get Started", variant: "primary", size: "lg", borderRadius: 999 },
        zIndex: 3,
        locked: false,
        visible: true,
      },
    } as Record<string, CanvasNode>,
  },
  {
    id: "pricing-card",
    name: "Pricing Card",
    category: "layout",
    description: "Pricing card with title, price, features list, and CTA",
    preview: "pricing",
    tags: ["pricing", "card", "commercial"],
    createdAt: Date.now(),
    props: {},
    nodes: {
      pricing_card: {
        id: "pricing_card",
        type: "container",
        componentName: "card",
        position: { x: 0, y: 0 },
        size: { width: 320, height: 420 },
        parentId: null,
        children: ["pricing_badge", "pricing_heading", "pricing_price", "pricing_features", "pricing_button"],
        props: {
          backgroundColor: "#ffffff",
          borderWidth: 2,
          borderColor: "#e5e7eb",
          borderStyle: "solid",
          borderRadius: 16,
          shadow: "lg",
          paddingTop: 32,
          paddingBottom: 32,
          paddingLeft: 24,
          paddingRight: 24,
        },
        zIndex: 0,
        locked: false,
        visible: true,
      },
      pricing_badge: {
        id: "pricing_badge",
        type: "component",
        componentName: "badge",
        position: { x: 110, y: 24 },
        size: { width: 100, height: 28 },
        parentId: "pricing_card",
        children: [],
        props: { text: "Popular", variant: "primary", borderRadius: 999 },
        zIndex: 1,
        locked: false,
        visible: true,
      },
      pricing_heading: {
        id: "pricing_heading",
        type: "component",
        componentName: "heading",
        position: { x: 80, y: 72 },
        size: { width: 160, height: 36 },
        parentId: "pricing_card",
        children: [],
        props: { text: "Pro Plan", level: "h2", fontSize: 24, fontWeight: "700", color: "#111827" },
        zIndex: 2,
        locked: false,
        visible: true,
      },
      pricing_price: {
        id: "pricing_price",
        type: "component",
        componentName: "text",
        position: { x: 100, y: 120 },
        size: { width: 120, height: 40 },
        parentId: "pricing_card",
        children: [],
        props: { text: "$29/mo", fontSize: 32, fontWeight: "800", color: "#6366f1" },
        zIndex: 3,
        locked: false,
        visible: true,
      },
      pricing_features: {
        id: "pricing_features",
        type: "component",
        componentName: "list",
        position: { x: 40, y: 180 },
        size: { width: 240, height: 120 },
        parentId: "pricing_card",
        children: [],
        props: { items: "Unlimited projects,Priority support,Advanced analytics,Custom domain", ordered: false, fontSize: 14, color: "#374151", gap: 8 },
        zIndex: 4,
        locked: false,
        visible: true,
      },
      pricing_button: {
        id: "pricing_button",
        type: "component",
        componentName: "button",
        position: { x: 60, y: 340 },
        size: { width: 200, height: 48 },
        parentId: "pricing_card",
        children: [],
        props: { text: "Choose Plan", variant: "primary", size: "lg", borderRadius: 999 },
        zIndex: 5,
        locked: false,
        visible: true,
      },
    } as Record<string, CanvasNode>,
  },
  {
    id: "login-form",
    name: "Login Form",
    category: "forms",
    description: "Complete login form with email, password, and submit button",
    preview: "form",
    tags: ["login", "form", "auth"],
    createdAt: Date.now(),
    props: {},
    nodes: {
      login_container: {
        id: "login_container",
        type: "container",
        componentName: "card",
        position: { x: 0, y: 0 },
        size: { width: 380, height: 400 },
        parentId: null,
        children: ["login_heading", "login_email_label", "login_email", "login_pass_label", "login_pass", "login_button", "login_link"],
        props: {
          backgroundColor: "#ffffff",
          borderWidth: 1,
          borderColor: "#e5e7eb",
          borderStyle: "solid",
          borderRadius: 16,
          shadow: "lg",
          paddingTop: 40,
          paddingBottom: 40,
          paddingLeft: 32,
          paddingRight: 32,
        },
        zIndex: 0,
        locked: false,
        visible: true,
      },
      login_heading: {
        id: "login_heading",
        type: "component",
        componentName: "heading",
        position: { x: 110, y: 32 },
        size: { width: 160, height: 32 },
        parentId: "login_container",
        children: [],
        props: { text: "Welcome Back", level: "h2", fontSize: 24, fontWeight: "700", color: "#111827" },
        zIndex: 1,
        locked: false,
        visible: true,
      },
      login_email_label: {
        id: "login_email_label",
        type: "component",
        componentName: "text",
        position: { x: 32, y: 88 },
        size: { width: 100, height: 20 },
        parentId: "login_container",
        children: [],
        props: { text: "Email", fontSize: 14, fontWeight: "500", color: "#374151" },
        zIndex: 2,
        locked: false,
        visible: true,
      },
      login_email: {
        id: "login_email",
        type: "component",
        componentName: "input",
        position: { x: 32, y: 112 },
        size: { width: 296, height: 44 },
        parentId: "login_container",
        children: [],
        props: { placeholder: "you@example.com", inputType: "email", borderWidth: 1, borderColor: "#d1d5db", borderRadius: 8 },
        zIndex: 3,
        locked: false,
        visible: true,
      },
      login_pass_label: {
        id: "login_pass_label",
        type: "component",
        componentName: "text",
        position: { x: 32, y: 172 },
        size: { width: 100, height: 20 },
        parentId: "login_container",
        children: [],
        props: { text: "Password", fontSize: 14, fontWeight: "500", color: "#374151" },
        zIndex: 4,
        locked: false,
        visible: true,
      },
      login_pass: {
        id: "login_pass",
        type: "component",
        componentName: "input",
        position: { x: 32, y: 196 },
        size: { width: 296, height: 44 },
        parentId: "login_container",
        children: [],
        props: { placeholder: "Enter your password", inputType: "password", borderWidth: 1, borderColor: "#d1d5db", borderRadius: 8 },
        zIndex: 5,
        locked: false,
        visible: true,
      },
      login_button: {
        id: "login_button",
        type: "component",
        componentName: "button",
        position: { x: 32, y: 268 },
        size: { width: 296, height: 48 },
        parentId: "login_container",
        children: [],
        props: { text: "Sign In", variant: "primary", size: "lg", borderRadius: 999 },
        zIndex: 6,
        locked: false,
        visible: true,
      },
      login_link: {
        id: "login_link",
        type: "component",
        componentName: "link",
        position: { x: 110, y: 340 },
        size: { width: 160, height: 24 },
        parentId: "login_container",
        children: [],
        props: { text: "Forgot password?", color: "#6366f1", textDecoration: "underline", fontSize: 14 },
        zIndex: 7,
        locked: false,
        visible: true,
      },
    } as Record<string, CanvasNode>,
  },
  {
    id: "alert-banner",
    name: "Alert Banner",
    category: "feedback",
    description: "Dismissible alert with icon, title, and description",
    preview: "alert",
    tags: ["alert", "notification", "banner"],
    createdAt: Date.now(),
    props: {},
    nodes: {
      alert_node: {
        id: "alert_node",
        type: "component",
        componentName: "alert",
        position: { x: 0, y: 0 },
        size: { width: 400, height: 80 },
        parentId: null,
        children: [],
        props: {
          title: "Success!",
          description: "Your changes have been saved successfully.",
          variant: "success",
          closable: true,
          borderRadius: 12,
        },
        zIndex: 0,
        locked: false,
        visible: true,
      },
    } as Record<string, CanvasNode>,
  },
  {
    id: "user-profile",
    name: "User Profile Card",
    category: "layout",
    description: "Profile card with avatar, name, bio, and action buttons",
    preview: "profile",
    tags: ["profile", "user", "card"],
    createdAt: Date.now(),
    props: {},
    nodes: {
      profile_card: {
        id: "profile_card",
        type: "container",
        componentName: "card",
        position: { x: 0, y: 0 },
        size: { width: 320, height: 280 },
        parentId: null,
        children: ["profile_avatar", "profile_name", "profile_bio", "profile_button"],
        props: {
          backgroundColor: "#ffffff",
          borderWidth: 1,
          borderColor: "#e5e7eb",
          borderStyle: "solid",
          borderRadius: 16,
          shadow: "md",
          paddingTop: 32,
          paddingBottom: 24,
          paddingLeft: 24,
          paddingRight: 24,
        },
        zIndex: 0,
        locked: false,
        visible: true,
      },
      profile_avatar: {
        id: "profile_avatar",
        type: "component",
        componentName: "avatar",
        position: { x: 136, y: 24 },
        size: { width: 48, height: 48 },
        parentId: "profile_card",
        children: [],
        props: { initials: "JD", size: "md", borderRadius: 999, backgroundColor: "#6366f1", textColor: "#ffffff" },
        zIndex: 1,
        locked: false,
        visible: true,
      },
      profile_name: {
        id: "profile_name",
        type: "component",
        componentName: "heading",
        position: { x: 80, y: 88 },
        size: { width: 160, height: 28 },
        parentId: "profile_card",
        children: [],
        props: { text: "Jane Doe", level: "h3", fontSize: 20, fontWeight: "700", color: "#111827" },
        zIndex: 2,
        locked: false,
        visible: true,
      },
      profile_bio: {
        id: "profile_bio",
        type: "component",
        componentName: "text",
        position: { x: 40, y: 128 },
        size: { width: 240, height: 40 },
        parentId: "profile_card",
        children: [],
        props: { text: "Product Designer & Frontend Developer", fontSize: 14, fontWeight: "400", color: "#6b7280", textAlign: "center" },
        zIndex: 3,
        locked: false,
        visible: true,
      },
      profile_button: {
        id: "profile_button",
        type: "component",
        componentName: "button",
        position: { x: 80, y: 200 },
        size: { width: 160, height: 40 },
        parentId: "profile_card",
        children: [],
        props: { text: "View Profile", variant: "outline", size: "md", borderRadius: 999 },
        zIndex: 4,
        locked: false,
        visible: true,
      },
    } as Record<string, CanvasNode>,
  },
];

export function getTemplatesByCategory(category: string): ComponentTemplate[] {
  return COMPONENT_TEMPLATES.filter((t) => t.category === category);
}

export function searchTemplates(query: string): ComponentTemplate[] {
  const lower = query.toLowerCase();
  return COMPONENT_TEMPLATES.filter(
    (t) =>
      t.name.toLowerCase().includes(lower) ||
      t.description.toLowerCase().includes(lower) ||
      t.tags.some((tag) => tag.includes(lower))
  );
}
