import {
  Play,
  RefreshCw,
  AlignLeft,
  Save,
  Download,
  Share2,
  Copy,
  Trash2,
  Plus,
  Minus,
  File,
  Code,
  Folder,
  FolderOpen,
  Search,
  Terminal,
  Bug,
  History,
  Bookmark,
  Star,
  Grid3x3,
  Image,
  Layout,
  Sparkles,
  Eye,
  RotateCcw,
  ZoomIn,
  ZoomOut,
  Maximize2,
  Minimize2,
  Sun,
  Moon,
  PanelLeft,
  PanelBottom,
  X,
  ChevronRight,
  ChevronDown,
  Check,
  AlertTriangle,
  AlertCircle,
  Info,
  MoreVertical,
  Settings,
  Undo,
  Redo,
  Pencil,
  Zap,
  Box,
  ExternalLink,
  Tag,
  Loader2,
  Columns,
  GitBranch,
  Database,
  User,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  play: Play,
  refresh: RefreshCw,
  format: AlignLeft,
  save: Save,
  download: Download,
  share: Share2,
  copy: Copy,
  trash: Trash2,
  plus: Plus,
  minus: Minus,
  file: File,
  code: Code,
  folder: Folder,
  folderOpen: FolderOpen,
  search: Search,
  terminal: Terminal,
  bug: Bug,
  history: History,
  bookmark: Bookmark,
  star: Star,
  grid: Grid3x3,
  image: Image,
  layout: Layout,
  sparkles: Sparkles,
  eye: Eye,
  rotate: RotateCcw,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  maximize: Maximize2,
  minimize: Minimize2,
  sun: Sun,
  moon: Moon,
  panelLeft: PanelLeft,
  panelBottom: PanelBottom,
  x: X,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  check: Check,
  alert: AlertTriangle,
  alertCircle: AlertCircle,
  info: Info,
  more: MoreVertical,
  settings: Settings,
  undo: Undo,
  redo: Redo,
  pencil: Pencil,
  zap: Zap,
  box: Box,
  external: ExternalLink,
  tag: Tag,
  loader: Loader2,
  split: Columns,
  gitBranch: GitBranch,
  database: Database,
  user: User,
};

export type IconName = keyof typeof iconMap;

export interface IconProps {
  name: IconName;
  className?: string;
  size?: number;
}

export function Icon({ name, className = "", size = 16 }: IconProps) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) return null;
  return <LucideIcon className={`shrink-0 ${className}`} size={size} aria-hidden="true" />;
}
